/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#pragma GCC diagnostic push
//#pragma GCC diagnostic ignored "-Wunused-variable"
#pragma GCC diagnostic ignored "-Wunused-parameter"
//#pragma GCC diagnostic ignored "-Wuninitialized"

#include "isp_rpc.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static RPC_CVI_S32 *
_rpc_cvi_isp_setpubattr_1 (rpc_cvi_isp_setpubattr_1_argument *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_setpubattr_1_svc(argp->ViPipe, argp->stAttrData, rqstp));
}

static RPC_ISP_GET_ATTR_DATA_S *
_rpc_cvi_isp_getpubattr_1 (RPC_VI_PIPE  *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_getpubattr_1_svc(*argp, rqstp));
}

static RPC_CVI_S32 *
_rpc_cvi_isp_setmodparam_1 (RPC_ISP_SET_ATTR_DATA_S  *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_setmodparam_1_svc(*argp, rqstp));
}

static RPC_ISP_GET_ATTR_DATA_S *
_rpc_cvi_isp_getmodparam_1 (void  *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_getmodparam_1_svc(rqstp));
}

static RPC_CVI_S32 *
_rpc_cvi_isp_setctrlparam_1 (rpc_cvi_isp_setctrlparam_1_argument *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_setctrlparam_1_svc(argp->ViPipe, argp->stAttrData, rqstp));
}

static RPC_ISP_GET_ATTR_DATA_S *
_rpc_cvi_isp_getctrlparam_1 (RPC_VI_PIPE  *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_getctrlparam_1_svc(*argp, rqstp));
}

static RPC_CVI_S32 *
_rpc_cvi_isp_setfmwstate_1 (rpc_cvi_isp_setfmwstate_1_argument *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_setfmwstate_1_svc(argp->ViPipe, argp->enState, rqstp));
}

static uint32_t *
_rpc_cvi_isp_getfmwstate_1 (RPC_VI_PIPE  *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_getfmwstate_1_svc(*argp, rqstp));
}

static RPC_CVI_S32 *
_rpc_cvi_isp_setmodulecontrol_1 (rpc_cvi_isp_setmodulecontrol_1_argument *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_setmodulecontrol_1_svc(argp->ViPipe, argp->stAttrData, rqstp));
}

static RPC_ISP_GET_ATTR_DATA_S *
_rpc_cvi_isp_getmodulecontrol_1 (RPC_VI_PIPE  *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_getmodulecontrol_1_svc(*argp, rqstp));
}

static RPC_CVI_S32 *
_rpc_cvi_isp_setregister_1 (rpc_cvi_isp_setregister_1_argument *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_setregister_1_svc(argp->ViPipe, argp->u32Addr, argp->u32Value, rqstp));
}

static uint32_t *
_rpc_cvi_isp_getregister_1 (rpc_cvi_isp_getregister_1_argument *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_getregister_1_svc(argp->ViPipe, argp->u32Addr, rqstp));
}

static RPC_CVI_S32 *
_rpc_cvi_isp_setcolortoneattr_1 (rpc_cvi_isp_setcolortoneattr_1_argument *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_setcolortoneattr_1_svc(argp->ViPipe, argp->stAttrData, rqstp));
}

static RPC_ISP_GET_ATTR_DATA_S *
_rpc_cvi_isp_getcolortoneattr_1 (RPC_VI_PIPE  *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_getcolortoneattr_1_svc(*argp, rqstp));
}

static RPC_CVI_S32 *
_rpc_cvi_isp_setdehazeattr_1 (rpc_cvi_isp_setdehazeattr_1_argument *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_setdehazeattr_1_svc(argp->ViPipe, argp->stAttrData, rqstp));
}

static RPC_ISP_GET_ATTR_DATA_S *
_rpc_cvi_isp_getdehazeattr_1 (RPC_VI_PIPE  *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_getdehazeattr_1_svc(*argp, rqstp));
}

static RPC_CVI_S32 *
_rpc_cvi_isp_setgammaattr_1 (rpc_cvi_isp_setgammaattr_1_argument *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_setgammaattr_1_svc(argp->ViPipe, argp->stAttrData, rqstp));
}

static RPC_ISP_GET_ATTR_DATA_S *
_rpc_cvi_isp_getgammaattr_1 (RPC_VI_PIPE  *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_getgammaattr_1_svc(*argp, rqstp));
}

static RPC_CVI_S32 *
_rpc_cvi_isp_setgammacurvetype_1 (rpc_cvi_isp_setgammacurvetype_1_argument *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_setgammacurvetype_1_svc(argp->ViPipe, argp->curveType, rqstp));
}

static RPC_CVI_S32 *
_rpc_cvi_isp_setautogammaattr_1 (rpc_cvi_isp_setautogammaattr_1_argument *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_setautogammaattr_1_svc(argp->ViPipe, argp->stAttrData, rqstp));
}

static RPC_ISP_GET_ATTR_DATA_S *
_rpc_cvi_isp_getautogammaattr_1 (RPC_VI_PIPE  *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_getautogammaattr_1_svc(*argp, rqstp));
}

static RPC_CVI_S32 *
_rpc_cvi_isp_setstatisticsconfig_1 (rpc_cvi_isp_setstatisticsconfig_1_argument *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_setstatisticsconfig_1_svc(argp->ViPipe, argp->stAttrData, rqstp));
}

static RPC_ISP_GET_ATTR_DATA_S *
_rpc_cvi_isp_getstatisticsconfig_1 (RPC_VI_PIPE  *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_getstatisticsconfig_1_svc(*argp, rqstp));
}

static RPC_CVI_S32 *
_rpc_cvi_isp_setnrattr_1 (rpc_cvi_isp_setnrattr_1_argument *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_setnrattr_1_svc(argp->ViPipe, argp->stAttrData, rqstp));
}

static RPC_ISP_GET_ATTR_DATA_S *
_rpc_cvi_isp_getnrattr_1 (RPC_VI_PIPE  *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_getnrattr_1_svc(*argp, rqstp));
}

static RPC_CVI_S32 *
_rpc_cvi_isp_setnrfilterattr_1 (rpc_cvi_isp_setnrfilterattr_1_argument *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_setnrfilterattr_1_svc(argp->ViPipe, argp->stAttrData, rqstp));
}

static RPC_ISP_GET_ATTR_DATA_S *
_rpc_cvi_isp_getnrfilterattr_1 (RPC_VI_PIPE  *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_getnrfilterattr_1_svc(*argp, rqstp));
}

static RPC_CVI_S32 *
_rpc_cvi_isp_setrlscattr_1 (rpc_cvi_isp_setrlscattr_1_argument *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_setrlscattr_1_svc(argp->ViPipe, argp->stAttrData, rqstp));
}

static RPC_ISP_GET_ATTR_DATA_S *
_rpc_cvi_isp_getrlscattr_1 (RPC_VI_PIPE  *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_getrlscattr_1_svc(*argp, rqstp));
}

static RPC_CVI_S32 *
_rpc_cvi_isp_setynrattr_1 (rpc_cvi_isp_setynrattr_1_argument *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_setynrattr_1_svc(argp->ViPipe, argp->stAttrData, rqstp));
}

static RPC_ISP_GET_ATTR_DATA_S *
_rpc_cvi_isp_getynrattr_1 (RPC_VI_PIPE  *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_getynrattr_1_svc(*argp, rqstp));
}

static RPC_CVI_S32 *
_rpc_cvi_isp_setynrmotionnrattr_1 (rpc_cvi_isp_setynrmotionnrattr_1_argument *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_setynrmotionnrattr_1_svc(argp->ViPipe, argp->stAttrData, rqstp));
}

static RPC_ISP_GET_ATTR_DATA_S *
_rpc_cvi_isp_getynrmotionnrattr_1 (RPC_VI_PIPE  *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_getynrmotionnrattr_1_svc(*argp, rqstp));
}

static RPC_CVI_S32 *
_rpc_cvi_isp_setynrfilterattr_1 (rpc_cvi_isp_setynrfilterattr_1_argument *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_setynrfilterattr_1_svc(argp->ViPipe, argp->stAttrData, rqstp));
}

static RPC_ISP_GET_ATTR_DATA_S *
_rpc_cvi_isp_getynrfilterattr_1 (RPC_VI_PIPE  *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_getynrfilterattr_1_svc(*argp, rqstp));
}

static RPC_CVI_S32 *
_rpc_cvi_isp_setcnrattr_1 (rpc_cvi_isp_setcnrattr_1_argument *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_setcnrattr_1_svc(argp->ViPipe, argp->stAttrData, rqstp));
}

static RPC_ISP_GET_ATTR_DATA_S *
_rpc_cvi_isp_getcnrattr_1 (RPC_VI_PIPE  *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_getcnrattr_1_svc(*argp, rqstp));
}

static RPC_CVI_S32 *
_rpc_cvi_isp_setcacattr_1 (rpc_cvi_isp_setcacattr_1_argument *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_setcacattr_1_svc(argp->ViPipe, argp->stAttrData, rqstp));
}

static RPC_ISP_GET_ATTR_DATA_S *
_rpc_cvi_isp_getcacattr_1 (RPC_VI_PIPE  *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_getcacattr_1_svc(*argp, rqstp));
}

static RPC_CVI_S32 *
_rpc_cvi_isp_setdciattr_1 (rpc_cvi_isp_setdciattr_1_argument *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_setdciattr_1_svc(argp->ViPipe, argp->stAttrData, rqstp));
}

static RPC_ISP_GET_ATTR_DATA_S *
_rpc_cvi_isp_getdciattr_1 (RPC_VI_PIPE  *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_getdciattr_1_svc(*argp, rqstp));
}

static RPC_CVI_S32 *
_rpc_cvi_isp_setmeshshadingattr_1 (rpc_cvi_isp_setmeshshadingattr_1_argument *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_setmeshshadingattr_1_svc(argp->ViPipe, argp->stAttrData, rqstp));
}

static RPC_ISP_GET_ATTR_DATA_S *
_rpc_cvi_isp_getmeshshadingattr_1 (RPC_VI_PIPE  *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_getmeshshadingattr_1_svc(*argp, rqstp));
}

static RPC_CVI_S32 *
_rpc_cvi_isp_setmeshshadinggainlutattr_1 (rpc_cvi_isp_setmeshshadinggainlutattr_1_argument *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_setmeshshadinggainlutattr_1_svc(argp->ViPipe, argp->stAttrData, rqstp));
}

static RPC_ISP_GET_ATTR_DATA_S *
_rpc_cvi_isp_getmeshshadinggainlutattr_1 (RPC_VI_PIPE  *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_getmeshshadinggainlutattr_1_svc(*argp, rqstp));
}

static RPC_CVI_S32 *
_rpc_cvi_isp_setradialshadingattr_1 (rpc_cvi_isp_setradialshadingattr_1_argument *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_setradialshadingattr_1_svc(argp->ViPipe, argp->stAttrData, rqstp));
}

static RPC_ISP_GET_ATTR_DATA_S *
_rpc_cvi_isp_getradialshadingattr_1 (RPC_VI_PIPE  *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_getradialshadingattr_1_svc(*argp, rqstp));
}

static RPC_CVI_S32 *
_rpc_cvi_isp_setradialshadinggainlutattr_1 (rpc_cvi_isp_setradialshadinggainlutattr_1_argument *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_setradialshadinggainlutattr_1_svc(argp->ViPipe, argp->stAttrData, rqstp));
}

static RPC_ISP_GET_ATTR_DATA_S *
_rpc_cvi_isp_getradialshadinggainlutattr_1 (RPC_VI_PIPE  *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_getradialshadinggainlutattr_1_svc(*argp, rqstp));
}

static RPC_CVI_S32 *
_rpc_cvi_isp_settnrattr_1 (rpc_cvi_isp_settnrattr_1_argument *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_settnrattr_1_svc(argp->ViPipe, argp->stAttrData, rqstp));
}

static RPC_ISP_GET_ATTR_DATA_S *
_rpc_cvi_isp_gettnrattr_1 (RPC_VI_PIPE  *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_gettnrattr_1_svc(*argp, rqstp));
}

static RPC_CVI_S32 *
_rpc_cvi_isp_settnrnoisemodelattr_1 (rpc_cvi_isp_settnrnoisemodelattr_1_argument *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_settnrnoisemodelattr_1_svc(argp->ViPipe, argp->stAttrData, rqstp));
}

static RPC_ISP_GET_ATTR_DATA_S *
_rpc_cvi_isp_gettnrnoisemodelattr_1 (RPC_VI_PIPE  *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_gettnrnoisemodelattr_1_svc(*argp, rqstp));
}

static RPC_CVI_S32 *
_rpc_cvi_isp_settnrlumamotionattr_1 (rpc_cvi_isp_settnrlumamotionattr_1_argument *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_settnrlumamotionattr_1_svc(argp->ViPipe, argp->stAttrData, rqstp));
}

static RPC_ISP_GET_ATTR_DATA_S *
_rpc_cvi_isp_gettnrlumamotionattr_1 (RPC_VI_PIPE  *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_gettnrlumamotionattr_1_svc(*argp, rqstp));
}

static RPC_CVI_S32 *
_rpc_cvi_isp_settnrghostattr_1 (rpc_cvi_isp_settnrghostattr_1_argument *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_settnrghostattr_1_svc(argp->ViPipe, argp->stAttrData, rqstp));
}

static RPC_ISP_GET_ATTR_DATA_S *
_rpc_cvi_isp_gettnrghostattr_1 (RPC_VI_PIPE  *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_gettnrghostattr_1_svc(*argp, rqstp));
}

static RPC_CVI_S32 *
_rpc_cvi_isp_settnrmtprtattr_1 (rpc_cvi_isp_settnrmtprtattr_1_argument *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_settnrmtprtattr_1_svc(argp->ViPipe, argp->stAttrData, rqstp));
}

static RPC_ISP_GET_ATTR_DATA_S *
_rpc_cvi_isp_gettnrmtprtattr_1 (RPC_VI_PIPE  *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_gettnrmtprtattr_1_svc(*argp, rqstp));
}

static RPC_CVI_S32 *
_rpc_cvi_isp_setclutattr_1 (rpc_cvi_isp_setclutattr_1_argument *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_setclutattr_1_svc(argp->ViPipe, argp->stAttrData, rqstp));
}

static RPC_ISP_GET_ATTR_DATA_S *
_rpc_cvi_isp_getclutattr_1 (RPC_VI_PIPE  *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_getclutattr_1_svc(*argp, rqstp));
}

static RPC_CVI_S32 *
_rpc_cvi_isp_setclutcoeff_1 (rpc_cvi_isp_setclutcoeff_1_argument *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_setclutcoeff_1_svc(argp->ViPipe, argp->stAttrData, rqstp));
}

static RPC_ISP_GET_ATTR_DATA_S *
_rpc_cvi_isp_getclutcoeff_1 (RPC_VI_PIPE  *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_getclutcoeff_1_svc(*argp, rqstp));
}

static RPC_CVI_S32 *
_rpc_cvi_isp_setblacklevelattr_1 (rpc_cvi_isp_setblacklevelattr_1_argument *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_setblacklevelattr_1_svc(argp->ViPipe, argp->stAttrData, rqstp));
}

static RPC_ISP_GET_ATTR_DATA_S *
_rpc_cvi_isp_getblacklevelattr_1 (RPC_VI_PIPE  *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_getblacklevelattr_1_svc(*argp, rqstp));
}

static RPC_CVI_S32 *
_rpc_cvi_isp_setdemosaicattr_1 (rpc_cvi_isp_setdemosaicattr_1_argument *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_setdemosaicattr_1_svc(argp->ViPipe, argp->stAttrData, rqstp));
}

static RPC_ISP_GET_ATTR_DATA_S *
_rpc_cvi_isp_getdemosaicattr_1 (RPC_VI_PIPE  *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_getdemosaicattr_1_svc(*argp, rqstp));
}

static RPC_CVI_S32 *
_rpc_cvi_isp_setdemosaicdemoireattr_1 (rpc_cvi_isp_setdemosaicdemoireattr_1_argument *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_setdemosaicdemoireattr_1_svc(argp->ViPipe, argp->stAttrData, rqstp));
}

static RPC_ISP_GET_ATTR_DATA_S *
_rpc_cvi_isp_getdemosaicdemoireattr_1 (RPC_VI_PIPE  *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_getdemosaicdemoireattr_1_svc(*argp, rqstp));
}

static RPC_CVI_S32 *
_rpc_cvi_isp_setdemosaicfilterattr_1 (rpc_cvi_isp_setdemosaicfilterattr_1_argument *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_setdemosaicfilterattr_1_svc(argp->ViPipe, argp->stAttrData, rqstp));
}

static RPC_ISP_GET_ATTR_DATA_S *
_rpc_cvi_isp_getdemosaicfilterattr_1 (RPC_VI_PIPE  *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_getdemosaicfilterattr_1_svc(*argp, rqstp));
}

static RPC_CVI_S32 *
_rpc_cvi_isp_setdemosaiceeattr_1 (rpc_cvi_isp_setdemosaiceeattr_1_argument *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_setdemosaiceeattr_1_svc(argp->ViPipe, argp->stAttrData, rqstp));
}

static RPC_ISP_GET_ATTR_DATA_S *
_rpc_cvi_isp_getdemosaiceeattr_1 (RPC_VI_PIPE  *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_getdemosaiceeattr_1_svc(*argp, rqstp));
}

static RPC_CVI_S32 *
_rpc_cvi_isp_setsaturationattr_1 (rpc_cvi_isp_setsaturationattr_1_argument *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_setsaturationattr_1_svc(argp->ViPipe, argp->stAttrData, rqstp));
}

static RPC_ISP_GET_ATTR_DATA_S *
_rpc_cvi_isp_getsaturationattr_1 (RPC_VI_PIPE  *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_getsaturationattr_1_svc(*argp, rqstp));
}

static RPC_CVI_S32 *
_rpc_cvi_isp_setccmattr_1 (rpc_cvi_isp_setccmattr_1_argument *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_setccmattr_1_svc(argp->ViPipe, argp->stAttrData, rqstp));
}

static RPC_ISP_GET_ATTR_DATA_S *
_rpc_cvi_isp_getccmattr_1 (RPC_VI_PIPE  *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_getccmattr_1_svc(*argp, rqstp));
}

static RPC_CVI_S32 *
_rpc_cvi_isp_sethsvattr_1 (rpc_cvi_isp_sethsvattr_1_argument *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_sethsvattr_1_svc(argp->ViPipe, argp->stAttrData, rqstp));
}

static RPC_ISP_GET_ATTR_DATA_S *
_rpc_cvi_isp_gethsvattr_1 (RPC_VI_PIPE  *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_gethsvattr_1_svc(*argp, rqstp));
}

static RPC_CVI_S32 *
_rpc_cvi_isp_setdpdynamicattr_1 (rpc_cvi_isp_setdpdynamicattr_1_argument *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_setdpdynamicattr_1_svc(argp->ViPipe, argp->stAttrData, rqstp));
}

static RPC_ISP_GET_ATTR_DATA_S *
_rpc_cvi_isp_getdpdynamicattr_1 (RPC_VI_PIPE  *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_getdpdynamicattr_1_svc(*argp, rqstp));
}

static RPC_CVI_S32 *
_rpc_cvi_isp_setdpstaticattr_1 (rpc_cvi_isp_setdpstaticattr_1_argument *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_setdpstaticattr_1_svc(argp->ViPipe, argp->stAttrData, rqstp));
}

static RPC_ISP_GET_ATTR_DATA_S *
_rpc_cvi_isp_getdpstaticattr_1 (RPC_VI_PIPE  *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_getdpstaticattr_1_svc(*argp, rqstp));
}

static RPC_CVI_S32 *
_rpc_cvi_isp_setdpcalibrate_1 (rpc_cvi_isp_setdpcalibrate_1_argument *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_setdpcalibrate_1_svc(argp->ViPipe, argp->stAttrData, rqstp));
}

static RPC_ISP_GET_ATTR_DATA_S *
_rpc_cvi_isp_getdpcalibrate_1 (RPC_VI_PIPE  *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_getdpcalibrate_1_svc(*argp, rqstp));
}

static RPC_CVI_S32 *
_rpc_cvi_isp_setcrosstalkattr_1 (rpc_cvi_isp_setcrosstalkattr_1_argument *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_setcrosstalkattr_1_svc(argp->ViPipe, argp->stAttrData, rqstp));
}

static RPC_ISP_GET_ATTR_DATA_S *
_rpc_cvi_isp_getcrosstalkattr_1 (RPC_VI_PIPE  *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_getcrosstalkattr_1_svc(*argp, rqstp));
}

static RPC_ISP_GET_ATTR_DATA_S *
_rpc_cvi_isp_getaestatistics_1 (RPC_VI_PIPE  *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_getaestatistics_1_svc(*argp, rqstp));
}

static RPC_ISP_GET_ATTR_DATA_S *
_rpc_cvi_isp_getwbstatistics_1 (RPC_VI_PIPE  *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_getwbstatistics_1_svc(*argp, rqstp));
}

static RPC_ISP_GET_ATTR_DATA_S *
_rpc_cvi_isp_getfocusstatistics_1 (RPC_VI_PIPE  *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_getfocusstatistics_1_svc(*argp, rqstp));
}

static RPC_ISP_GET_ATTR_DATA_S *
_rpc_cvi_isp_getlightboxgain_1 (RPC_VI_PIPE  *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_getlightboxgain_1_svc(*argp, rqstp));
}

static RPC_CVI_S32 *
_rpc_cvi_isp_setfswdrattr_1 (rpc_cvi_isp_setfswdrattr_1_argument *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_setfswdrattr_1_svc(argp->ViPipe, argp->stAttrData, rqstp));
}

static RPC_ISP_GET_ATTR_DATA_S *
_rpc_cvi_isp_getfswdrattr_1 (RPC_VI_PIPE  *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_getfswdrattr_1_svc(*argp, rqstp));
}

static RPC_CVI_S32 *
_rpc_cvi_isp_setdrcattr_1 (rpc_cvi_isp_setdrcattr_1_argument *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_setdrcattr_1_svc(argp->ViPipe, argp->stAttrData, rqstp));
}

static RPC_ISP_GET_ATTR_DATA_S *
_rpc_cvi_isp_getdrcattr_1 (RPC_VI_PIPE  *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_getdrcattr_1_svc(*argp, rqstp));
}

static RPC_CVI_S32 *
_rpc_cvi_isp_setsharpenattr_1 (rpc_cvi_isp_setsharpenattr_1_argument *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_setsharpenattr_1_svc(argp->ViPipe, argp->stAttrData, rqstp));
}

static RPC_ISP_GET_ATTR_DATA_S *
_rpc_cvi_isp_getsharpenattr_1 (RPC_VI_PIPE  *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_getsharpenattr_1_svc(*argp, rqstp));
}

static RPC_CVI_S32 *
_rpc_cvi_isp_setnoiseprofileattr_1 (rpc_cvi_isp_setnoiseprofileattr_1_argument *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_setnoiseprofileattr_1_svc(argp->ViPipe, argp->stAttrData, rqstp));
}

static RPC_ISP_GET_ATTR_DATA_S *
_rpc_cvi_isp_getnoiseprofileattr_1 (RPC_VI_PIPE  *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_getnoiseprofileattr_1_svc(*argp, rqstp));
}

static RPC_CVI_S32 *
_rpc_cvi_isp_setycontrastattr_1 (rpc_cvi_isp_setycontrastattr_1_argument *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_setycontrastattr_1_svc(argp->ViPipe, argp->stAttrData, rqstp));
}

static RPC_ISP_GET_ATTR_DATA_S *
_rpc_cvi_isp_getycontrastattr_1 (RPC_VI_PIPE  *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_getycontrastattr_1_svc(*argp, rqstp));
}

static RPC_CVI_S32 *
_rpc_cvi_isp_setdcfinfo_1 (rpc_cvi_isp_setdcfinfo_1_argument *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_setdcfinfo_1_svc(argp->ViPipe, argp->stAttrData, rqstp));
}

static RPC_ISP_GET_ATTR_DATA_S *
_rpc_cvi_isp_getdcfinfo_1 (RPC_VI_PIPE  *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_getdcfinfo_1_svc(*argp, rqstp));
}

static RPC_ISP_GET_ATTR_DATA_S *
_rpc_cvi_isp_queryinnerstateinfo_1 (RPC_VI_PIPE  *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_queryinnerstateinfo_1_svc(*argp, rqstp));
}

static RPC_CVI_S32 *
_rpc_cvi_isp_getvdtimeout_1 (rpc_cvi_isp_getvdtimeout_1_argument *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_getvdtimeout_1_svc(argp->ViPipe, argp->enIspVDType, argp->u32MilliSec, rqstp));
}

static RPC_CVI_S32 *
_rpc_cvi_isp_setmonoattr_1 (rpc_cvi_isp_setmonoattr_1_argument *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_setmonoattr_1_svc(argp->ViPipe, argp->stAttrData, rqstp));
}

static RPC_ISP_GET_ATTR_DATA_S *
_rpc_cvi_isp_getmonoattr_1 (RPC_VI_PIPE  *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_getmonoattr_1_svc(*argp, rqstp));
}

static RPC_CVI_S32 *
_rpc_cvi_isp_setdisattr_1 (rpc_cvi_isp_setdisattr_1_argument *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_setdisattr_1_svc(argp->ViPipe, argp->stAttrData, rqstp));
}

static RPC_ISP_GET_ATTR_DATA_S *
_rpc_cvi_isp_getdisattr_1 (RPC_VI_PIPE  *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_getdisattr_1_svc(*argp, rqstp));
}

static RPC_CVI_S32 *
_rpc_cvi_isp_setdisconfig_1 (rpc_cvi_isp_setdisconfig_1_argument *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_setdisconfig_1_svc(argp->ViPipe, argp->stAttrData, rqstp));
}

static RPC_ISP_GET_ATTR_DATA_S *
_rpc_cvi_isp_getdisconfig_1 (RPC_VI_PIPE  *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_getdisconfig_1_svc(*argp, rqstp));
}

static RPC_CVI_S32 *
_rpc_cvi_isp_getbinstatus_1 (RPC_VI_PIPE  *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_getbinstatus_1_svc(*argp, rqstp));
}

static RPC_CVI_S32 *
_rpc_cvi_isp_setvcattr_1 (rpc_cvi_isp_setvcattr_1_argument *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_setvcattr_1_svc(argp->ViPipe, argp->stAttrData, rqstp));
}

static RPC_ISP_GET_ATTR_DATA_S *
_rpc_cvi_isp_getvcattr_1 (RPC_VI_PIPE  *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_getvcattr_1_svc(*argp, rqstp));
}

static RPC_CVI_S32 *
_rpc_cvi_isp_dumphwregistertofile_1 (rpc_cvi_isp_dumphwregistertofile_1_argument *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_dumphwregistertofile_1_svc(argp->ViPipe, argp->fileName, rqstp));
}

static RPC_CVI_S32 *
_rpc_cvi_isp_dumpframerawinfotofile_1 (rpc_cvi_isp_dumpframerawinfotofile_1_argument *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_dumpframerawinfotofile_1_svc(argp->ViPipe, argp->fileName, rqstp));
}

static RPC_ISP_GET_ATTR_DATA_S *
_rpc_cvi_isp_irautorunonce_1 (rpc_cvi_isp_irautorunonce_1_argument *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_irautorunonce_1_svc(argp->IspDev, argp->stAttrData, rqstp));
}

static RPC_CVI_S32 *
_rpc_cvi_isp_setsmartinfo_1 (rpc_cvi_isp_setsmartinfo_1_argument *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_setsmartinfo_1_svc(argp->ViPipe, argp->stAttrData, argp->TimeOut, rqstp));
}

static RPC_ISP_GET_ATTR_DATA_S *
_rpc_cvi_isp_getsmartinfo_1 (RPC_VI_PIPE  *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_getsmartinfo_1_svc(*argp, rqstp));
}

static RPC_CVI_S32 *
_rpc_cvi_isp_settnrmotionadaptattr_1 (rpc_cvi_isp_settnrmotionadaptattr_1_argument *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_settnrmotionadaptattr_1_svc(argp->ViPipe, argp->stAttrData, rqstp));
}

static RPC_ISP_GET_ATTR_DATA_S *
_rpc_cvi_isp_gettnrmotionadaptattr_1 (RPC_VI_PIPE  *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_gettnrmotionadaptattr_1_svc(*argp, rqstp));
}

static RPC_CVI_S32 *
_rpc_cvi_isp_setclutsaturationattr_1 (rpc_cvi_isp_setclutsaturationattr_1_argument *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_setclutsaturationattr_1_svc(argp->ViPipe, argp->stAttrData, rqstp));
}

static RPC_ISP_GET_ATTR_DATA_S *
_rpc_cvi_isp_getclutsaturationattr_1 (RPC_VI_PIPE  *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_getclutsaturationattr_1_svc(*argp, rqstp));
}

static RPC_ISP_GET_ATTR_DATA_S *
_rpc_cvi_isp_getgammacurvebytype_1 (rpc_cvi_isp_getgammacurvebytype_1_argument *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_getgammacurvebytype_1_svc(argp->ViPipe, argp->curveType, rqstp));
}

static RPC_CVI_S32 *
_rpc_cvi_isp_setpresharpenattr_1 (rpc_cvi_isp_setpresharpenattr_1_argument *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_setpresharpenattr_1_svc(argp->ViPipe, argp->stAttrData, rqstp));
}

static RPC_ISP_GET_ATTR_DATA_S *
_rpc_cvi_isp_getpresharpenattr_1 (RPC_VI_PIPE  *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_getpresharpenattr_1_svc(*argp, rqstp));
}

static RPC_CVI_S32 *
_rpc_cvi_isp_setrgbcacattr_1 (rpc_cvi_isp_setrgbcacattr_1_argument *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_setrgbcacattr_1_svc(argp->ViPipe, argp->stAttrData, rqstp));
}

static RPC_ISP_GET_ATTR_DATA_S *
_rpc_cvi_isp_getrgbcacattr_1 (RPC_VI_PIPE  *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_getrgbcacattr_1_svc(*argp, rqstp));
}

static RPC_CVI_S32 *
_rpc_cvi_isp_setcnrmotionnrattr_1 (rpc_cvi_isp_setcnrmotionnrattr_1_argument *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_setcnrmotionnrattr_1_svc(argp->ViPipe, argp->stAttrData, rqstp));
}

static RPC_ISP_GET_ATTR_DATA_S *
_rpc_cvi_isp_getcnrmotionnrattr_1 (RPC_VI_PIPE  *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_getcnrmotionnrattr_1_svc(*argp, rqstp));
}

static RPC_CVI_S32 *
_rpc_cvi_isp_setccmsaturationattr_1 (rpc_cvi_isp_setccmsaturationattr_1_argument *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_setccmsaturationattr_1_svc(argp->ViPipe, argp->stAttrData, rqstp));
}

static RPC_ISP_GET_ATTR_DATA_S *
_rpc_cvi_isp_getccmsaturationattr_1 (RPC_VI_PIPE  *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_getccmsaturationattr_1_svc(*argp, rqstp));
}

static RPC_CVI_S32 *
_rpc_cvi_isp_setcaattr_1 (rpc_cvi_isp_setcaattr_1_argument *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_setcaattr_1_svc(argp->ViPipe, argp->stAttrData, rqstp));
}

static RPC_ISP_GET_ATTR_DATA_S *
_rpc_cvi_isp_getcaattr_1 (RPC_VI_PIPE  *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_getcaattr_1_svc(*argp, rqstp));
}

static RPC_CVI_S32 *
_rpc_cvi_isp_setcscattr_1 (rpc_cvi_isp_setcscattr_1_argument *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_setcscattr_1_svc(argp->ViPipe, argp->stAttrData, rqstp));
}

static RPC_ISP_GET_ATTR_DATA_S *
_rpc_cvi_isp_getcscattr_1 (RPC_VI_PIPE  *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_getcscattr_1_svc(*argp, rqstp));
}

static RPC_CVI_S32 *
_rpc_cvi_isp_setexposureattr_1 (rpc_cvi_isp_setexposureattr_1_argument *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_setexposureattr_1_svc(argp->ViPipe, argp->stAttrData, rqstp));
}

static RPC_ISP_GET_ATTR_DATA_S *
_rpc_cvi_isp_getexposureattr_1 (RPC_VI_PIPE  *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_getexposureattr_1_svc(*argp, rqstp));
}

static RPC_ISP_GET_ATTR_DATA_S *
_rpc_cvi_isp_queryexposureinfo_1 (RPC_VI_PIPE  *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_queryexposureinfo_1_svc(*argp, rqstp));
}

static RPC_CVI_S32 *
_rpc_cvi_isp_setwdrexposureattr_1 (rpc_cvi_isp_setwdrexposureattr_1_argument *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_setwdrexposureattr_1_svc(argp->ViPipe, argp->stAttrData, rqstp));
}

static RPC_ISP_GET_ATTR_DATA_S *
_rpc_cvi_isp_getwdrexposureattr_1 (RPC_VI_PIPE  *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_getwdrexposureattr_1_svc(*argp, rqstp));
}

static RPC_CVI_S32 *
_rpc_cvi_isp_setaerouteattr_1 (rpc_cvi_isp_setaerouteattr_1_argument *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_setaerouteattr_1_svc(argp->ViPipe, argp->stAttrData, rqstp));
}

static RPC_ISP_GET_ATTR_DATA_S *
_rpc_cvi_isp_getaerouteattr_1 (RPC_VI_PIPE  *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_getaerouteattr_1_svc(*argp, rqstp));
}

static RPC_CVI_S32 *
_rpc_cvi_isp_setaerouteattrex_1 (rpc_cvi_isp_setaerouteattrex_1_argument *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_setaerouteattrex_1_svc(argp->ViPipe, argp->stAttrData, rqstp));
}

static RPC_ISP_GET_ATTR_DATA_S *
_rpc_cvi_isp_getaerouteattrex_1 (RPC_VI_PIPE  *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_getaerouteattrex_1_svc(*argp, rqstp));
}

static RPC_CVI_S32 *
_rpc_cvi_isp_aebracketingstart_1 (RPC_VI_PIPE  *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_aebracketingstart_1_svc(*argp, rqstp));
}

static RPC_CVI_S32 *
_rpc_cvi_isp_aebracketingsetexpsoure_1 (rpc_cvi_isp_aebracketingsetexpsoure_1_argument *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_aebracketingsetexpsoure_1_svc(argp->ViPipe, argp->leEvX10, argp->seEvX10, rqstp));
}

static RPC_CVI_S32 *
_rpc_cvi_isp_aebracketingfinish_1 (RPC_VI_PIPE  *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_aebracketingfinish_1_svc(*argp, rqstp));
}

static RPC_CVI_S32 *
_rpc_cvi_isp_aebracketingsetsimple_1 (uint8_t  *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_aebracketingsetsimple_1_svc(*argp, rqstp));
}

static RPC_CVI_S32 *
_rpc_cvi_isp_setaestatisticsconfig_1 (rpc_cvi_isp_setaestatisticsconfig_1_argument *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_setaestatisticsconfig_1_svc(argp->ViPipe, argp->stAttrData, rqstp));
}

static RPC_ISP_GET_ATTR_DATA_S *
_rpc_cvi_isp_getaestatisticsconfig_1 (RPC_VI_PIPE  *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_getaestatisticsconfig_1_svc(*argp, rqstp));
}

static RPC_CVI_S32 *
_rpc_cvi_isp_setantiflicker_1 (rpc_cvi_isp_setantiflicker_1_argument *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_setantiflicker_1_svc(argp->ViPipe, argp->enable, argp->frequency, rqstp));
}

static uint32_t *
_rpc_cvi_isp_getantiflicker_1 (RPC_VI_PIPE  *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_getantiflicker_1_svc(*argp, rqstp));
}

static RPC_CVI_S32 *
_rpc_cvi_isp_setwdrleonly_1 (rpc_cvi_isp_setwdrleonly_1_argument *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_setwdrleonly_1_svc(argp->ViPipe, argp->wdrLEOnly, rqstp));
}

static uint32_t *
_rpc_cvi_isp_getframeid_1 (RPC_VI_PIPE  *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_getframeid_1_svc(*argp, rqstp));
}

static RPC_CVI_S32 *
_rpc_cvi_isp_setaelogpath_1 (char * *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_setaelogpath_1_svc(*argp, rqstp));
}

static RPC_ISP_GET_ATTR_DATA_S *
_rpc_cvi_isp_getaelogpath_1 (int  *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_getaelogpath_1_svc(*argp, rqstp));
}

static RPC_CVI_S32 *
_rpc_cvi_isp_setaelogname_1 (char * *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_setaelogname_1_svc(*argp, rqstp));
}

static RPC_ISP_GET_ATTR_DATA_S *
_rpc_cvi_isp_getaelogname_1 (int  *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_getaelogname_1_svc(*argp, rqstp));
}

static float *
_rpc_cvi_isp_queryfps_1 (RPC_VI_PIPE  *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_queryfps_1_svc(*argp, rqstp));
}

static RPC_ISP_GET_ATTR_DATA_S *
_rpc_cvi_isp_getaelogbuf_1 (RPC_VI_PIPE  *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_getaelogbuf_1_svc(*argp, rqstp));
}

static RPC_ISP_GET_ATTR_DATA_S *
_rpc_cvi_isp_getaelogbufsize_1 (RPC_VI_PIPE  *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_getaelogbufsize_1_svc(*argp, rqstp));
}

static RPC_ISP_GET_ATTR_DATA_S *
_rpc_cvi_isp_getaebinbuf_1 (RPC_VI_PIPE  *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_getaebinbuf_1_svc(*argp, rqstp));
}

static RPC_ISP_GET_ATTR_DATA_S *
_rpc_cvi_isp_getaebinbufsize_1 (RPC_VI_PIPE  *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_getaebinbufsize_1_svc(*argp, rqstp));
}

static RPC_ISP_GET_ATTR_DATA_S *
_rpc_cvi_isp_getcurrentlvx100_1 (RPC_VI_PIPE  *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_getcurrentlvx100_1_svc(*argp, rqstp));
}

static RPC_CVI_S32 *
_rpc_cvi_isp_setfastbootexposure_1 (rpc_cvi_isp_setfastbootexposure_1_argument *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_setfastbootexposure_1_svc(argp->ViPipe, argp->expLine, argp->again, argp->dgain, argp->ispdgain, rqstp));
}

static RPC_CVI_S32 *
_rpc_cvi_isp_setsmartexposureattr_1 (rpc_cvi_isp_setsmartexposureattr_1_argument *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_setsmartexposureattr_1_svc(argp->ViPipe, argp->stAttrData, rqstp));
}

static RPC_ISP_GET_ATTR_DATA_S *
_rpc_cvi_isp_getsmartexposureattr_1 (RPC_VI_PIPE  *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_getsmartexposureattr_1_svc(*argp, rqstp));
}

static RPC_CVI_S32 *
_rpc_cvi_isp_setwbattr_1 (rpc_cvi_isp_setwbattr_1_argument *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_setwbattr_1_svc(argp->ViPipe, argp->stAttrData, rqstp));
}

static RPC_ISP_GET_ATTR_DATA_S *
_rpc_cvi_isp_getwbattr_1 (RPC_VI_PIPE  *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_getwbattr_1_svc(*argp, rqstp));
}

static RPC_CVI_S32 *
_rpc_cvi_isp_setawbattrex_1 (rpc_cvi_isp_setawbattrex_1_argument *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_setawbattrex_1_svc(argp->ViPipe, argp->stAttrData, rqstp));
}

static RPC_ISP_GET_ATTR_DATA_S *
_rpc_cvi_isp_getawbattrex_1 (RPC_VI_PIPE  *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_getawbattrex_1_svc(*argp, rqstp));
}

static RPC_ISP_GET_ATTR_DATA_S *
_rpc_cvi_isp_querywbinfo_1 (RPC_VI_PIPE  *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_querywbinfo_1_svc(*argp, rqstp));
}

static RPC_CVI_S32 *
_rpc_cvi_isp_setwbcalibration_1 (rpc_cvi_isp_setwbcalibration_1_argument *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_setwbcalibration_1_svc(argp->ViPipe, argp->stAttrData, rqstp));
}

static RPC_ISP_GET_ATTR_DATA_S *
_rpc_cvi_isp_getwbcalibration_1 (RPC_VI_PIPE  *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_getwbcalibration_1_svc(*argp, rqstp));
}

static RPC_CVI_S32 *
_rpc_cvi_isp_setwbcalibrationex_1 (rpc_cvi_isp_setwbcalibrationex_1_argument *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_setwbcalibrationex_1_svc(argp->ViPipe, argp->stAttrData, rqstp));
}

static RPC_ISP_GET_ATTR_DATA_S *
_rpc_cvi_isp_getwbcalibrationex_1 (RPC_VI_PIPE  *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_getwbcalibrationex_1_svc(*argp, rqstp));
}

static RPC_CVI_S32 *
_rpc_cvi_isp_setawbwinstatictics_1 (rpc_cvi_isp_setawbwinstatictics_1_argument *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_setawbwinstatictics_1_svc(argp->ViPipe, argp->stAttrData, rqstp));
}

static RPC_ISP_GET_ATTR_DATA_S *
_rpc_cvi_isp_getawbwinstatictics_1 (RPC_VI_PIPE  *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_getawbwinstatictics_1_svc(*argp, rqstp));
}

static RPC_ISP_GET_ATTR_DATA_S *
_rpc_cvi_isp_getawbsnaplogbuf_1 (RPC_VI_PIPE  *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_getawbsnaplogbuf_1_svc(*argp, rqstp));
}

static RPC_ISP_GET_ATTR_DATA_S *
_rpc_cvi_isp_getawbdbgbinbuf_1 (RPC_VI_PIPE  *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_getawbdbgbinbuf_1_svc(*argp, rqstp));
}

static RPC_CVI_S32 *
_rpc_cvi_isp_getawbdbgbinsize_1 (void  *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_getawbdbgbinsize_1_svc(rqstp));
}

static RPC_ISP_GET_ATTR_DATA_S *
_rpc_cvi_isp_getawbcurve_1 (RPC_VI_PIPE  *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_getawbcurve_1_svc(*argp, rqstp));
}

static RPC_CVI_S32 *
_rpc_cvi_isp_setawblogpath_1 (char * *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_setawblogpath_1_svc(*argp, rqstp));
}

static RPC_CVI_S32 *
_rpc_cvi_isp_setawblogname_1 (char * *argp, struct svc_req *rqstp)
{
	return (rpc_cvi_isp_setawblogname_1_svc(*argp, rqstp));
}

static void
isp_rpc_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		rpc_cvi_isp_setpubattr_1_argument rpc_cvi_isp_setpubattr_1_arg;
		RPC_VI_PIPE rpc_cvi_isp_getpubattr_1_arg;
		RPC_ISP_SET_ATTR_DATA_S rpc_cvi_isp_setmodparam_1_arg;
		rpc_cvi_isp_setctrlparam_1_argument rpc_cvi_isp_setctrlparam_1_arg;
		RPC_VI_PIPE rpc_cvi_isp_getctrlparam_1_arg;
		rpc_cvi_isp_setfmwstate_1_argument rpc_cvi_isp_setfmwstate_1_arg;
		RPC_VI_PIPE rpc_cvi_isp_getfmwstate_1_arg;
		rpc_cvi_isp_setmodulecontrol_1_argument rpc_cvi_isp_setmodulecontrol_1_arg;
		RPC_VI_PIPE rpc_cvi_isp_getmodulecontrol_1_arg;
		rpc_cvi_isp_setregister_1_argument rpc_cvi_isp_setregister_1_arg;
		rpc_cvi_isp_getregister_1_argument rpc_cvi_isp_getregister_1_arg;
		rpc_cvi_isp_setcolortoneattr_1_argument rpc_cvi_isp_setcolortoneattr_1_arg;
		RPC_VI_PIPE rpc_cvi_isp_getcolortoneattr_1_arg;
		rpc_cvi_isp_setdehazeattr_1_argument rpc_cvi_isp_setdehazeattr_1_arg;
		RPC_VI_PIPE rpc_cvi_isp_getdehazeattr_1_arg;
		rpc_cvi_isp_setgammaattr_1_argument rpc_cvi_isp_setgammaattr_1_arg;
		RPC_VI_PIPE rpc_cvi_isp_getgammaattr_1_arg;
		rpc_cvi_isp_setgammacurvetype_1_argument rpc_cvi_isp_setgammacurvetype_1_arg;
		rpc_cvi_isp_setautogammaattr_1_argument rpc_cvi_isp_setautogammaattr_1_arg;
		RPC_VI_PIPE rpc_cvi_isp_getautogammaattr_1_arg;
		rpc_cvi_isp_setstatisticsconfig_1_argument rpc_cvi_isp_setstatisticsconfig_1_arg;
		RPC_VI_PIPE rpc_cvi_isp_getstatisticsconfig_1_arg;
		rpc_cvi_isp_setnrattr_1_argument rpc_cvi_isp_setnrattr_1_arg;
		RPC_VI_PIPE rpc_cvi_isp_getnrattr_1_arg;
		rpc_cvi_isp_setnrfilterattr_1_argument rpc_cvi_isp_setnrfilterattr_1_arg;
		RPC_VI_PIPE rpc_cvi_isp_getnrfilterattr_1_arg;
		rpc_cvi_isp_setrlscattr_1_argument rpc_cvi_isp_setrlscattr_1_arg;
		RPC_VI_PIPE rpc_cvi_isp_getrlscattr_1_arg;
		rpc_cvi_isp_setynrattr_1_argument rpc_cvi_isp_setynrattr_1_arg;
		RPC_VI_PIPE rpc_cvi_isp_getynrattr_1_arg;
		rpc_cvi_isp_setynrmotionnrattr_1_argument rpc_cvi_isp_setynrmotionnrattr_1_arg;
		RPC_VI_PIPE rpc_cvi_isp_getynrmotionnrattr_1_arg;
		rpc_cvi_isp_setynrfilterattr_1_argument rpc_cvi_isp_setynrfilterattr_1_arg;
		RPC_VI_PIPE rpc_cvi_isp_getynrfilterattr_1_arg;
		rpc_cvi_isp_setcnrattr_1_argument rpc_cvi_isp_setcnrattr_1_arg;
		RPC_VI_PIPE rpc_cvi_isp_getcnrattr_1_arg;
		rpc_cvi_isp_setcacattr_1_argument rpc_cvi_isp_setcacattr_1_arg;
		RPC_VI_PIPE rpc_cvi_isp_getcacattr_1_arg;
		rpc_cvi_isp_setdciattr_1_argument rpc_cvi_isp_setdciattr_1_arg;
		RPC_VI_PIPE rpc_cvi_isp_getdciattr_1_arg;
		rpc_cvi_isp_setmeshshadingattr_1_argument rpc_cvi_isp_setmeshshadingattr_1_arg;
		RPC_VI_PIPE rpc_cvi_isp_getmeshshadingattr_1_arg;
		rpc_cvi_isp_setmeshshadinggainlutattr_1_argument rpc_cvi_isp_setmeshshadinggainlutattr_1_arg;
		RPC_VI_PIPE rpc_cvi_isp_getmeshshadinggainlutattr_1_arg;
		rpc_cvi_isp_setradialshadingattr_1_argument rpc_cvi_isp_setradialshadingattr_1_arg;
		RPC_VI_PIPE rpc_cvi_isp_getradialshadingattr_1_arg;
		rpc_cvi_isp_setradialshadinggainlutattr_1_argument rpc_cvi_isp_setradialshadinggainlutattr_1_arg;
		RPC_VI_PIPE rpc_cvi_isp_getradialshadinggainlutattr_1_arg;
		rpc_cvi_isp_settnrattr_1_argument rpc_cvi_isp_settnrattr_1_arg;
		RPC_VI_PIPE rpc_cvi_isp_gettnrattr_1_arg;
		rpc_cvi_isp_settnrnoisemodelattr_1_argument rpc_cvi_isp_settnrnoisemodelattr_1_arg;
		RPC_VI_PIPE rpc_cvi_isp_gettnrnoisemodelattr_1_arg;
		rpc_cvi_isp_settnrlumamotionattr_1_argument rpc_cvi_isp_settnrlumamotionattr_1_arg;
		RPC_VI_PIPE rpc_cvi_isp_gettnrlumamotionattr_1_arg;
		rpc_cvi_isp_settnrghostattr_1_argument rpc_cvi_isp_settnrghostattr_1_arg;
		RPC_VI_PIPE rpc_cvi_isp_gettnrghostattr_1_arg;
		rpc_cvi_isp_settnrmtprtattr_1_argument rpc_cvi_isp_settnrmtprtattr_1_arg;
		RPC_VI_PIPE rpc_cvi_isp_gettnrmtprtattr_1_arg;
		rpc_cvi_isp_setclutattr_1_argument rpc_cvi_isp_setclutattr_1_arg;
		RPC_VI_PIPE rpc_cvi_isp_getclutattr_1_arg;
		rpc_cvi_isp_setclutcoeff_1_argument rpc_cvi_isp_setclutcoeff_1_arg;
		RPC_VI_PIPE rpc_cvi_isp_getclutcoeff_1_arg;
		rpc_cvi_isp_setblacklevelattr_1_argument rpc_cvi_isp_setblacklevelattr_1_arg;
		RPC_VI_PIPE rpc_cvi_isp_getblacklevelattr_1_arg;
		rpc_cvi_isp_setdemosaicattr_1_argument rpc_cvi_isp_setdemosaicattr_1_arg;
		RPC_VI_PIPE rpc_cvi_isp_getdemosaicattr_1_arg;
		rpc_cvi_isp_setdemosaicdemoireattr_1_argument rpc_cvi_isp_setdemosaicdemoireattr_1_arg;
		RPC_VI_PIPE rpc_cvi_isp_getdemosaicdemoireattr_1_arg;
		rpc_cvi_isp_setdemosaicfilterattr_1_argument rpc_cvi_isp_setdemosaicfilterattr_1_arg;
		RPC_VI_PIPE rpc_cvi_isp_getdemosaicfilterattr_1_arg;
		rpc_cvi_isp_setdemosaiceeattr_1_argument rpc_cvi_isp_setdemosaiceeattr_1_arg;
		RPC_VI_PIPE rpc_cvi_isp_getdemosaiceeattr_1_arg;
		rpc_cvi_isp_setsaturationattr_1_argument rpc_cvi_isp_setsaturationattr_1_arg;
		RPC_VI_PIPE rpc_cvi_isp_getsaturationattr_1_arg;
		rpc_cvi_isp_setccmattr_1_argument rpc_cvi_isp_setccmattr_1_arg;
		RPC_VI_PIPE rpc_cvi_isp_getccmattr_1_arg;
		rpc_cvi_isp_sethsvattr_1_argument rpc_cvi_isp_sethsvattr_1_arg;
		RPC_VI_PIPE rpc_cvi_isp_gethsvattr_1_arg;
		rpc_cvi_isp_setdpdynamicattr_1_argument rpc_cvi_isp_setdpdynamicattr_1_arg;
		RPC_VI_PIPE rpc_cvi_isp_getdpdynamicattr_1_arg;
		rpc_cvi_isp_setdpstaticattr_1_argument rpc_cvi_isp_setdpstaticattr_1_arg;
		RPC_VI_PIPE rpc_cvi_isp_getdpstaticattr_1_arg;
		rpc_cvi_isp_setdpcalibrate_1_argument rpc_cvi_isp_setdpcalibrate_1_arg;
		RPC_VI_PIPE rpc_cvi_isp_getdpcalibrate_1_arg;
		rpc_cvi_isp_setcrosstalkattr_1_argument rpc_cvi_isp_setcrosstalkattr_1_arg;
		RPC_VI_PIPE rpc_cvi_isp_getcrosstalkattr_1_arg;
		RPC_VI_PIPE rpc_cvi_isp_getaestatistics_1_arg;
		RPC_VI_PIPE rpc_cvi_isp_getwbstatistics_1_arg;
		RPC_VI_PIPE rpc_cvi_isp_getfocusstatistics_1_arg;
		RPC_VI_PIPE rpc_cvi_isp_getlightboxgain_1_arg;
		rpc_cvi_isp_setfswdrattr_1_argument rpc_cvi_isp_setfswdrattr_1_arg;
		RPC_VI_PIPE rpc_cvi_isp_getfswdrattr_1_arg;
		rpc_cvi_isp_setdrcattr_1_argument rpc_cvi_isp_setdrcattr_1_arg;
		RPC_VI_PIPE rpc_cvi_isp_getdrcattr_1_arg;
		rpc_cvi_isp_setsharpenattr_1_argument rpc_cvi_isp_setsharpenattr_1_arg;
		RPC_VI_PIPE rpc_cvi_isp_getsharpenattr_1_arg;
		rpc_cvi_isp_setnoiseprofileattr_1_argument rpc_cvi_isp_setnoiseprofileattr_1_arg;
		RPC_VI_PIPE rpc_cvi_isp_getnoiseprofileattr_1_arg;
		rpc_cvi_isp_setycontrastattr_1_argument rpc_cvi_isp_setycontrastattr_1_arg;
		RPC_VI_PIPE rpc_cvi_isp_getycontrastattr_1_arg;
		rpc_cvi_isp_setdcfinfo_1_argument rpc_cvi_isp_setdcfinfo_1_arg;
		RPC_VI_PIPE rpc_cvi_isp_getdcfinfo_1_arg;
		RPC_VI_PIPE rpc_cvi_isp_queryinnerstateinfo_1_arg;
		rpc_cvi_isp_getvdtimeout_1_argument rpc_cvi_isp_getvdtimeout_1_arg;
		rpc_cvi_isp_setmonoattr_1_argument rpc_cvi_isp_setmonoattr_1_arg;
		RPC_VI_PIPE rpc_cvi_isp_getmonoattr_1_arg;
		rpc_cvi_isp_setdisattr_1_argument rpc_cvi_isp_setdisattr_1_arg;
		RPC_VI_PIPE rpc_cvi_isp_getdisattr_1_arg;
		rpc_cvi_isp_setdisconfig_1_argument rpc_cvi_isp_setdisconfig_1_arg;
		RPC_VI_PIPE rpc_cvi_isp_getdisconfig_1_arg;
		RPC_VI_PIPE rpc_cvi_isp_getbinstatus_1_arg;
		rpc_cvi_isp_setvcattr_1_argument rpc_cvi_isp_setvcattr_1_arg;
		RPC_VI_PIPE rpc_cvi_isp_getvcattr_1_arg;
		rpc_cvi_isp_dumphwregistertofile_1_argument rpc_cvi_isp_dumphwregistertofile_1_arg;
		rpc_cvi_isp_dumpframerawinfotofile_1_argument rpc_cvi_isp_dumpframerawinfotofile_1_arg;
		rpc_cvi_isp_irautorunonce_1_argument rpc_cvi_isp_irautorunonce_1_arg;
		rpc_cvi_isp_setsmartinfo_1_argument rpc_cvi_isp_setsmartinfo_1_arg;
		RPC_VI_PIPE rpc_cvi_isp_getsmartinfo_1_arg;
		rpc_cvi_isp_settnrmotionadaptattr_1_argument rpc_cvi_isp_settnrmotionadaptattr_1_arg;
		RPC_VI_PIPE rpc_cvi_isp_gettnrmotionadaptattr_1_arg;
		rpc_cvi_isp_setclutsaturationattr_1_argument rpc_cvi_isp_setclutsaturationattr_1_arg;
		RPC_VI_PIPE rpc_cvi_isp_getclutsaturationattr_1_arg;
		rpc_cvi_isp_getgammacurvebytype_1_argument rpc_cvi_isp_getgammacurvebytype_1_arg;
		rpc_cvi_isp_setpresharpenattr_1_argument rpc_cvi_isp_setpresharpenattr_1_arg;
		RPC_VI_PIPE rpc_cvi_isp_getpresharpenattr_1_arg;
		rpc_cvi_isp_setrgbcacattr_1_argument rpc_cvi_isp_setrgbcacattr_1_arg;
		RPC_VI_PIPE rpc_cvi_isp_getrgbcacattr_1_arg;
		rpc_cvi_isp_setcnrmotionnrattr_1_argument rpc_cvi_isp_setcnrmotionnrattr_1_arg;
		RPC_VI_PIPE rpc_cvi_isp_getcnrmotionnrattr_1_arg;
		rpc_cvi_isp_setccmsaturationattr_1_argument rpc_cvi_isp_setccmsaturationattr_1_arg;
		RPC_VI_PIPE rpc_cvi_isp_getccmsaturationattr_1_arg;
		rpc_cvi_isp_setcaattr_1_argument rpc_cvi_isp_setcaattr_1_arg;
		RPC_VI_PIPE rpc_cvi_isp_getcaattr_1_arg;
		rpc_cvi_isp_setcscattr_1_argument rpc_cvi_isp_setcscattr_1_arg;
		RPC_VI_PIPE rpc_cvi_isp_getcscattr_1_arg;
		rpc_cvi_isp_setexposureattr_1_argument rpc_cvi_isp_setexposureattr_1_arg;
		RPC_VI_PIPE rpc_cvi_isp_getexposureattr_1_arg;
		RPC_VI_PIPE rpc_cvi_isp_queryexposureinfo_1_arg;
		rpc_cvi_isp_setwdrexposureattr_1_argument rpc_cvi_isp_setwdrexposureattr_1_arg;
		RPC_VI_PIPE rpc_cvi_isp_getwdrexposureattr_1_arg;
		rpc_cvi_isp_setaerouteattr_1_argument rpc_cvi_isp_setaerouteattr_1_arg;
		RPC_VI_PIPE rpc_cvi_isp_getaerouteattr_1_arg;
		rpc_cvi_isp_setaerouteattrex_1_argument rpc_cvi_isp_setaerouteattrex_1_arg;
		RPC_VI_PIPE rpc_cvi_isp_getaerouteattrex_1_arg;
		RPC_VI_PIPE rpc_cvi_isp_aebracketingstart_1_arg;
		rpc_cvi_isp_aebracketingsetexpsoure_1_argument rpc_cvi_isp_aebracketingsetexpsoure_1_arg;
		RPC_VI_PIPE rpc_cvi_isp_aebracketingfinish_1_arg;
		uint8_t rpc_cvi_isp_aebracketingsetsimple_1_arg;
		rpc_cvi_isp_setaestatisticsconfig_1_argument rpc_cvi_isp_setaestatisticsconfig_1_arg;
		RPC_VI_PIPE rpc_cvi_isp_getaestatisticsconfig_1_arg;
		rpc_cvi_isp_setantiflicker_1_argument rpc_cvi_isp_setantiflicker_1_arg;
		RPC_VI_PIPE rpc_cvi_isp_getantiflicker_1_arg;
		rpc_cvi_isp_setwdrleonly_1_argument rpc_cvi_isp_setwdrleonly_1_arg;
		RPC_VI_PIPE rpc_cvi_isp_getframeid_1_arg;
		char *rpc_cvi_isp_setaelogpath_1_arg;
		int rpc_cvi_isp_getaelogpath_1_arg;
		char *rpc_cvi_isp_setaelogname_1_arg;
		int rpc_cvi_isp_getaelogname_1_arg;
		RPC_VI_PIPE rpc_cvi_isp_queryfps_1_arg;
		RPC_VI_PIPE rpc_cvi_isp_getaelogbuf_1_arg;
		RPC_VI_PIPE rpc_cvi_isp_getaelogbufsize_1_arg;
		RPC_VI_PIPE rpc_cvi_isp_getaebinbuf_1_arg;
		RPC_VI_PIPE rpc_cvi_isp_getaebinbufsize_1_arg;
		RPC_VI_PIPE rpc_cvi_isp_getcurrentlvx100_1_arg;
		rpc_cvi_isp_setfastbootexposure_1_argument rpc_cvi_isp_setfastbootexposure_1_arg;
		rpc_cvi_isp_setsmartexposureattr_1_argument rpc_cvi_isp_setsmartexposureattr_1_arg;
		RPC_VI_PIPE rpc_cvi_isp_getsmartexposureattr_1_arg;
		rpc_cvi_isp_setwbattr_1_argument rpc_cvi_isp_setwbattr_1_arg;
		RPC_VI_PIPE rpc_cvi_isp_getwbattr_1_arg;
		rpc_cvi_isp_setawbattrex_1_argument rpc_cvi_isp_setawbattrex_1_arg;
		RPC_VI_PIPE rpc_cvi_isp_getawbattrex_1_arg;
		RPC_VI_PIPE rpc_cvi_isp_querywbinfo_1_arg;
		rpc_cvi_isp_setwbcalibration_1_argument rpc_cvi_isp_setwbcalibration_1_arg;
		RPC_VI_PIPE rpc_cvi_isp_getwbcalibration_1_arg;
		rpc_cvi_isp_setwbcalibrationex_1_argument rpc_cvi_isp_setwbcalibrationex_1_arg;
		RPC_VI_PIPE rpc_cvi_isp_getwbcalibrationex_1_arg;
		rpc_cvi_isp_setawbwinstatictics_1_argument rpc_cvi_isp_setawbwinstatictics_1_arg;
		RPC_VI_PIPE rpc_cvi_isp_getawbwinstatictics_1_arg;
		RPC_VI_PIPE rpc_cvi_isp_getawbsnaplogbuf_1_arg;
		RPC_VI_PIPE rpc_cvi_isp_getawbdbgbinbuf_1_arg;
		RPC_VI_PIPE rpc_cvi_isp_getawbcurve_1_arg;
		char *rpc_cvi_isp_setawblogpath_1_arg;
		char *rpc_cvi_isp_setawblogname_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case RPC_CVI_ISP_SetPubAttr:
		_xdr_argument = (xdrproc_t) xdr_rpc_cvi_isp_setpubattr_1_argument;
		_xdr_result = (xdrproc_t) xdr_RPC_CVI_S32;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_setpubattr_1;
		break;

	case RPC_CVI_ISP_GetPubAttr:
		_xdr_argument = (xdrproc_t) xdr_RPC_VI_PIPE;
		_xdr_result = (xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_getpubattr_1;
		break;

	case RPC_CVI_ISP_SetModParam:
		_xdr_argument = (xdrproc_t) xdr_RPC_ISP_SET_ATTR_DATA_S;
		_xdr_result = (xdrproc_t) xdr_RPC_CVI_S32;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_setmodparam_1;
		break;

	case RPC_CVI_ISP_GetModParam:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_getmodparam_1;
		break;

	case RPC_CVI_ISP_SetCtrlParam:
		_xdr_argument = (xdrproc_t) xdr_rpc_cvi_isp_setctrlparam_1_argument;
		_xdr_result = (xdrproc_t) xdr_RPC_CVI_S32;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_setctrlparam_1;
		break;

	case RPC_CVI_ISP_GetCtrlParam:
		_xdr_argument = (xdrproc_t) xdr_RPC_VI_PIPE;
		_xdr_result = (xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_getctrlparam_1;
		break;

	case RPC_CVI_ISP_SetFMWState:
		_xdr_argument = (xdrproc_t) xdr_rpc_cvi_isp_setfmwstate_1_argument;
		_xdr_result = (xdrproc_t) xdr_RPC_CVI_S32;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_setfmwstate_1;
		break;

	case RPC_CVI_ISP_GetFMWState:
		_xdr_argument = (xdrproc_t) xdr_RPC_VI_PIPE;
		_xdr_result = (xdrproc_t) xdr_uint32_t;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_getfmwstate_1;
		break;

	case RPC_CVI_ISP_SetModuleControl:
		_xdr_argument = (xdrproc_t) xdr_rpc_cvi_isp_setmodulecontrol_1_argument;
		_xdr_result = (xdrproc_t) xdr_RPC_CVI_S32;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_setmodulecontrol_1;
		break;

	case RPC_CVI_ISP_GetModuleControl:
		_xdr_argument = (xdrproc_t) xdr_RPC_VI_PIPE;
		_xdr_result = (xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_getmodulecontrol_1;
		break;

	case RPC_CVI_ISP_SetRegister:
		_xdr_argument = (xdrproc_t) xdr_rpc_cvi_isp_setregister_1_argument;
		_xdr_result = (xdrproc_t) xdr_RPC_CVI_S32;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_setregister_1;
		break;

	case RPC_CVI_ISP_GetRegister:
		_xdr_argument = (xdrproc_t) xdr_rpc_cvi_isp_getregister_1_argument;
		_xdr_result = (xdrproc_t) xdr_uint32_t;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_getregister_1;
		break;

	case RPC_CVI_ISP_SetColorToneAttr:
		_xdr_argument = (xdrproc_t) xdr_rpc_cvi_isp_setcolortoneattr_1_argument;
		_xdr_result = (xdrproc_t) xdr_RPC_CVI_S32;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_setcolortoneattr_1;
		break;

	case RPC_CVI_ISP_GetColorToneAttr:
		_xdr_argument = (xdrproc_t) xdr_RPC_VI_PIPE;
		_xdr_result = (xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_getcolortoneattr_1;
		break;

	case RPC_CVI_ISP_SetDehazeAttr:
		_xdr_argument = (xdrproc_t) xdr_rpc_cvi_isp_setdehazeattr_1_argument;
		_xdr_result = (xdrproc_t) xdr_RPC_CVI_S32;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_setdehazeattr_1;
		break;

	case RPC_CVI_ISP_GetDehazeAttr:
		_xdr_argument = (xdrproc_t) xdr_RPC_VI_PIPE;
		_xdr_result = (xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_getdehazeattr_1;
		break;

	case RPC_CVI_ISP_SetGammaAttr:
		_xdr_argument = (xdrproc_t) xdr_rpc_cvi_isp_setgammaattr_1_argument;
		_xdr_result = (xdrproc_t) xdr_RPC_CVI_S32;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_setgammaattr_1;
		break;

	case RPC_CVI_ISP_GetGammaAttr:
		_xdr_argument = (xdrproc_t) xdr_RPC_VI_PIPE;
		_xdr_result = (xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_getgammaattr_1;
		break;

	case RPC_CVI_ISP_SetGammaCurveType:
		_xdr_argument = (xdrproc_t) xdr_rpc_cvi_isp_setgammacurvetype_1_argument;
		_xdr_result = (xdrproc_t) xdr_RPC_CVI_S32;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_setgammacurvetype_1;
		break;

	case RPC_CVI_ISP_SetAutoGammaAttr:
		_xdr_argument = (xdrproc_t) xdr_rpc_cvi_isp_setautogammaattr_1_argument;
		_xdr_result = (xdrproc_t) xdr_RPC_CVI_S32;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_setautogammaattr_1;
		break;

	case RPC_CVI_ISP_GetAutoGammaAttr:
		_xdr_argument = (xdrproc_t) xdr_RPC_VI_PIPE;
		_xdr_result = (xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_getautogammaattr_1;
		break;

	case RPC_CVI_ISP_SetStatisticsConfig:
		_xdr_argument = (xdrproc_t) xdr_rpc_cvi_isp_setstatisticsconfig_1_argument;
		_xdr_result = (xdrproc_t) xdr_RPC_CVI_S32;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_setstatisticsconfig_1;
		break;

	case RPC_CVI_ISP_GetStatisticsConfig:
		_xdr_argument = (xdrproc_t) xdr_RPC_VI_PIPE;
		_xdr_result = (xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_getstatisticsconfig_1;
		break;

	case RPC_CVI_ISP_SetNRAttr:
		_xdr_argument = (xdrproc_t) xdr_rpc_cvi_isp_setnrattr_1_argument;
		_xdr_result = (xdrproc_t) xdr_RPC_CVI_S32;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_setnrattr_1;
		break;

	case RPC_CVI_ISP_GetNRAttr:
		_xdr_argument = (xdrproc_t) xdr_RPC_VI_PIPE;
		_xdr_result = (xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_getnrattr_1;
		break;

	case RPC_CVI_ISP_SetNRFilterAttr:
		_xdr_argument = (xdrproc_t) xdr_rpc_cvi_isp_setnrfilterattr_1_argument;
		_xdr_result = (xdrproc_t) xdr_RPC_CVI_S32;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_setnrfilterattr_1;
		break;

	case RPC_CVI_ISP_GetNRFilterAttr:
		_xdr_argument = (xdrproc_t) xdr_RPC_VI_PIPE;
		_xdr_result = (xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_getnrfilterattr_1;
		break;

	case RPC_CVI_ISP_SetRLSCAttr:
		_xdr_argument = (xdrproc_t) xdr_rpc_cvi_isp_setrlscattr_1_argument;
		_xdr_result = (xdrproc_t) xdr_RPC_CVI_S32;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_setrlscattr_1;
		break;

	case RPC_CVI_ISP_GetRLSCAttr:
		_xdr_argument = (xdrproc_t) xdr_RPC_VI_PIPE;
		_xdr_result = (xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_getrlscattr_1;
		break;

	case RPC_CVI_ISP_SetYNRAttr:
		_xdr_argument = (xdrproc_t) xdr_rpc_cvi_isp_setynrattr_1_argument;
		_xdr_result = (xdrproc_t) xdr_RPC_CVI_S32;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_setynrattr_1;
		break;

	case RPC_CVI_ISP_GetYNRAttr:
		_xdr_argument = (xdrproc_t) xdr_RPC_VI_PIPE;
		_xdr_result = (xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_getynrattr_1;
		break;

	case RPC_CVI_ISP_SetYNRMotionNRAttr:
		_xdr_argument = (xdrproc_t) xdr_rpc_cvi_isp_setynrmotionnrattr_1_argument;
		_xdr_result = (xdrproc_t) xdr_RPC_CVI_S32;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_setynrmotionnrattr_1;
		break;

	case RPC_CVI_ISP_GetYNRMotionNRAttr:
		_xdr_argument = (xdrproc_t) xdr_RPC_VI_PIPE;
		_xdr_result = (xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_getynrmotionnrattr_1;
		break;

	case RPC_CVI_ISP_SetYNRFilterAttr:
		_xdr_argument = (xdrproc_t) xdr_rpc_cvi_isp_setynrfilterattr_1_argument;
		_xdr_result = (xdrproc_t) xdr_RPC_CVI_S32;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_setynrfilterattr_1;
		break;

	case RPC_CVI_ISP_GetYNRFilterAttr:
		_xdr_argument = (xdrproc_t) xdr_RPC_VI_PIPE;
		_xdr_result = (xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_getynrfilterattr_1;
		break;

	case RPC_CVI_ISP_SetCNRAttr:
		_xdr_argument = (xdrproc_t) xdr_rpc_cvi_isp_setcnrattr_1_argument;
		_xdr_result = (xdrproc_t) xdr_RPC_CVI_S32;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_setcnrattr_1;
		break;

	case RPC_CVI_ISP_GetCNRAttr:
		_xdr_argument = (xdrproc_t) xdr_RPC_VI_PIPE;
		_xdr_result = (xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_getcnrattr_1;
		break;

	case RPC_CVI_ISP_SetCACAttr:
		_xdr_argument = (xdrproc_t) xdr_rpc_cvi_isp_setcacattr_1_argument;
		_xdr_result = (xdrproc_t) xdr_RPC_CVI_S32;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_setcacattr_1;
		break;

	case RPC_CVI_ISP_GetCACAttr:
		_xdr_argument = (xdrproc_t) xdr_RPC_VI_PIPE;
		_xdr_result = (xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_getcacattr_1;
		break;

	case RPC_CVI_ISP_SetDCIAttr:
		_xdr_argument = (xdrproc_t) xdr_rpc_cvi_isp_setdciattr_1_argument;
		_xdr_result = (xdrproc_t) xdr_RPC_CVI_S32;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_setdciattr_1;
		break;

	case RPC_CVI_ISP_GetDCIAttr:
		_xdr_argument = (xdrproc_t) xdr_RPC_VI_PIPE;
		_xdr_result = (xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_getdciattr_1;
		break;

	case RPC_CVI_ISP_SetMeshShadingAttr:
		_xdr_argument = (xdrproc_t) xdr_rpc_cvi_isp_setmeshshadingattr_1_argument;
		_xdr_result = (xdrproc_t) xdr_RPC_CVI_S32;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_setmeshshadingattr_1;
		break;

	case RPC_CVI_ISP_GetMeshShadingAttr:
		_xdr_argument = (xdrproc_t) xdr_RPC_VI_PIPE;
		_xdr_result = (xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_getmeshshadingattr_1;
		break;

	case RPC_CVI_ISP_SetMeshShadingGainLutAttr:
		_xdr_argument = (xdrproc_t) xdr_rpc_cvi_isp_setmeshshadinggainlutattr_1_argument;
		_xdr_result = (xdrproc_t) xdr_RPC_CVI_S32;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_setmeshshadinggainlutattr_1;
		break;

	case RPC_CVI_ISP_GetMeshShadingGainLutAttr:
		_xdr_argument = (xdrproc_t) xdr_RPC_VI_PIPE;
		_xdr_result = (xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_getmeshshadinggainlutattr_1;
		break;

	case RPC_CVI_ISP_SetRadialShadingAttr:
		_xdr_argument = (xdrproc_t) xdr_rpc_cvi_isp_setradialshadingattr_1_argument;
		_xdr_result = (xdrproc_t) xdr_RPC_CVI_S32;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_setradialshadingattr_1;
		break;

	case RPC_CVI_ISP_GetRadialShadingAttr:
		_xdr_argument = (xdrproc_t) xdr_RPC_VI_PIPE;
		_xdr_result = (xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_getradialshadingattr_1;
		break;

	case RPC_CVI_ISP_SetRadialShadingGainLutAttr:
		_xdr_argument = (xdrproc_t) xdr_rpc_cvi_isp_setradialshadinggainlutattr_1_argument;
		_xdr_result = (xdrproc_t) xdr_RPC_CVI_S32;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_setradialshadinggainlutattr_1;
		break;

	case RPC_CVI_ISP_GetRadialShadingGainLutAttr:
		_xdr_argument = (xdrproc_t) xdr_RPC_VI_PIPE;
		_xdr_result = (xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_getradialshadinggainlutattr_1;
		break;

	case RPC_CVI_ISP_SetTNRAttr:
		_xdr_argument = (xdrproc_t) xdr_rpc_cvi_isp_settnrattr_1_argument;
		_xdr_result = (xdrproc_t) xdr_RPC_CVI_S32;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_settnrattr_1;
		break;

	case RPC_CVI_ISP_GetTNRAttr:
		_xdr_argument = (xdrproc_t) xdr_RPC_VI_PIPE;
		_xdr_result = (xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_gettnrattr_1;
		break;

	case RPC_CVI_ISP_SetTNRNoiseModelAttr:
		_xdr_argument = (xdrproc_t) xdr_rpc_cvi_isp_settnrnoisemodelattr_1_argument;
		_xdr_result = (xdrproc_t) xdr_RPC_CVI_S32;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_settnrnoisemodelattr_1;
		break;

	case RPC_CVI_ISP_GetTNRNoiseModelAttr:
		_xdr_argument = (xdrproc_t) xdr_RPC_VI_PIPE;
		_xdr_result = (xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_gettnrnoisemodelattr_1;
		break;

	case RPC_CVI_ISP_SetTNRLumaMotionAttr:
		_xdr_argument = (xdrproc_t) xdr_rpc_cvi_isp_settnrlumamotionattr_1_argument;
		_xdr_result = (xdrproc_t) xdr_RPC_CVI_S32;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_settnrlumamotionattr_1;
		break;

	case RPC_CVI_ISP_GetTNRLumaMotionAttr:
		_xdr_argument = (xdrproc_t) xdr_RPC_VI_PIPE;
		_xdr_result = (xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_gettnrlumamotionattr_1;
		break;

	case RPC_CVI_ISP_SetTNRGhostAttr:
		_xdr_argument = (xdrproc_t) xdr_rpc_cvi_isp_settnrghostattr_1_argument;
		_xdr_result = (xdrproc_t) xdr_RPC_CVI_S32;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_settnrghostattr_1;
		break;

	case RPC_CVI_ISP_GetTNRGhostAttr:
		_xdr_argument = (xdrproc_t) xdr_RPC_VI_PIPE;
		_xdr_result = (xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_gettnrghostattr_1;
		break;

	case RPC_CVI_ISP_SetTNRMtPrtAttr:
		_xdr_argument = (xdrproc_t) xdr_rpc_cvi_isp_settnrmtprtattr_1_argument;
		_xdr_result = (xdrproc_t) xdr_RPC_CVI_S32;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_settnrmtprtattr_1;
		break;

	case RPC_CVI_ISP_GetTNRMtPrtAttr:
		_xdr_argument = (xdrproc_t) xdr_RPC_VI_PIPE;
		_xdr_result = (xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_gettnrmtprtattr_1;
		break;

	case RPC_CVI_ISP_SetCLutAttr:
		_xdr_argument = (xdrproc_t) xdr_rpc_cvi_isp_setclutattr_1_argument;
		_xdr_result = (xdrproc_t) xdr_RPC_CVI_S32;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_setclutattr_1;
		break;

	case RPC_CVI_ISP_GetCLutAttr:
		_xdr_argument = (xdrproc_t) xdr_RPC_VI_PIPE;
		_xdr_result = (xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_getclutattr_1;
		break;

	case RPC_CVI_ISP_SetCLutCoeff:
		_xdr_argument = (xdrproc_t) xdr_rpc_cvi_isp_setclutcoeff_1_argument;
		_xdr_result = (xdrproc_t) xdr_RPC_CVI_S32;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_setclutcoeff_1;
		break;

	case RPC_CVI_ISP_GetCLutCoeff:
		_xdr_argument = (xdrproc_t) xdr_RPC_VI_PIPE;
		_xdr_result = (xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_getclutcoeff_1;
		break;

	case RPC_CVI_ISP_SetBlackLevelAttr:
		_xdr_argument = (xdrproc_t) xdr_rpc_cvi_isp_setblacklevelattr_1_argument;
		_xdr_result = (xdrproc_t) xdr_RPC_CVI_S32;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_setblacklevelattr_1;
		break;

	case RPC_CVI_ISP_GetBlackLevelAttr:
		_xdr_argument = (xdrproc_t) xdr_RPC_VI_PIPE;
		_xdr_result = (xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_getblacklevelattr_1;
		break;

	case RPC_CVI_ISP_SetDemosaicAttr:
		_xdr_argument = (xdrproc_t) xdr_rpc_cvi_isp_setdemosaicattr_1_argument;
		_xdr_result = (xdrproc_t) xdr_RPC_CVI_S32;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_setdemosaicattr_1;
		break;

	case RPC_CVI_ISP_GetDemosaicAttr:
		_xdr_argument = (xdrproc_t) xdr_RPC_VI_PIPE;
		_xdr_result = (xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_getdemosaicattr_1;
		break;

	case RPC_CVI_ISP_SetDemosaicDemoireAttr:
		_xdr_argument = (xdrproc_t) xdr_rpc_cvi_isp_setdemosaicdemoireattr_1_argument;
		_xdr_result = (xdrproc_t) xdr_RPC_CVI_S32;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_setdemosaicdemoireattr_1;
		break;

	case RPC_CVI_ISP_GetDemosaicDemoireAttr:
		_xdr_argument = (xdrproc_t) xdr_RPC_VI_PIPE;
		_xdr_result = (xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_getdemosaicdemoireattr_1;
		break;

	case RPC_CVI_ISP_SetDemosaicFilterAttr:
		_xdr_argument = (xdrproc_t) xdr_rpc_cvi_isp_setdemosaicfilterattr_1_argument;
		_xdr_result = (xdrproc_t) xdr_RPC_CVI_S32;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_setdemosaicfilterattr_1;
		break;

	case RPC_CVI_ISP_GetDemosaicFilterAttr:
		_xdr_argument = (xdrproc_t) xdr_RPC_VI_PIPE;
		_xdr_result = (xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_getdemosaicfilterattr_1;
		break;

	case RPC_CVI_ISP_SetDemosaicEEAttr:
		_xdr_argument = (xdrproc_t) xdr_rpc_cvi_isp_setdemosaiceeattr_1_argument;
		_xdr_result = (xdrproc_t) xdr_RPC_CVI_S32;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_setdemosaiceeattr_1;
		break;

	case RPC_CVI_ISP_GetDemosaicEEAttr:
		_xdr_argument = (xdrproc_t) xdr_RPC_VI_PIPE;
		_xdr_result = (xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_getdemosaiceeattr_1;
		break;

	case RPC_CVI_ISP_SetSaturationAttr:
		_xdr_argument = (xdrproc_t) xdr_rpc_cvi_isp_setsaturationattr_1_argument;
		_xdr_result = (xdrproc_t) xdr_RPC_CVI_S32;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_setsaturationattr_1;
		break;

	case RPC_CVI_ISP_GetSaturationAttr:
		_xdr_argument = (xdrproc_t) xdr_RPC_VI_PIPE;
		_xdr_result = (xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_getsaturationattr_1;
		break;

	case RPC_CVI_ISP_SetCCMAttr:
		_xdr_argument = (xdrproc_t) xdr_rpc_cvi_isp_setccmattr_1_argument;
		_xdr_result = (xdrproc_t) xdr_RPC_CVI_S32;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_setccmattr_1;
		break;

	case RPC_CVI_ISP_GetCCMAttr:
		_xdr_argument = (xdrproc_t) xdr_RPC_VI_PIPE;
		_xdr_result = (xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_getccmattr_1;
		break;

	case RPC_CVI_ISP_SetHSVAttr:
		_xdr_argument = (xdrproc_t) xdr_rpc_cvi_isp_sethsvattr_1_argument;
		_xdr_result = (xdrproc_t) xdr_RPC_CVI_S32;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_sethsvattr_1;
		break;

	case RPC_CVI_ISP_GetHSVAttr:
		_xdr_argument = (xdrproc_t) xdr_RPC_VI_PIPE;
		_xdr_result = (xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_gethsvattr_1;
		break;

	case RPC_CVI_ISP_SetDPDynamicAttr:
		_xdr_argument = (xdrproc_t) xdr_rpc_cvi_isp_setdpdynamicattr_1_argument;
		_xdr_result = (xdrproc_t) xdr_RPC_CVI_S32;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_setdpdynamicattr_1;
		break;

	case RPC_CVI_ISP_GetDPDynamicAttr:
		_xdr_argument = (xdrproc_t) xdr_RPC_VI_PIPE;
		_xdr_result = (xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_getdpdynamicattr_1;
		break;

	case RPC_CVI_ISP_SetDPStaticAttr:
		_xdr_argument = (xdrproc_t) xdr_rpc_cvi_isp_setdpstaticattr_1_argument;
		_xdr_result = (xdrproc_t) xdr_RPC_CVI_S32;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_setdpstaticattr_1;
		break;

	case RPC_CVI_ISP_GetDPStaticAttr:
		_xdr_argument = (xdrproc_t) xdr_RPC_VI_PIPE;
		_xdr_result = (xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_getdpstaticattr_1;
		break;

	case RPC_CVI_ISP_SetDPCalibrate:
		_xdr_argument = (xdrproc_t) xdr_rpc_cvi_isp_setdpcalibrate_1_argument;
		_xdr_result = (xdrproc_t) xdr_RPC_CVI_S32;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_setdpcalibrate_1;
		break;

	case RPC_CVI_ISP_GetDPCalibrate:
		_xdr_argument = (xdrproc_t) xdr_RPC_VI_PIPE;
		_xdr_result = (xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_getdpcalibrate_1;
		break;

	case RPC_CVI_ISP_SetCrosstalkAttr:
		_xdr_argument = (xdrproc_t) xdr_rpc_cvi_isp_setcrosstalkattr_1_argument;
		_xdr_result = (xdrproc_t) xdr_RPC_CVI_S32;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_setcrosstalkattr_1;
		break;

	case RPC_CVI_ISP_GetCrosstalkAttr:
		_xdr_argument = (xdrproc_t) xdr_RPC_VI_PIPE;
		_xdr_result = (xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_getcrosstalkattr_1;
		break;

	case RPC_CVI_ISP_GetAEStatistics:
		_xdr_argument = (xdrproc_t) xdr_RPC_VI_PIPE;
		_xdr_result = (xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_getaestatistics_1;
		break;

	case RPC_CVI_ISP_GetWBStatistics:
		_xdr_argument = (xdrproc_t) xdr_RPC_VI_PIPE;
		_xdr_result = (xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_getwbstatistics_1;
		break;

	case RPC_CVI_ISP_GetFocusStatistics:
		_xdr_argument = (xdrproc_t) xdr_RPC_VI_PIPE;
		_xdr_result = (xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_getfocusstatistics_1;
		break;

	case RPC_CVI_ISP_GetLightboxGain:
		_xdr_argument = (xdrproc_t) xdr_RPC_VI_PIPE;
		_xdr_result = (xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_getlightboxgain_1;
		break;

	case RPC_CVI_ISP_SetFSWDRAttr:
		_xdr_argument = (xdrproc_t) xdr_rpc_cvi_isp_setfswdrattr_1_argument;
		_xdr_result = (xdrproc_t) xdr_RPC_CVI_S32;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_setfswdrattr_1;
		break;

	case RPC_CVI_ISP_GetFSWDRAttr:
		_xdr_argument = (xdrproc_t) xdr_RPC_VI_PIPE;
		_xdr_result = (xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_getfswdrattr_1;
		break;

	case RPC_CVI_ISP_SetDRCAttr:
		_xdr_argument = (xdrproc_t) xdr_rpc_cvi_isp_setdrcattr_1_argument;
		_xdr_result = (xdrproc_t) xdr_RPC_CVI_S32;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_setdrcattr_1;
		break;

	case RPC_CVI_ISP_GetDRCAttr:
		_xdr_argument = (xdrproc_t) xdr_RPC_VI_PIPE;
		_xdr_result = (xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_getdrcattr_1;
		break;

	case RPC_CVI_ISP_SetSharpenAttr:
		_xdr_argument = (xdrproc_t) xdr_rpc_cvi_isp_setsharpenattr_1_argument;
		_xdr_result = (xdrproc_t) xdr_RPC_CVI_S32;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_setsharpenattr_1;
		break;

	case RPC_CVI_ISP_GetSharpenAttr:
		_xdr_argument = (xdrproc_t) xdr_RPC_VI_PIPE;
		_xdr_result = (xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_getsharpenattr_1;
		break;

	case RPC_CVI_ISP_SetNoiseProfileAttr:
		_xdr_argument = (xdrproc_t) xdr_rpc_cvi_isp_setnoiseprofileattr_1_argument;
		_xdr_result = (xdrproc_t) xdr_RPC_CVI_S32;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_setnoiseprofileattr_1;
		break;

	case RPC_CVI_ISP_GetNoiseProfileAttr:
		_xdr_argument = (xdrproc_t) xdr_RPC_VI_PIPE;
		_xdr_result = (xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_getnoiseprofileattr_1;
		break;

	case RPC_CVI_ISP_SetYContrastAttr:
		_xdr_argument = (xdrproc_t) xdr_rpc_cvi_isp_setycontrastattr_1_argument;
		_xdr_result = (xdrproc_t) xdr_RPC_CVI_S32;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_setycontrastattr_1;
		break;

	case RPC_CVI_ISP_GetYContrastAttr:
		_xdr_argument = (xdrproc_t) xdr_RPC_VI_PIPE;
		_xdr_result = (xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_getycontrastattr_1;
		break;

	case RPC_CVI_ISP_SetDCFInfo:
		_xdr_argument = (xdrproc_t) xdr_rpc_cvi_isp_setdcfinfo_1_argument;
		_xdr_result = (xdrproc_t) xdr_RPC_CVI_S32;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_setdcfinfo_1;
		break;

	case RPC_CVI_ISP_GetDCFInfo:
		_xdr_argument = (xdrproc_t) xdr_RPC_VI_PIPE;
		_xdr_result = (xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_getdcfinfo_1;
		break;

	case RPC_CVI_ISP_QueryInnerStateInfo:
		_xdr_argument = (xdrproc_t) xdr_RPC_VI_PIPE;
		_xdr_result = (xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_queryinnerstateinfo_1;
		break;

	case RPC_CVI_ISP_GetVDTimeOut:
		_xdr_argument = (xdrproc_t) xdr_rpc_cvi_isp_getvdtimeout_1_argument;
		_xdr_result = (xdrproc_t) xdr_RPC_CVI_S32;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_getvdtimeout_1;
		break;

	case RPC_CVI_ISP_SetMonoAttr:
		_xdr_argument = (xdrproc_t) xdr_rpc_cvi_isp_setmonoattr_1_argument;
		_xdr_result = (xdrproc_t) xdr_RPC_CVI_S32;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_setmonoattr_1;
		break;

	case RPC_CVI_ISP_GetMonoAttr:
		_xdr_argument = (xdrproc_t) xdr_RPC_VI_PIPE;
		_xdr_result = (xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_getmonoattr_1;
		break;

	case RPC_CVI_ISP_SetDisAttr:
		_xdr_argument = (xdrproc_t) xdr_rpc_cvi_isp_setdisattr_1_argument;
		_xdr_result = (xdrproc_t) xdr_RPC_CVI_S32;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_setdisattr_1;
		break;

	case RPC_CVI_ISP_GetDisAttr:
		_xdr_argument = (xdrproc_t) xdr_RPC_VI_PIPE;
		_xdr_result = (xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_getdisattr_1;
		break;

	case RPC_CVI_ISP_SetDisConfig:
		_xdr_argument = (xdrproc_t) xdr_rpc_cvi_isp_setdisconfig_1_argument;
		_xdr_result = (xdrproc_t) xdr_RPC_CVI_S32;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_setdisconfig_1;
		break;

	case RPC_CVI_ISP_GetDisConfig:
		_xdr_argument = (xdrproc_t) xdr_RPC_VI_PIPE;
		_xdr_result = (xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_getdisconfig_1;
		break;

	case RPC_CVI_ISP_GetBinStatus:
		_xdr_argument = (xdrproc_t) xdr_RPC_VI_PIPE;
		_xdr_result = (xdrproc_t) xdr_RPC_CVI_S32;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_getbinstatus_1;
		break;

	case RPC_CVI_ISP_SetVCAttr:
		_xdr_argument = (xdrproc_t) xdr_rpc_cvi_isp_setvcattr_1_argument;
		_xdr_result = (xdrproc_t) xdr_RPC_CVI_S32;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_setvcattr_1;
		break;

	case RPC_CVI_ISP_GetVCAttr:
		_xdr_argument = (xdrproc_t) xdr_RPC_VI_PIPE;
		_xdr_result = (xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_getvcattr_1;
		break;

	case RPC_CVI_ISP_DumpHwRegisterToFile:
		_xdr_argument = (xdrproc_t) xdr_rpc_cvi_isp_dumphwregistertofile_1_argument;
		_xdr_result = (xdrproc_t) xdr_RPC_CVI_S32;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_dumphwregistertofile_1;
		break;

	case RPC_CVI_ISP_DumpFrameRawInfoToFile:
		_xdr_argument = (xdrproc_t) xdr_rpc_cvi_isp_dumpframerawinfotofile_1_argument;
		_xdr_result = (xdrproc_t) xdr_RPC_CVI_S32;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_dumpframerawinfotofile_1;
		break;

	case RPC_CVI_ISP_IrAutoRunOnce:
		_xdr_argument = (xdrproc_t) xdr_rpc_cvi_isp_irautorunonce_1_argument;
		_xdr_result = (xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_irautorunonce_1;
		break;

	case RPC_CVI_ISP_SetSmartInfo:
		_xdr_argument = (xdrproc_t) xdr_rpc_cvi_isp_setsmartinfo_1_argument;
		_xdr_result = (xdrproc_t) xdr_RPC_CVI_S32;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_setsmartinfo_1;
		break;

	case RPC_CVI_ISP_GetSmartInfo:
		_xdr_argument = (xdrproc_t) xdr_RPC_VI_PIPE;
		_xdr_result = (xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_getsmartinfo_1;
		break;

	case RPC_CVI_ISP_SetTNRMotionAdaptAttr:
		_xdr_argument = (xdrproc_t) xdr_rpc_cvi_isp_settnrmotionadaptattr_1_argument;
		_xdr_result = (xdrproc_t) xdr_RPC_CVI_S32;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_settnrmotionadaptattr_1;
		break;

	case RPC_CVI_ISP_GetTNRMotionAdaptAttr:
		_xdr_argument = (xdrproc_t) xdr_RPC_VI_PIPE;
		_xdr_result = (xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_gettnrmotionadaptattr_1;
		break;

	case RPC_CVI_ISP_SetClutSaturationAttr:
		_xdr_argument = (xdrproc_t) xdr_rpc_cvi_isp_setclutsaturationattr_1_argument;
		_xdr_result = (xdrproc_t) xdr_RPC_CVI_S32;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_setclutsaturationattr_1;
		break;

	case RPC_CVI_ISP_GetClutSaturationAttr:
		_xdr_argument = (xdrproc_t) xdr_RPC_VI_PIPE;
		_xdr_result = (xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_getclutsaturationattr_1;
		break;

	case RPC_CVI_ISP_GetGammaCurveByType:
		_xdr_argument = (xdrproc_t) xdr_rpc_cvi_isp_getgammacurvebytype_1_argument;
		_xdr_result = (xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_getgammacurvebytype_1;
		break;

	case RPC_CVI_ISP_SetPreSharpenAttr:
		_xdr_argument = (xdrproc_t) xdr_rpc_cvi_isp_setpresharpenattr_1_argument;
		_xdr_result = (xdrproc_t) xdr_RPC_CVI_S32;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_setpresharpenattr_1;
		break;

	case RPC_CVI_ISP_GetPreSharpenAttr:
		_xdr_argument = (xdrproc_t) xdr_RPC_VI_PIPE;
		_xdr_result = (xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_getpresharpenattr_1;
		break;

	case RPC_CVI_ISP_SetRGBCACAttr:
		_xdr_argument = (xdrproc_t) xdr_rpc_cvi_isp_setrgbcacattr_1_argument;
		_xdr_result = (xdrproc_t) xdr_RPC_CVI_S32;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_setrgbcacattr_1;
		break;

	case RPC_CVI_ISP_GetRGBCACAttr:
		_xdr_argument = (xdrproc_t) xdr_RPC_VI_PIPE;
		_xdr_result = (xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_getrgbcacattr_1;
		break;

	case RPC_CVI_ISP_SetCNRMotionNRAttr:
		_xdr_argument = (xdrproc_t) xdr_rpc_cvi_isp_setcnrmotionnrattr_1_argument;
		_xdr_result = (xdrproc_t) xdr_RPC_CVI_S32;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_setcnrmotionnrattr_1;
		break;

	case RPC_CVI_ISP_GetCNRMotionNRAttr:
		_xdr_argument = (xdrproc_t) xdr_RPC_VI_PIPE;
		_xdr_result = (xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_getcnrmotionnrattr_1;
		break;

	case RPC_CVI_ISP_SetCCMSaturationAttr:
		_xdr_argument = (xdrproc_t) xdr_rpc_cvi_isp_setccmsaturationattr_1_argument;
		_xdr_result = (xdrproc_t) xdr_RPC_CVI_S32;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_setccmsaturationattr_1;
		break;

	case RPC_CVI_ISP_GetCCMSaturationAttr:
		_xdr_argument = (xdrproc_t) xdr_RPC_VI_PIPE;
		_xdr_result = (xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_getccmsaturationattr_1;
		break;

	case RPC_CVI_ISP_SetCAAttr:
		_xdr_argument = (xdrproc_t) xdr_rpc_cvi_isp_setcaattr_1_argument;
		_xdr_result = (xdrproc_t) xdr_RPC_CVI_S32;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_setcaattr_1;
		break;

	case RPC_CVI_ISP_GetCAAttr:
		_xdr_argument = (xdrproc_t) xdr_RPC_VI_PIPE;
		_xdr_result = (xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_getcaattr_1;
		break;

	case RPC_CVI_ISP_SetCSCAttr:
		_xdr_argument = (xdrproc_t) xdr_rpc_cvi_isp_setcscattr_1_argument;
		_xdr_result = (xdrproc_t) xdr_RPC_CVI_S32;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_setcscattr_1;
		break;

	case RPC_CVI_ISP_GetCSCAttr:
		_xdr_argument = (xdrproc_t) xdr_RPC_VI_PIPE;
		_xdr_result = (xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_getcscattr_1;
		break;

	case RPC_CVI_ISP_SetExposureAttr:
		_xdr_argument = (xdrproc_t) xdr_rpc_cvi_isp_setexposureattr_1_argument;
		_xdr_result = (xdrproc_t) xdr_RPC_CVI_S32;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_setexposureattr_1;
		break;

	case RPC_CVI_ISP_GetExposureAttr:
		_xdr_argument = (xdrproc_t) xdr_RPC_VI_PIPE;
		_xdr_result = (xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_getexposureattr_1;
		break;

	case RPC_CVI_ISP_QueryExposureInfo:
		_xdr_argument = (xdrproc_t) xdr_RPC_VI_PIPE;
		_xdr_result = (xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_queryexposureinfo_1;
		break;

	case RPC_CVI_ISP_SetWDRExposureAttr:
		_xdr_argument = (xdrproc_t) xdr_rpc_cvi_isp_setwdrexposureattr_1_argument;
		_xdr_result = (xdrproc_t) xdr_RPC_CVI_S32;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_setwdrexposureattr_1;
		break;

	case RPC_CVI_ISP_GetWDRExposureAttr:
		_xdr_argument = (xdrproc_t) xdr_RPC_VI_PIPE;
		_xdr_result = (xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_getwdrexposureattr_1;
		break;

	case RPC_CVI_ISP_SetAERouteAttr:
		_xdr_argument = (xdrproc_t) xdr_rpc_cvi_isp_setaerouteattr_1_argument;
		_xdr_result = (xdrproc_t) xdr_RPC_CVI_S32;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_setaerouteattr_1;
		break;

	case RPC_CVI_ISP_GetAERouteAttr:
		_xdr_argument = (xdrproc_t) xdr_RPC_VI_PIPE;
		_xdr_result = (xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_getaerouteattr_1;
		break;

	case RPC_CVI_ISP_SetAERouteAttrEx:
		_xdr_argument = (xdrproc_t) xdr_rpc_cvi_isp_setaerouteattrex_1_argument;
		_xdr_result = (xdrproc_t) xdr_RPC_CVI_S32;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_setaerouteattrex_1;
		break;

	case RPC_CVI_ISP_GetAERouteAttrEx:
		_xdr_argument = (xdrproc_t) xdr_RPC_VI_PIPE;
		_xdr_result = (xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_getaerouteattrex_1;
		break;

	case RPC_CVI_ISP_AEBracketingStart:
		_xdr_argument = (xdrproc_t) xdr_RPC_VI_PIPE;
		_xdr_result = (xdrproc_t) xdr_RPC_CVI_S32;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_aebracketingstart_1;
		break;

	case RPC_CVI_ISP_AEBracketingSetExpsoure:
		_xdr_argument = (xdrproc_t) xdr_rpc_cvi_isp_aebracketingsetexpsoure_1_argument;
		_xdr_result = (xdrproc_t) xdr_RPC_CVI_S32;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_aebracketingsetexpsoure_1;
		break;

	case RPC_CVI_ISP_AEBracketingFinish:
		_xdr_argument = (xdrproc_t) xdr_RPC_VI_PIPE;
		_xdr_result = (xdrproc_t) xdr_RPC_CVI_S32;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_aebracketingfinish_1;
		break;

	case RPC_CVI_ISP_AEBracketingSetSimple:
		_xdr_argument = (xdrproc_t) xdr_uint8_t;
		_xdr_result = (xdrproc_t) xdr_RPC_CVI_S32;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_aebracketingsetsimple_1;
		break;

	case RPC_CVI_ISP_SetAEStatisticsConfig:
		_xdr_argument = (xdrproc_t) xdr_rpc_cvi_isp_setaestatisticsconfig_1_argument;
		_xdr_result = (xdrproc_t) xdr_RPC_CVI_S32;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_setaestatisticsconfig_1;
		break;

	case RPC_CVI_ISP_GetAEStatisticsConfig:
		_xdr_argument = (xdrproc_t) xdr_RPC_VI_PIPE;
		_xdr_result = (xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_getaestatisticsconfig_1;
		break;

	case RPC_CVI_ISP_SetAntiFlicker:
		_xdr_argument = (xdrproc_t) xdr_rpc_cvi_isp_setantiflicker_1_argument;
		_xdr_result = (xdrproc_t) xdr_RPC_CVI_S32;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_setantiflicker_1;
		break;

	case RPC_CVI_ISP_GetAntiFlicker:
		_xdr_argument = (xdrproc_t) xdr_RPC_VI_PIPE;
		_xdr_result = (xdrproc_t) xdr_uint32_t;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_getantiflicker_1;
		break;

	case RPC_CVI_ISP_SetWDRLEOnly:
		_xdr_argument = (xdrproc_t) xdr_rpc_cvi_isp_setwdrleonly_1_argument;
		_xdr_result = (xdrproc_t) xdr_RPC_CVI_S32;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_setwdrleonly_1;
		break;

	case RPC_CVI_ISP_GetFrameID:
		_xdr_argument = (xdrproc_t) xdr_RPC_VI_PIPE;
		_xdr_result = (xdrproc_t) xdr_uint32_t;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_getframeid_1;
		break;

	case RPC_CVI_ISP_SetAELogPath:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_RPC_CVI_S32;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_setaelogpath_1;
		break;

	case RPC_CVI_ISP_GetAELogPath:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_getaelogpath_1;
		break;

	case RPC_CVI_ISP_SetAELogName:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_RPC_CVI_S32;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_setaelogname_1;
		break;

	case RPC_CVI_ISP_GetAELogName:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_getaelogname_1;
		break;

	case RPC_CVI_ISP_QueryFps:
		_xdr_argument = (xdrproc_t) xdr_RPC_VI_PIPE;
		_xdr_result = (xdrproc_t) xdr_float;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_queryfps_1;
		break;

	case RPC_CVI_ISP_GetAELogBuf:
		_xdr_argument = (xdrproc_t) xdr_RPC_VI_PIPE;
		_xdr_result = (xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_getaelogbuf_1;
		break;

	case RPC_CVI_ISP_GetAELogBufSize:
		_xdr_argument = (xdrproc_t) xdr_RPC_VI_PIPE;
		_xdr_result = (xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_getaelogbufsize_1;
		break;

	case RPC_CVI_ISP_GetAEBinBuf:
		_xdr_argument = (xdrproc_t) xdr_RPC_VI_PIPE;
		_xdr_result = (xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_getaebinbuf_1;
		break;

	case RPC_CVI_ISP_GetAEBinBufSize:
		_xdr_argument = (xdrproc_t) xdr_RPC_VI_PIPE;
		_xdr_result = (xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_getaebinbufsize_1;
		break;

	case RPC_CVI_ISP_GetCurrentLvX100:
		_xdr_argument = (xdrproc_t) xdr_RPC_VI_PIPE;
		_xdr_result = (xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_getcurrentlvx100_1;
		break;

	case RPC_CVI_ISP_SetFastBootExposure:
		_xdr_argument = (xdrproc_t) xdr_rpc_cvi_isp_setfastbootexposure_1_argument;
		_xdr_result = (xdrproc_t) xdr_RPC_CVI_S32;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_setfastbootexposure_1;
		break;

	case RPC_CVI_ISP_SetSmartExposureAttr:
		_xdr_argument = (xdrproc_t) xdr_rpc_cvi_isp_setsmartexposureattr_1_argument;
		_xdr_result = (xdrproc_t) xdr_RPC_CVI_S32;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_setsmartexposureattr_1;
		break;

	case RPC_CVI_ISP_GetSmartExposureAttr:
		_xdr_argument = (xdrproc_t) xdr_RPC_VI_PIPE;
		_xdr_result = (xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_getsmartexposureattr_1;
		break;

	case RPC_CVI_ISP_SetWBAttr:
		_xdr_argument = (xdrproc_t) xdr_rpc_cvi_isp_setwbattr_1_argument;
		_xdr_result = (xdrproc_t) xdr_RPC_CVI_S32;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_setwbattr_1;
		break;

	case RPC_CVI_ISP_GetWBAttr:
		_xdr_argument = (xdrproc_t) xdr_RPC_VI_PIPE;
		_xdr_result = (xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_getwbattr_1;
		break;

	case RPC_CVI_ISP_SetAWBAttrEx:
		_xdr_argument = (xdrproc_t) xdr_rpc_cvi_isp_setawbattrex_1_argument;
		_xdr_result = (xdrproc_t) xdr_RPC_CVI_S32;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_setawbattrex_1;
		break;

	case RPC_CVI_ISP_GetAWBAttrEx:
		_xdr_argument = (xdrproc_t) xdr_RPC_VI_PIPE;
		_xdr_result = (xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_getawbattrex_1;
		break;

	case RPC_CVI_ISP_QueryWBInfo:
		_xdr_argument = (xdrproc_t) xdr_RPC_VI_PIPE;
		_xdr_result = (xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_querywbinfo_1;
		break;

	case RPC_CVI_ISP_SetWBCalibration:
		_xdr_argument = (xdrproc_t) xdr_rpc_cvi_isp_setwbcalibration_1_argument;
		_xdr_result = (xdrproc_t) xdr_RPC_CVI_S32;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_setwbcalibration_1;
		break;

	case RPC_CVI_ISP_GetWBCalibration:
		_xdr_argument = (xdrproc_t) xdr_RPC_VI_PIPE;
		_xdr_result = (xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_getwbcalibration_1;
		break;

	case RPC_CVI_ISP_SetWBCalibrationEx:
		_xdr_argument = (xdrproc_t) xdr_rpc_cvi_isp_setwbcalibrationex_1_argument;
		_xdr_result = (xdrproc_t) xdr_RPC_CVI_S32;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_setwbcalibrationex_1;
		break;

	case RPC_CVI_ISP_GetWBCalibrationEx:
		_xdr_argument = (xdrproc_t) xdr_RPC_VI_PIPE;
		_xdr_result = (xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_getwbcalibrationex_1;
		break;

	case RPC_CVI_ISP_SetAWBWinStatictics:
		_xdr_argument = (xdrproc_t) xdr_rpc_cvi_isp_setawbwinstatictics_1_argument;
		_xdr_result = (xdrproc_t) xdr_RPC_CVI_S32;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_setawbwinstatictics_1;
		break;

	case RPC_CVI_ISP_GetAWBWinStatictics:
		_xdr_argument = (xdrproc_t) xdr_RPC_VI_PIPE;
		_xdr_result = (xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_getawbwinstatictics_1;
		break;

	case RPC_CVI_ISP_GetAWBSnapLogBuf:
		_xdr_argument = (xdrproc_t) xdr_RPC_VI_PIPE;
		_xdr_result = (xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_getawbsnaplogbuf_1;
		break;

	case RPC_CVI_ISP_GetAWBDbgBinBuf:
		_xdr_argument = (xdrproc_t) xdr_RPC_VI_PIPE;
		_xdr_result = (xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_getawbdbgbinbuf_1;
		break;

	case RPC_CVI_ISP_GetAWBDbgBinSize:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_RPC_CVI_S32;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_getawbdbgbinsize_1;
		break;

	case RPC_CVI_ISP_GetAWBCurve:
		_xdr_argument = (xdrproc_t) xdr_RPC_VI_PIPE;
		_xdr_result = (xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_getawbcurve_1;
		break;

	case RPC_CVI_ISP_SetAWBLogPath:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_RPC_CVI_S32;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_setawblogpath_1;
		break;

	case RPC_CVI_ISP_SetAWBLogName:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_RPC_CVI_S32;
		local = (char *(*)(char *, struct svc_req *)) _rpc_cvi_isp_setawblogname_1;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

static void register_and_run_svc(void)
{
	register SVCXPRT *transp;

	pmap_unset (ISP_RPC, ISP_RPC_VERSION);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, ISP_RPC, ISP_RPC_VERSION, isp_rpc_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (ISP_RPC, ISP_RPC_VERSION, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, ISP_RPC, ISP_RPC_VERSION, isp_rpc_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (ISP_RPC, ISP_RPC_VERSION, tcp).");
		exit(1);
	}

	svc_run ();
}

#include <sys/prctl.h>
#include <pthread.h>
#include <unistd.h>
#include "cvi_isp.h"

extern void isp_rpc_init_result_mem(void);

/*
static void *isp_rpc_main(void *arg)
{
	arg = arg;

	prctl(PR_SET_NAME, "ispRpcThread");

	while (access("/tmp/startIspRpc", F_OK) != 0x00) {
		usleep(300 * 1000);
	}

	{
		ISP_PUB_ATTR_S stPubAttr;

		memset(&stPubAttr, 0, sizeof(ISP_PUB_ATTR_S));

		do {
			usleep(100 * 1000);
			CVI_ISP_GetPubAttr(0, &stPubAttr);
		} while (stPubAttr.f32FrameRate == 0x00);
	}

	printf("start isp rpc....\n");

	isp_rpc_init_result_mem();

	register_and_run_svc();

	return NULL;
}

static __attribute__((constructor)) void start_isp_rpc_thread(void)
{
	pthread_t pid;

	pthread_create(&pid, NULL, isp_rpc_main, NULL);
}
*/

static void *isp_rpc_main(void *arg)
{
	arg = arg;

	prctl(PR_SET_NAME, "ispRpcThread");

	printf("start isp rpc....\n");

	isp_rpc_init_result_mem();

	register_and_run_svc();

	return NULL;
}

static void start_isp_rpc_thread(void)
{
	pthread_t pid;
	pthread_create(&pid, NULL, isp_rpc_main, NULL);
}

void init_isp_rpc(void)
{
	if (access("/tmp/startIspRpc", F_OK) == 0x00) {
		start_isp_rpc_thread();
	}
}

#pragma GCC diagnostic pop

