/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "cvi_isp.h"
#include "cvi_ae.h"
#include "cvi_awb.h"
#include "isp_debug.h"

//#define LOGOUT(fmt, arg...) printf(fmt, ##arg)
#define LOGOUT(fmt, arg...) ISP_DEBUG(LOG_DEBUG, fmt, ##arg)

#define LOGOUT_ERROR() ({                                 \
		LOGOUT("[ERROR] %s:%d\n", __func__, __LINE__);})

#pragma GCC diagnostic push
//#pragma GCC diagnostic ignored "-Wunused-variable"
#pragma GCC diagnostic ignored "-Wunused-parameter"
//#pragma GCC diagnostic ignored "-Wuninitialized"

#define __BUFFER_SIZE  (256 * 1024)

typedef struct _ISP_COMMON_BUFFER_S {
	uint8_t buffer[__BUFFER_SIZE];
} ISP_COMMON_BUFFER_S;

union unResult {
	ISP_COMMON_BUFFER_S stBuffer;
	ISP_PUB_ATTR_S stPubAttr;
	ISP_MOD_PARAM_S stModParam;
	ISP_CTRL_PARAM_S stIspCtrlParam;
	ISP_MODULE_CTRL_U unModCtrl;
	ISP_COLOR_TONE_ATTR_S stWBGAttr;
	ISP_DEHAZE_ATTR_S stDehazeAttr;
	ISP_GAMMA_ATTR_S stGammaAttr;
	ISP_AUTO_GAMMA_ATTR_S stAutoGammaAttr;
	ISP_STATISTICS_CFG_S stStatCfg;
	ISP_NR_ATTR_S stNRAttr;
	ISP_NR_FILTER_ATTR_S stNRFilterAttr;
	ISP_RLSC_ATTR_S stRLSCAttr;
	ISP_YNR_ATTR_S stYNRAttrl;
	ISP_YNR_MOTION_NR_ATTR_S stYNRMotionNRAttr;
	ISP_YNR_FILTER_ATTR_S stYNRFilterAttr;
	ISP_CNR_ATTR_S stCNRAttr;
	ISP_CAC_ATTR_S stCACAttr;
	ISP_DCI_ATTR_S stDCIAttr;
	ISP_MESH_SHADING_ATTR_S stMeshShadingAttr;
	ISP_MESH_SHADING_GAIN_LUT_ATTR_S stMeshShadingGainLutAttr;
	ISP_RADIAL_SHADING_ATTR_S stRadialShadingAttr;
	ISP_RADIAL_SHADING_GAIN_LUT_ATTR_S stRadialShadingGainLutAttr;
	ISP_TNR_ATTR_S stTNRAttr;
	ISP_TNR_NOISE_MODEL_ATTR_S stTNRNoiseModelAttr;
	ISP_TNR_LUMA_MOTION_ATTR_S stTNRLumaMotionAttr;
	ISP_TNR_GHOST_ATTR_S stTNRGhostAttr;
	ISP_TNR_MT_PRT_ATTR_S stTNRMtPrtAttr;
	ISP_CLUT_ATTR_S stCLutAttr;
#ifdef ARCH_CV183X
	ISP_CLUT_LUT_S stClutLUT;
#endif
	ISP_BLACK_LEVEL_ATTR_S stBlackLevelAttr;
	ISP_DEMOSAIC_ATTR_S stDemosaicAttr;
	ISP_DEMOSAIC_DEMOIRE_ATTR_S stDemosaicDemoireAttr;
	ISP_DEMOSAIC_FILTER_ATTR_S stDemosaicFilterAttr;
#ifdef ARCH_CV183X
	ISP_DEMOSAIC_EE_ATTR_S stDemosaicEEAttr;
#endif
	ISP_SATURATION_ATTR_S stSaturationAttr;
	ISP_CCM_ATTR_S stCCMAttr;
#ifdef ARCH_CV183X
	ISP_HSV_ATTR_S stHSVAttr;
#endif
	ISP_DP_DYNAMIC_ATTR_S stDPCDynamicAttr;
	ISP_DP_STATIC_ATTR_S stDPStaticAttr;
	ISP_DP_CALIB_ATTR_S stDPCalibAttr;
	ISP_CROSSTALK_ATTR_S stCrosstalkAttr;
	ISP_AE_STATISTICS_S stAeStat;
	ISP_WB_STATISTICS_S stWBStat;
	ISP_AF_STATISTICS_S stAfStat;
	ISP_AWB_LightBox_Gain_S stAWBLightBoxGain;
	ISP_FSWDR_ATTR_S stFSWDRAttr;
	ISP_DRC_ATTR_S stDRCAttr;
	ISP_SHARPEN_ATTR_S stSharpenAttr;
	ISP_CMOS_NOISE_CALIBRATION_S stNoiseProfileAttr;
	ISP_YCONTRAST_ATTR_S stYContrastAttr;
	ISP_DCF_INFO_S stIspDCF;
	ISP_INNER_STATE_INFO_S stInnerStateInfo;
	ISP_MONO_ATTR_S stMonoAttr;
	ISP_DIS_ATTR_S stDisAttr;
	ISP_DIS_CONFIG_S stDisConfig;
	ISP_VC_ATTR_S stVCAttr;
	ISP_SMART_INFO_S stSmartInfoAttr;
#ifdef ARCH_CV182X
	ISP_TNR_MOTION_ADAPT_ATTR_S stMotionAdaptAttr;
	ISP_CLUT_SATURATION_ATTR_S stClutSaturationAttr;
	ISP_GAMMA_ATTR_S stGammaCurve;
	ISP_PRESHARPEN_ATTR_S stPreSharpenAttr;
	ISP_RGBCAC_ATTR_S stRGBCACAttr;
	ISP_CNR_MOTION_NR_ATTR_S stCNRMotionNRAttr;
	ISP_CCM_SATURATION_ATTR_S stCCMSaturationAttr;
	ISP_CA_ATTR_S stCAAttr;
	ISP_CSC_ATTR_S stCSCAttr;
#endif
	ISP_EXPOSURE_ATTR_S stExpAttr;
	ISP_EXP_INFO_S stExpInfo;
	ISP_WDR_EXPOSURE_ATTR_S stWDRExpAttr;
	ISP_AE_ROUTE_S stAERouteAttr;
	ISP_AE_ROUTE_EX_S stAERouteAttrEx;
	ISP_AE_STATISTICS_CFG_S stAeStatisticsCfg;
	ISP_SMART_EXPOSURE_ATTR_S stSmartExpAttr;
	ISP_WB_ATTR_S stWBAttr;
	ISP_AWB_ATTR_EX_S stAWBAttrEx;
	ISP_WB_INFO_S stWBInfo;
	ISP_AWB_Calibration_Gain_S stWBCalib;
	ISP_AWB_Calibration_Gain_S_EX stWBCalibEx;
	ISP_WB_STATISTICS_CFG_S stAwbWinCfg;
	ISP_WB_CURVE_S shWBCurve;
};

static union unResult *punResult = NULL;

#define SET_ATTR(__TYPE, __FUN) ({							     \
		__TYPE *p = NULL;                                        \
		if (stAttrData.data.data_len == sizeof(__TYPE)) {        \
			p = (__TYPE *) stAttrData.data.data_val;             \
			result = __FUN(ViPipe, p);                           \
		} else {                                                 \
			result = CVI_FAILURE;                                \
			LOGOUT_ERROR();                                      \
		}})

#define GET_ATTR(__TYPE, __NAME, __FUN) ({                       \
		memset(&punResult->__NAME, 0, sizeof(__TYPE));           \
		result.ret = __FUN(ViPipe, &punResult->__NAME);          \
		result.data.data_len = sizeof(__TYPE);                   \
		result.data.data_val = (uint8_t *) &punResult->__NAME;})


void isp_rpc_init_result_mem(void)
{
	punResult = calloc(1, sizeof(union unResult));

	if (punResult == NULL) {
		LOGOUT_ERROR();
	}
}

/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "isp_rpc.h"

RPC_CVI_S32 *
rpc_cvi_isp_setpubattr_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */
	SET_ATTR(ISP_PUB_ATTR_S, CVI_ISP_SetPubAttr);

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getpubattr_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */
	GET_ATTR(ISP_PUB_ATTR_S, stPubAttr, CVI_ISP_GetPubAttr);

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setmodparam_1_svc(RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */
	ISP_MOD_PARAM_S *p = NULL;

	if (stAttrData.data.data_len == sizeof(ISP_MOD_PARAM_S)) {
		p = (ISP_MOD_PARAM_S *) stAttrData.data.data_val;
		result = CVI_ISP_SetModParam(p);
	} else {
		result = CVI_FAILURE;
		LOGOUT_ERROR();
	}

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getmodparam_1_svc(struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */
	memset(&punResult->stModParam, 0, sizeof(ISP_MOD_PARAM_S));
	result.ret = CVI_ISP_GetModParam(&punResult->stModParam);
	result.data.data_len = sizeof(ISP_MOD_PARAM_S);
	result.data.data_val = (uint8_t *) &punResult->stModParam;

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setctrlparam_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */
	SET_ATTR(ISP_CTRL_PARAM_S, CVI_ISP_SetCtrlParam);

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getctrlparam_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */
	GET_ATTR(ISP_CTRL_PARAM_S, stIspCtrlParam, CVI_ISP_GetCtrlParam);

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setfmwstate_1_svc(RPC_VI_PIPE ViPipe, uint32_t enState,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */
	result = CVI_ISP_SetFMWState(ViPipe, enState);

	return &result;
}

uint32_t *
rpc_cvi_isp_getfmwstate_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static uint32_t  result;

	/*
	 * insert server code here
	 */
	CVI_ISP_GetFMWState(ViPipe, &result);

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setmodulecontrol_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */
	SET_ATTR(ISP_MODULE_CTRL_U, CVI_ISP_SetModuleControl);

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getmodulecontrol_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */
	GET_ATTR(ISP_MODULE_CTRL_U, unModCtrl, CVI_ISP_GetModuleControl);

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setregister_1_svc(RPC_VI_PIPE ViPipe, uint32_t u32Addr, uint32_t u32Value,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */
	result = CVI_ISP_SetRegister(ViPipe, u32Addr, u32Value);

	return &result;
}

uint32_t *
rpc_cvi_isp_getregister_1_svc(RPC_VI_PIPE ViPipe, uint32_t u32Addr,  struct svc_req *rqstp)
{
	static uint32_t  result;

	/*
	 * insert server code here
	 */
	CVI_ISP_GetRegister(ViPipe, u32Addr, &result);

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setcolortoneattr_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */
	SET_ATTR(ISP_COLOR_TONE_ATTR_S, CVI_ISP_SetColorToneAttr);

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getcolortoneattr_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */
	GET_ATTR(ISP_COLOR_TONE_ATTR_S, stWBGAttr, CVI_ISP_GetColorToneAttr);

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setdehazeattr_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */
	SET_ATTR(ISP_DEHAZE_ATTR_S, CVI_ISP_SetDehazeAttr);

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getdehazeattr_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */
	GET_ATTR(ISP_DEHAZE_ATTR_S, stDehazeAttr, CVI_ISP_GetDehazeAttr);

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setgammaattr_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */
	SET_ATTR(ISP_GAMMA_ATTR_S, CVI_ISP_SetGammaAttr);
	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getgammaattr_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */
	GET_ATTR(ISP_GAMMA_ATTR_S, stGammaAttr, CVI_ISP_GetGammaAttr);


	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setgammacurvetype_1_svc(RPC_VI_PIPE ViPipe, uint32_t curveType,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */
#ifdef ARCH_CV183X
	result = CVI_ISP_SetGammaCurveType(ViPipe, curveType);
#endif
	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setautogammaattr_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */
	SET_ATTR(ISP_AUTO_GAMMA_ATTR_S, CVI_ISP_SetAutoGammaAttr);

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getautogammaattr_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */
	GET_ATTR(ISP_AUTO_GAMMA_ATTR_S, stAutoGammaAttr, CVI_ISP_GetAutoGammaAttr);

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setstatisticsconfig_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */
	SET_ATTR(ISP_STATISTICS_CFG_S, CVI_ISP_SetStatisticsConfig);

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getstatisticsconfig_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */
	GET_ATTR(ISP_STATISTICS_CFG_S, stStatCfg, CVI_ISP_GetStatisticsConfig);

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setnrattr_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */
	SET_ATTR(ISP_NR_ATTR_S, CVI_ISP_SetNRAttr);

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getnrattr_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */
	GET_ATTR(ISP_NR_ATTR_S, stNRAttr, CVI_ISP_GetNRAttr);

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setnrfilterattr_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */
	SET_ATTR(ISP_NR_FILTER_ATTR_S, CVI_ISP_SetNRFilterAttr);

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getnrfilterattr_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */
	GET_ATTR(ISP_NR_FILTER_ATTR_S, stNRFilterAttr, CVI_ISP_GetNRFilterAttr);

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setrlscattr_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */
	SET_ATTR(ISP_RLSC_ATTR_S, CVI_ISP_SetRLSCAttr);

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getrlscattr_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */
	GET_ATTR(ISP_RLSC_ATTR_S, stRLSCAttr, CVI_ISP_GetRLSCAttr);

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setynrattr_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */
	SET_ATTR(ISP_YNR_ATTR_S, CVI_ISP_SetYNRAttr);

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getynrattr_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */
	GET_ATTR(ISP_YNR_ATTR_S, stYNRAttrl, CVI_ISP_GetYNRAttr);

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setynrmotionnrattr_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */
	SET_ATTR(ISP_YNR_MOTION_NR_ATTR_S, CVI_ISP_SetYNRMotionNRAttr);

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getynrmotionnrattr_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */
	GET_ATTR(ISP_YNR_MOTION_NR_ATTR_S, stYNRMotionNRAttr, CVI_ISP_GetYNRMotionNRAttr);

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setynrfilterattr_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */
	SET_ATTR(ISP_YNR_FILTER_ATTR_S, CVI_ISP_SetYNRFilterAttr);

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getynrfilterattr_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */
	GET_ATTR(ISP_YNR_FILTER_ATTR_S, stYNRFilterAttr, CVI_ISP_GetYNRFilterAttr);

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setcnrattr_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */
	SET_ATTR(ISP_CNR_ATTR_S, CVI_ISP_SetCNRAttr);

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getcnrattr_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */
	GET_ATTR(ISP_CNR_ATTR_S, stCNRAttr, CVI_ISP_GetCNRAttr);

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setcacattr_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */
	SET_ATTR(ISP_CAC_ATTR_S, CVI_ISP_SetCACAttr);

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getcacattr_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */
	GET_ATTR(ISP_CAC_ATTR_S, stCACAttr, CVI_ISP_GetCACAttr);

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setdciattr_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */
	SET_ATTR(ISP_DCI_ATTR_S, CVI_ISP_SetDCIAttr);

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getdciattr_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */
	GET_ATTR(ISP_DCI_ATTR_S, stDCIAttr, CVI_ISP_GetDCIAttr);

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setmeshshadingattr_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */
	SET_ATTR(ISP_MESH_SHADING_ATTR_S, CVI_ISP_SetMeshShadingAttr);

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getmeshshadingattr_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */
	GET_ATTR(ISP_MESH_SHADING_ATTR_S, stMeshShadingAttr, CVI_ISP_GetMeshShadingAttr);

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setmeshshadinggainlutattr_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */
	SET_ATTR(ISP_MESH_SHADING_GAIN_LUT_ATTR_S, CVI_ISP_SetMeshShadingGainLutAttr);

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getmeshshadinggainlutattr_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */
	GET_ATTR(ISP_MESH_SHADING_GAIN_LUT_ATTR_S, stMeshShadingGainLutAttr, CVI_ISP_GetMeshShadingGainLutAttr);

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setradialshadingattr_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */
	SET_ATTR(ISP_RADIAL_SHADING_ATTR_S, CVI_ISP_SetRadialShadingAttr);

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getradialshadingattr_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */
	GET_ATTR(ISP_RADIAL_SHADING_ATTR_S, stRadialShadingAttr, CVI_ISP_GetRadialShadingAttr);

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setradialshadinggainlutattr_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */
	SET_ATTR(ISP_RADIAL_SHADING_GAIN_LUT_ATTR_S, CVI_ISP_SetRadialShadingGainLutAttr);

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getradialshadinggainlutattr_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */
	GET_ATTR(ISP_RADIAL_SHADING_GAIN_LUT_ATTR_S, stRadialShadingGainLutAttr, CVI_ISP_GetRadialShadingGainLutAttr);

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_settnrattr_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */
	SET_ATTR(ISP_TNR_ATTR_S, CVI_ISP_SetTNRAttr);

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_gettnrattr_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */
	GET_ATTR(ISP_TNR_ATTR_S, stTNRAttr, CVI_ISP_GetTNRAttr);

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_settnrnoisemodelattr_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */
	SET_ATTR(ISP_TNR_NOISE_MODEL_ATTR_S, CVI_ISP_SetTNRNoiseModelAttr);

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_gettnrnoisemodelattr_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */
	GET_ATTR(ISP_TNR_NOISE_MODEL_ATTR_S, stTNRNoiseModelAttr, CVI_ISP_GetTNRNoiseModelAttr);

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_settnrlumamotionattr_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */
	SET_ATTR(ISP_TNR_LUMA_MOTION_ATTR_S, CVI_ISP_SetTNRLumaMotionAttr);

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_gettnrlumamotionattr_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */
	GET_ATTR(ISP_TNR_LUMA_MOTION_ATTR_S, stTNRLumaMotionAttr, CVI_ISP_GetTNRLumaMotionAttr);

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_settnrghostattr_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */
	SET_ATTR(ISP_TNR_GHOST_ATTR_S, CVI_ISP_SetTNRGhostAttr);

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_gettnrghostattr_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */
	GET_ATTR(ISP_TNR_GHOST_ATTR_S, stTNRGhostAttr, CVI_ISP_GetTNRGhostAttr);

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_settnrmtprtattr_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */
	SET_ATTR(ISP_TNR_MT_PRT_ATTR_S, CVI_ISP_SetTNRMtPrtAttr);

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_gettnrmtprtattr_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */
	GET_ATTR(ISP_TNR_MT_PRT_ATTR_S, stTNRMtPrtAttr, CVI_ISP_GetTNRMtPrtAttr);

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setclutattr_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */
	SET_ATTR(ISP_CLUT_ATTR_S, CVI_ISP_SetClutAttr);

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getclutattr_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */
	GET_ATTR(ISP_CLUT_ATTR_S, stCLutAttr, CVI_ISP_GetClutAttr);

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setclutcoeff_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */
#ifdef ARCH_CV183X
	SET_ATTR(ISP_CLUT_LUT_S, CVI_ISP_SetClutCoeff);
#endif
	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getclutcoeff_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */
#ifdef ARCH_CV183X
	GET_ATTR(ISP_CLUT_LUT_S, stClutLUT, CVI_ISP_GetClutCoeff);
#endif
	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setblacklevelattr_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */
	SET_ATTR(ISP_BLACK_LEVEL_ATTR_S, CVI_ISP_SetBlackLevelAttr);

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getblacklevelattr_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */
	GET_ATTR(ISP_BLACK_LEVEL_ATTR_S, stBlackLevelAttr, CVI_ISP_GetBlackLevelAttr);

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setdemosaicattr_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */
	SET_ATTR(ISP_DEMOSAIC_ATTR_S, CVI_ISP_SetDemosaicAttr);

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getdemosaicattr_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */
	GET_ATTR(ISP_DEMOSAIC_ATTR_S, stDemosaicAttr, CVI_ISP_GetDemosaicAttr);

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setdemosaicdemoireattr_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */
	SET_ATTR(ISP_DEMOSAIC_DEMOIRE_ATTR_S, CVI_ISP_SetDemosaicDemoireAttr);

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getdemosaicdemoireattr_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */
	GET_ATTR(ISP_DEMOSAIC_DEMOIRE_ATTR_S, stDemosaicDemoireAttr, CVI_ISP_GetDemosaicDemoireAttr);

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setdemosaicfilterattr_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */
	SET_ATTR(ISP_DEMOSAIC_FILTER_ATTR_S, CVI_ISP_SetDemosaicFilterAttr);

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getdemosaicfilterattr_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */
	GET_ATTR(ISP_DEMOSAIC_FILTER_ATTR_S, stDemosaicFilterAttr, CVI_ISP_GetDemosaicFilterAttr);

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setdemosaiceeattr_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */
#ifdef ARCH_CV183X
	SET_ATTR(ISP_DEMOSAIC_EE_ATTR_S, CVI_ISP_SetDemosaicEEAttr);
#endif
	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getdemosaiceeattr_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */
#ifdef ARCH_CV183X
	GET_ATTR(ISP_DEMOSAIC_EE_ATTR_S, stDemosaicEEAttr, CVI_ISP_GetDemosaicEEAttr);
#endif
	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setsaturationattr_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */
	SET_ATTR(ISP_SATURATION_ATTR_S, CVI_ISP_SetSaturationAttr);

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getsaturationattr_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */
	GET_ATTR(ISP_SATURATION_ATTR_S, stSaturationAttr, CVI_ISP_GetSaturationAttr);

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setccmattr_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */
	SET_ATTR(ISP_CCM_ATTR_S, CVI_ISP_SetCCMAttr);

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getccmattr_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */
	GET_ATTR(ISP_CCM_ATTR_S, stCCMAttr, CVI_ISP_GetCCMAttr);

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_sethsvattr_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */
#ifdef ARCH_CV183X
	SET_ATTR(ISP_HSV_ATTR_S, CVI_ISP_SetHSVAttr);
#endif
	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_gethsvattr_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */
#ifdef ARCH_CV183X
	GET_ATTR(ISP_HSV_ATTR_S, stHSVAttr, CVI_ISP_GetHSVAttr);
#endif
	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setdpdynamicattr_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */
	SET_ATTR(ISP_DP_DYNAMIC_ATTR_S, CVI_ISP_SetDPDynamicAttr);

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getdpdynamicattr_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */
	GET_ATTR(ISP_DP_DYNAMIC_ATTR_S, stDPCDynamicAttr, CVI_ISP_GetDPDynamicAttr);

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setdpstaticattr_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */
	SET_ATTR(ISP_DP_STATIC_ATTR_S, CVI_ISP_SetDPStaticAttr);

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getdpstaticattr_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */
	GET_ATTR(ISP_DP_STATIC_ATTR_S, stDPStaticAttr, CVI_ISP_GetDPStaticAttr);

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setdpcalibrate_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */
	SET_ATTR(ISP_DP_CALIB_ATTR_S, CVI_ISP_SetDPCalibrate);

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getdpcalibrate_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */
	GET_ATTR(ISP_DP_CALIB_ATTR_S, stDPCalibAttr, CVI_ISP_GetDPCalibrate);

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setcrosstalkattr_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */
	SET_ATTR(ISP_CROSSTALK_ATTR_S, CVI_ISP_SetCrosstalkAttr);

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getcrosstalkattr_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */
	GET_ATTR(ISP_CROSSTALK_ATTR_S, stCrosstalkAttr, CVI_ISP_GetCrosstalkAttr);

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getaestatistics_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */
	GET_ATTR(ISP_AE_STATISTICS_S, stAeStat, CVI_ISP_GetAEStatistics);

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getwbstatistics_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */
	GET_ATTR(ISP_WB_STATISTICS_S, stWBStat, CVI_ISP_GetWBStatistics);

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getfocusstatistics_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */
	GET_ATTR(ISP_AF_STATISTICS_S, stAfStat, CVI_ISP_GetFocusStatistics);

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getlightboxgain_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */
	GET_ATTR(ISP_AWB_LightBox_Gain_S, stAWBLightBoxGain, CVI_ISP_GetLightboxGain);

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setfswdrattr_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */
	SET_ATTR(ISP_FSWDR_ATTR_S, CVI_ISP_SetFSWDRAttr);

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getfswdrattr_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */
	GET_ATTR(ISP_FSWDR_ATTR_S, stFSWDRAttr, CVI_ISP_GetFSWDRAttr);

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setdrcattr_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */
	SET_ATTR(ISP_DRC_ATTR_S, CVI_ISP_SetDRCAttr);

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getdrcattr_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */
	GET_ATTR(ISP_DRC_ATTR_S, stDRCAttr, CVI_ISP_GetDRCAttr);

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setsharpenattr_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */
	SET_ATTR(ISP_SHARPEN_ATTR_S, CVI_ISP_SetSharpenAttr);

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getsharpenattr_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */
	GET_ATTR(ISP_SHARPEN_ATTR_S, stSharpenAttr, CVI_ISP_GetSharpenAttr);

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setnoiseprofileattr_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */
	SET_ATTR(ISP_CMOS_NOISE_CALIBRATION_S, CVI_ISP_SetNoiseProfileAttr);

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getnoiseprofileattr_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */
	GET_ATTR(ISP_CMOS_NOISE_CALIBRATION_S, stNoiseProfileAttr, CVI_ISP_GetNoiseProfileAttr);

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setycontrastattr_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */
	SET_ATTR(ISP_YCONTRAST_ATTR_S, CVI_ISP_SetYContrastAttr);

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getycontrastattr_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */
	GET_ATTR(ISP_YCONTRAST_ATTR_S, stYContrastAttr, CVI_ISP_GetYContrastAttr);

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setdcfinfo_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */
#ifdef ARCH_CV183X
	SET_ATTR(ISP_DCF_INFO_S, CVI_ISP_SetDCFInfo);
#endif
	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getdcfinfo_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */
#ifdef ARCH_CV183X
	GET_ATTR(ISP_DCF_INFO_S, stIspDCF, CVI_ISP_GetDCFInfo);
#endif
	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_queryinnerstateinfo_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */
	GET_ATTR(ISP_INNER_STATE_INFO_S, stInnerStateInfo, CVI_ISP_QueryInnerStateInfo);

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_getvdtimeout_1_svc(RPC_VI_PIPE ViPipe, uint32_t enIspVDType, uint32_t u32MilliSec,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */
	result = CVI_ISP_GetVDTimeOut(ViPipe, enIspVDType, u32MilliSec);

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setmonoattr_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */
	SET_ATTR(ISP_MONO_ATTR_S, CVI_ISP_SetMonoAttr);

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getmonoattr_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */
	GET_ATTR(ISP_MONO_ATTR_S, stMonoAttr, CVI_ISP_GetMonoAttr);

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setdisattr_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */
	SET_ATTR(ISP_DIS_ATTR_S, CVI_ISP_SetDisAttr);

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getdisattr_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */
	GET_ATTR(ISP_DIS_ATTR_S, stDisAttr, CVI_ISP_GetDisAttr);

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setdisconfig_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */
	SET_ATTR(ISP_DIS_CONFIG_S, CVI_ISP_SetDisConfig);

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getdisconfig_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */
	GET_ATTR(ISP_DIS_CONFIG_S, stDisConfig, CVI_ISP_GetDisConfig);

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_getbinstatus_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */
#ifdef ARCH_CV183X
	result = CVI_ISP_GetBinStatus(ViPipe);
#endif
	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setvcattr_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */
	SET_ATTR(ISP_VC_ATTR_S, CVI_ISP_SetVCAttr);

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getvcattr_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */
	GET_ATTR(ISP_VC_ATTR_S, stVCAttr, CVI_ISP_GetVCAttr);

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_dumphwregistertofile_1_svc(RPC_VI_PIPE ViPipe, char *fileName,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */
	FILE *fp = NULL;

	if (fileName != NULL) {

		fp = fopen(fileName, "w");

		if (fp == NULL) {
			LOGOUT("[ERROR]: fopen %s\n", fileName);
			result = -1;
			return &result;
		}

		result = CVI_ISP_DumpHwRegisterToFile(ViPipe, fp);

		fclose(fp);

	} else {
		result = -1;
		LOGOUT("[ERROR]: fileName is NULL!!!!\n");
	}

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_dumpframerawinfotofile_1_svc(RPC_VI_PIPE ViPipe, char *fileName,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */
	FILE *fp = NULL;

	if (fileName != NULL) {

		fp = fopen(fileName, "w");

		if (fp == NULL) {
			LOGOUT("[ERROR]: fopen %s\n", fileName);
			result = -1;
			return &result;
		}

		result = CVI_ISP_DumpFrameRawInfoToFile(ViPipe, fp);

		fclose(fp);

	} else {
		result = -1;
		LOGOUT("[ERROR]: fileName is NULL!!!!\n");
	}

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_irautorunonce_1_svc(uint32_t IspDev, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */
	ISP_IR_AUTO_ATTR_S *p = NULL;
	if (stAttrData.data.data_len == sizeof(ISP_IR_AUTO_ATTR_S)) {
		p = (ISP_IR_AUTO_ATTR_S *) stAttrData.data.data_val;
		memset(&result, 0, sizeof(RPC_ISP_GET_ATTR_DATA_S));
		result.ret = CVI_ISP_IrAutoRunOnce(IspDev, p);
		result.data.data_len = sizeof(ISP_IR_AUTO_ATTR_S);
		memcpy(result.data.data_val, (uint8_t*)p, sizeof(ISP_IR_AUTO_ATTR_S));
	} else {
		result.ret = CVI_FAILURE;
		LOGOUT_ERROR();
		return NULL;
	}

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setsmartinfo_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData, uint8_t TimeOut,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */
	ISP_SMART_INFO_S *p = NULL;
	if (stAttrData.data.data_len == sizeof(ISP_SMART_INFO_S)) {
		p = (ISP_SMART_INFO_S *) stAttrData.data.data_val;
		result = CVI_ISP_SetSmartInfo(ViPipe, p, TimeOut);
	} else {
		result = CVI_FAILURE;
		LOGOUT_ERROR();
	}

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getsmartinfo_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */
	GET_ATTR(ISP_SMART_INFO_S, stSmartInfoAttr, CVI_ISP_GetSmartInfo);

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_settnrmotionadaptattr_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */
#ifdef ARCH_CV182X
	 SET_ATTR(ISP_TNR_MOTION_ADAPT_ATTR_S, CVI_ISP_SetTNRMotionAdaptAttr);
#endif

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_gettnrmotionadaptattr_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */
#ifdef ARCH_CV182X
	GET_ATTR(ISP_TNR_MOTION_ADAPT_ATTR_S, stMotionAdaptAttr, CVI_ISP_GetTNRMotionAdaptAttr);
#endif

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setclutsaturationattr_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */
#ifdef ARCH_CV182X
	SET_ATTR(ISP_CLUT_SATURATION_ATTR_S, CVI_ISP_SetClutSaturationAttr);
#endif

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getclutsaturationattr_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */
#ifdef ARCH_CV182X
	GET_ATTR(ISP_CLUT_SATURATION_ATTR_S, stClutSaturationAttr, CVI_ISP_GetClutSaturationAttr);
#endif

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getgammacurvebytype_1_svc(RPC_VI_PIPE ViPipe, uint32_t curveType,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */
#ifdef ARCH_CV182X
	memset(&punResult->stGammaCurve, 0, sizeof(ISP_GAMMA_ATTR_S));
	result.ret = CVI_ISP_GetGammaCurveByType(ViPipe,&punResult->stGammaCurve,curveType);
	result.data.data_len = sizeof(ISP_GAMMA_ATTR_S);
	result.data.data_val = (uint8_t *)&punResult->stGammaCurve;
#endif

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setpresharpenattr_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */
#ifdef ARCH_CV182X
	SET_ATTR(ISP_PRESHARPEN_ATTR_S, CVI_ISP_SetPreSharpenAttr);
#endif

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getpresharpenattr_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */
#ifdef ARCH_CV182X
	GET_ATTR(ISP_PRESHARPEN_ATTR_S, stPreSharpenAttr, CVI_ISP_GetPreSharpenAttr);
#endif

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setrgbcacattr_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */
#ifdef ARCH_CV182X
	SET_ATTR(ISP_RGBCAC_ATTR_S, CVI_ISP_SetRGBCACAttr);
#endif

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getrgbcacattr_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */
#ifdef ARCH_CV182X
	GET_ATTR(ISP_RGBCAC_ATTR_S, stRGBCACAttr, CVI_ISP_GetRGBCACAttr);
#endif

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setcnrmotionnrattr_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */
#ifdef ARCH_CV182X
	SET_ATTR(ISP_CNR_MOTION_NR_ATTR_S, CVI_ISP_SetCNRMotionNRAttr);
#endif

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getcnrmotionnrattr_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */
#ifdef ARCH_CV182X
	GET_ATTR(ISP_CNR_MOTION_NR_ATTR_S, stCNRMotionNRAttr, CVI_ISP_GetCNRMotionNRAttr);
#endif

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setccmsaturationattr_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */
#ifdef ARCH_CV182X
	SET_ATTR(ISP_CCM_SATURATION_ATTR_S, CVI_ISP_SetCCMSaturationAttr);
#endif

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getccmsaturationattr_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */
#ifdef ARCH_CV182X
	GET_ATTR(ISP_CCM_SATURATION_ATTR_S, stCCMSaturationAttr, CVI_ISP_GetCCMSaturationAttr);
#endif

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setcaattr_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */
#ifdef ARCH_CV182X
	SET_ATTR(ISP_CA_ATTR_S, CVI_ISP_SetCAAttr);
#endif

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getcaattr_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */
#ifdef ARCH_CV182X
	GET_ATTR(ISP_CA_ATTR_S, stCAAttr, CVI_ISP_GetCAAttr);
#endif

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setcscattr_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */
#ifdef ARCH_CV182X
	SET_ATTR(ISP_CSC_ATTR_S, CVI_ISP_SetCSCAttr);
#endif

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getcscattr_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */
#ifdef ARCH_CV182X
	GET_ATTR(ISP_CSC_ATTR_S, stCSCAttr, CVI_ISP_GetCSCAttr);
#endif

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setexposureattr_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */
	SET_ATTR(ISP_EXPOSURE_ATTR_S, CVI_ISP_SetExposureAttr);

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getexposureattr_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */
	GET_ATTR(ISP_EXPOSURE_ATTR_S, stExpAttr, CVI_ISP_GetExposureAttr);

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_queryexposureinfo_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */
	GET_ATTR(ISP_EXP_INFO_S, stExpInfo, CVI_ISP_QueryExposureInfo);

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setwdrexposureattr_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */
	SET_ATTR(ISP_WDR_EXPOSURE_ATTR_S, CVI_ISP_SetWDRExposureAttr);

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getwdrexposureattr_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */
	GET_ATTR(ISP_WDR_EXPOSURE_ATTR_S, stWDRExpAttr, CVI_ISP_GetWDRExposureAttr);

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setaerouteattr_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */
	SET_ATTR(ISP_AE_ROUTE_S, CVI_ISP_SetAERouteAttr);

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getaerouteattr_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */
	GET_ATTR(ISP_AE_ROUTE_S, stAERouteAttr, CVI_ISP_GetAERouteAttr);

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setaerouteattrex_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */
	SET_ATTR(ISP_AE_ROUTE_EX_S, CVI_ISP_SetAERouteAttrEx);

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getaerouteattrex_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */
	GET_ATTR(ISP_AE_ROUTE_EX_S, stAERouteAttrEx, CVI_ISP_GetAERouteAttrEx);

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_aebracketingstart_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */
	result = CVI_ISP_AEBracketingStart(ViPipe);

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_aebracketingsetexpsoure_1_svc(RPC_VI_PIPE ViPipe, int leEvX10, int seEvX10,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */
	result = CVI_ISP_AEBracketingSetExpsoure(ViPipe, leEvX10, seEvX10);

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_aebracketingfinish_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */
	result = CVI_ISP_AEBracketingFinish(ViPipe);

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_aebracketingsetsimple_1_svc(uint8_t enable,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */
	result = CVI_ISP_AEBracketingSetSimple(enable);

	return &result;
}
RPC_CVI_S32 *
rpc_cvi_isp_setaestatisticsconfig_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */
	SET_ATTR(ISP_AE_STATISTICS_CFG_S, CVI_ISP_SetAEStatisticsConfig);

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getaestatisticsconfig_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */
	GET_ATTR(ISP_AE_STATISTICS_CFG_S, stAeStatisticsCfg, CVI_ISP_GetAEStatisticsConfig);

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setantiflicker_1_svc(RPC_VI_PIPE ViPipe, uint8_t enable, uint8_t frequency,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */
	result = CVI_ISP_SetAntiFlicker(ViPipe, enable, frequency);

	return &result;
}

uint32_t *
rpc_cvi_isp_getantiflicker_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static uint32_t  result;

	/*
	 * insert server code here
	 */
	bool enable;
	uint8_t freq;

	CVI_ISP_GetAntiFlicker(ViPipe, &enable, &freq);

	result = 0x00;
	result |= ((uint32_t)enable << 8);
	result |= freq;

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setwdrleonly_1_svc(RPC_VI_PIPE ViPipe, uint8_t wdrLEOnly,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */
	result = CVI_ISP_SetWDRLEOnly(ViPipe, wdrLEOnly);

	return &result;
}

uint32_t *
rpc_cvi_isp_getframeid_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static uint32_t  result;

	/*
	 * insert server code here
	 */
	CVI_ISP_GetFrameID(ViPipe, &result);

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setaelogpath_1_svc(char *fileName,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */
	result = CVI_ISP_SetAELogPath(fileName);

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getaelogpath_1_svc(int pathSize,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */
	result.ret = CVI_ISP_GetAELogPath((char *) punResult->stBuffer.buffer,pathSize);
	result.data.data_len = pathSize;
	result.data.data_val = punResult->stBuffer.buffer;

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setaelogname_1_svc(char *fileName,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */
	result = CVI_ISP_SetAELogName(fileName);

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getaelogname_1_svc(int nameSize,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */
	result.ret = CVI_ISP_GetAELogName((char *) punResult->stBuffer.buffer,nameSize);
	result.data.data_len = nameSize;
	result.data.data_val = punResult->stBuffer.buffer;

	return &result;
}

float *
rpc_cvi_isp_queryfps_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static float  result;

	/*
	 * insert server code here
	 */
	CVI_ISP_QueryFps(ViPipe, &result);

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getaelogbuf_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */
	memset(&punResult->stBuffer, 0, sizeof(ISP_COMMON_BUFFER_S));
	result.ret = CVI_ISP_GetAELogBuf(ViPipe, punResult->stBuffer.buffer, __BUFFER_SIZE);
	result.data.data_len = __BUFFER_SIZE;
	result.data.data_val = punResult->stBuffer.buffer;

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getaelogbufsize_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */
	memset(&punResult->stBuffer, 0, sizeof(ISP_COMMON_BUFFER_S));
	result.ret = CVI_ISP_GetAELogBufSize(ViPipe, (CVI_U32 *)punResult->stBuffer.buffer);
	result.data.data_len = sizeof(CVI_S32);
	result.data.data_val = punResult->stBuffer.buffer;

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getaebinbuf_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */
	memset(&punResult->stBuffer, 0, sizeof(ISP_COMMON_BUFFER_S));
	result.ret = CVI_ISP_GetAEBinBuf(ViPipe, punResult->stBuffer.buffer, __BUFFER_SIZE);
	result.data.data_len = __BUFFER_SIZE;
	result.data.data_val = punResult->stBuffer.buffer;

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getaebinbufsize_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */
	memset(&punResult->stBuffer, 0, sizeof(ISP_COMMON_BUFFER_S));
	result.ret = CVI_ISP_GetAEBinBufSize(ViPipe, (CVI_U32 *)punResult->stBuffer.buffer);
	result.data.data_len = sizeof(CVI_S32);
	result.data.data_val = punResult->stBuffer.buffer;

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getcurrentlvx100_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */
	memset(&punResult->stBuffer, 0, sizeof(ISP_COMMON_BUFFER_S));
	result.ret = CVI_ISP_GetCurrentLvX100(ViPipe, (CVI_S16 *)punResult->stBuffer.buffer);
	result.data.data_len = sizeof(CVI_S16);
	result.data.data_val = punResult->stBuffer.buffer;

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setfastbootexposure_1_svc(RPC_VI_PIPE ViPipe, uint32_t expLine, uint32_t again, uint32_t dgain, uint32_t ispdgain,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */
	result = CVI_ISP_SetFastBootExposure(ViPipe, expLine, again, dgain, ispdgain);

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setsmartexposureattr_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */
	SET_ATTR(ISP_SMART_EXPOSURE_ATTR_S, CVI_ISP_SetSmartExposureAttr);

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getsmartexposureattr_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */
	GET_ATTR(ISP_SMART_EXPOSURE_ATTR_S, stSmartExpAttr, CVI_ISP_GetSmartExposureAttr);

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setwbattr_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */
	SET_ATTR(ISP_WB_ATTR_S, CVI_ISP_SetWBAttr);

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getwbattr_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */
	GET_ATTR(ISP_WB_ATTR_S, stWBAttr, CVI_ISP_GetWBAttr);

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setawbattrex_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */
	SET_ATTR(ISP_AWB_ATTR_EX_S, CVI_ISP_SetAWBAttrEx);

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getawbattrex_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */
	GET_ATTR(ISP_AWB_ATTR_EX_S, stAWBAttrEx, CVI_ISP_GetAWBAttrEx);

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_querywbinfo_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */
	GET_ATTR(ISP_WB_INFO_S, stWBInfo, CVI_ISP_QueryWBInfo);

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setwbcalibration_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */
	SET_ATTR(ISP_AWB_Calibration_Gain_S, CVI_ISP_SetWBCalibration);

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getwbcalibration_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */
	GET_ATTR(ISP_AWB_Calibration_Gain_S, stWBCalib, CVI_ISP_GetWBCalibration);

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setwbcalibrationex_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */
	SET_ATTR(ISP_AWB_Calibration_Gain_S_EX, CVI_ISP_SetWBCalibrationEx);

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getwbcalibrationex_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */
	GET_ATTR(ISP_AWB_Calibration_Gain_S_EX, stWBCalibEx, CVI_ISP_GetWBCalibrationEx);

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setawbwinstatictics_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */
	SET_ATTR(ISP_WB_STATISTICS_CFG_S, CVI_ISP_SetAWBWinStatictics);

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getawbwinstatictics_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */
	GET_ATTR(ISP_WB_STATISTICS_CFG_S, stAwbWinCfg, CVI_ISP_GetAWBWinStatictics);

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getawbsnaplogbuf_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */
	memset(&punResult->stBuffer, 0, sizeof(ISP_COMMON_BUFFER_S));
	result.ret = CVI_ISP_GetAWBSnapLogBuf(ViPipe, punResult->stBuffer.buffer, __BUFFER_SIZE);
	result.data.data_len = __BUFFER_SIZE;
	result.data.data_val = punResult->stBuffer.buffer;

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getawbdbgbinbuf_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */
	memset(&punResult->stBuffer, 0, sizeof(ISP_COMMON_BUFFER_S));
	result.ret = CVI_ISP_GetAWBDbgBinBuf(ViPipe, punResult->stBuffer.buffer, __BUFFER_SIZE);
	result.data.data_len = __BUFFER_SIZE;
	result.data.data_val = punResult->stBuffer.buffer;

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_getawbdbgbinsize_1_svc(struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */
	result = CVI_ISP_GetAWBDbgBinSize();

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getawbcurve_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */
	GET_ATTR(ISP_WB_CURVE_S, shWBCurve, CVI_ISP_GetAWBCurve);

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setawblogpath_1_svc(char *fileName,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */
	result = CVI_ISP_SetAWBLogPath(fileName);

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setawblogname_1_svc(char *fileName,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */
	result = CVI_ISP_SetAWBLogName(fileName);

	return &result;
}

#pragma GCC diagnostic pop

