export V4L2_ISP_DEV_INSTALL=/opt/sophon/sophon-soc-libisp-dev_1.0.0
export V4L2_ISP_DEV_LIB=${V4L2_ISP_DEV_INSTALL}/lib
export V4L2_ISP_DEV_BIN=${V4L2_ISP_DEV_INSTALL}/bin
export V4L2_ISP_DEV_DOC=${V4L2_ISP_DEV_INSTALL}/doc
export V4L2_ISP_DEV_DATA=${V4L2_ISP_DEV_INSTALL}/data
export V4L2_ISP_DEV_SRC=${V4L2_ISP_DEV_INSTALL}/src
export V4L2_ISP_DEV_SAMPLE=${V4L2_ISP_DEV_INSTALL}/sample

export PKG_CONFIG_PATH=${V4L2_ISP_DEV_LIB}/pkgconfig:$PKG_CONFIG_PATH
