/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunused-variable"

#include "isp_rpc.h"

bool_t
xdr_RPC_CVI_S32 (XDR *xdrs, RPC_CVI_S32 *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_RPC_VI_PIPE (XDR *xdrs, RPC_VI_PIPE *objp)
{
	register int32_t *buf;

	 if (!xdr_uint32_t (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_RPC_ISP_SET_ATTR_DATA_S (XDR *xdrs, RPC_ISP_SET_ATTR_DATA_S *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->data.data_val, (u_int *) &objp->data.data_len, ~0,
		sizeof (uint8_t), (xdrproc_t) xdr_uint8_t))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_RPC_ISP_GET_ATTR_DATA_S (XDR *xdrs, RPC_ISP_GET_ATTR_DATA_S *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->ret))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->data.data_val, (u_int *) &objp->data.data_len, ~0,
		sizeof (uint8_t), (xdrproc_t) xdr_uint8_t))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cvi_isp_setpubattr_1_argument (XDR *xdrs, rpc_cvi_isp_setpubattr_1_argument *objp)
{
	 if (!xdr_RPC_VI_PIPE (xdrs, &objp->ViPipe))
		 return FALSE;
	 if (!xdr_RPC_ISP_SET_ATTR_DATA_S (xdrs, &objp->stAttrData))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cvi_isp_setctrlparam_1_argument (XDR *xdrs, rpc_cvi_isp_setctrlparam_1_argument *objp)
{
	 if (!xdr_RPC_VI_PIPE (xdrs, &objp->ViPipe))
		 return FALSE;
	 if (!xdr_RPC_ISP_SET_ATTR_DATA_S (xdrs, &objp->stAttrData))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cvi_isp_setfmwstate_1_argument (XDR *xdrs, rpc_cvi_isp_setfmwstate_1_argument *objp)
{
	 if (!xdr_RPC_VI_PIPE (xdrs, &objp->ViPipe))
		 return FALSE;
	 if (!xdr_uint32_t (xdrs, &objp->enState))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cvi_isp_setmodulecontrol_1_argument (XDR *xdrs, rpc_cvi_isp_setmodulecontrol_1_argument *objp)
{
	 if (!xdr_RPC_VI_PIPE (xdrs, &objp->ViPipe))
		 return FALSE;
	 if (!xdr_RPC_ISP_SET_ATTR_DATA_S (xdrs, &objp->stAttrData))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cvi_isp_setregister_1_argument (XDR *xdrs, rpc_cvi_isp_setregister_1_argument *objp)
{
	 if (!xdr_RPC_VI_PIPE (xdrs, &objp->ViPipe))
		 return FALSE;
	 if (!xdr_uint32_t (xdrs, &objp->u32Addr))
		 return FALSE;
	 if (!xdr_uint32_t (xdrs, &objp->u32Value))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cvi_isp_getregister_1_argument (XDR *xdrs, rpc_cvi_isp_getregister_1_argument *objp)
{
	 if (!xdr_RPC_VI_PIPE (xdrs, &objp->ViPipe))
		 return FALSE;
	 if (!xdr_uint32_t (xdrs, &objp->u32Addr))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cvi_isp_setcolortoneattr_1_argument (XDR *xdrs, rpc_cvi_isp_setcolortoneattr_1_argument *objp)
{
	 if (!xdr_RPC_VI_PIPE (xdrs, &objp->ViPipe))
		 return FALSE;
	 if (!xdr_RPC_ISP_SET_ATTR_DATA_S (xdrs, &objp->stAttrData))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cvi_isp_setdehazeattr_1_argument (XDR *xdrs, rpc_cvi_isp_setdehazeattr_1_argument *objp)
{
	 if (!xdr_RPC_VI_PIPE (xdrs, &objp->ViPipe))
		 return FALSE;
	 if (!xdr_RPC_ISP_SET_ATTR_DATA_S (xdrs, &objp->stAttrData))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cvi_isp_setgammaattr_1_argument (XDR *xdrs, rpc_cvi_isp_setgammaattr_1_argument *objp)
{
	 if (!xdr_RPC_VI_PIPE (xdrs, &objp->ViPipe))
		 return FALSE;
	 if (!xdr_RPC_ISP_SET_ATTR_DATA_S (xdrs, &objp->stAttrData))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cvi_isp_setgammacurvetype_1_argument (XDR *xdrs, rpc_cvi_isp_setgammacurvetype_1_argument *objp)
{
	 if (!xdr_RPC_VI_PIPE (xdrs, &objp->ViPipe))
		 return FALSE;
	 if (!xdr_uint32_t (xdrs, &objp->curveType))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cvi_isp_setautogammaattr_1_argument (XDR *xdrs, rpc_cvi_isp_setautogammaattr_1_argument *objp)
{
	 if (!xdr_RPC_VI_PIPE (xdrs, &objp->ViPipe))
		 return FALSE;
	 if (!xdr_RPC_ISP_SET_ATTR_DATA_S (xdrs, &objp->stAttrData))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cvi_isp_setstatisticsconfig_1_argument (XDR *xdrs, rpc_cvi_isp_setstatisticsconfig_1_argument *objp)
{
	 if (!xdr_RPC_VI_PIPE (xdrs, &objp->ViPipe))
		 return FALSE;
	 if (!xdr_RPC_ISP_SET_ATTR_DATA_S (xdrs, &objp->stAttrData))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cvi_isp_setnrattr_1_argument (XDR *xdrs, rpc_cvi_isp_setnrattr_1_argument *objp)
{
	 if (!xdr_RPC_VI_PIPE (xdrs, &objp->ViPipe))
		 return FALSE;
	 if (!xdr_RPC_ISP_SET_ATTR_DATA_S (xdrs, &objp->stAttrData))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cvi_isp_setnrfilterattr_1_argument (XDR *xdrs, rpc_cvi_isp_setnrfilterattr_1_argument *objp)
{
	 if (!xdr_RPC_VI_PIPE (xdrs, &objp->ViPipe))
		 return FALSE;
	 if (!xdr_RPC_ISP_SET_ATTR_DATA_S (xdrs, &objp->stAttrData))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cvi_isp_setrlscattr_1_argument (XDR *xdrs, rpc_cvi_isp_setrlscattr_1_argument *objp)
{
	 if (!xdr_RPC_VI_PIPE (xdrs, &objp->ViPipe))
		 return FALSE;
	 if (!xdr_RPC_ISP_SET_ATTR_DATA_S (xdrs, &objp->stAttrData))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cvi_isp_setynrattr_1_argument (XDR *xdrs, rpc_cvi_isp_setynrattr_1_argument *objp)
{
	 if (!xdr_RPC_VI_PIPE (xdrs, &objp->ViPipe))
		 return FALSE;
	 if (!xdr_RPC_ISP_SET_ATTR_DATA_S (xdrs, &objp->stAttrData))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cvi_isp_setynrmotionnrattr_1_argument (XDR *xdrs, rpc_cvi_isp_setynrmotionnrattr_1_argument *objp)
{
	 if (!xdr_RPC_VI_PIPE (xdrs, &objp->ViPipe))
		 return FALSE;
	 if (!xdr_RPC_ISP_SET_ATTR_DATA_S (xdrs, &objp->stAttrData))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cvi_isp_setynrfilterattr_1_argument (XDR *xdrs, rpc_cvi_isp_setynrfilterattr_1_argument *objp)
{
	 if (!xdr_RPC_VI_PIPE (xdrs, &objp->ViPipe))
		 return FALSE;
	 if (!xdr_RPC_ISP_SET_ATTR_DATA_S (xdrs, &objp->stAttrData))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cvi_isp_setcnrattr_1_argument (XDR *xdrs, rpc_cvi_isp_setcnrattr_1_argument *objp)
{
	 if (!xdr_RPC_VI_PIPE (xdrs, &objp->ViPipe))
		 return FALSE;
	 if (!xdr_RPC_ISP_SET_ATTR_DATA_S (xdrs, &objp->stAttrData))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cvi_isp_setcacattr_1_argument (XDR *xdrs, rpc_cvi_isp_setcacattr_1_argument *objp)
{
	 if (!xdr_RPC_VI_PIPE (xdrs, &objp->ViPipe))
		 return FALSE;
	 if (!xdr_RPC_ISP_SET_ATTR_DATA_S (xdrs, &objp->stAttrData))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cvi_isp_setdciattr_1_argument (XDR *xdrs, rpc_cvi_isp_setdciattr_1_argument *objp)
{
	 if (!xdr_RPC_VI_PIPE (xdrs, &objp->ViPipe))
		 return FALSE;
	 if (!xdr_RPC_ISP_SET_ATTR_DATA_S (xdrs, &objp->stAttrData))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cvi_isp_setmeshshadingattr_1_argument (XDR *xdrs, rpc_cvi_isp_setmeshshadingattr_1_argument *objp)
{
	 if (!xdr_RPC_VI_PIPE (xdrs, &objp->ViPipe))
		 return FALSE;
	 if (!xdr_RPC_ISP_SET_ATTR_DATA_S (xdrs, &objp->stAttrData))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cvi_isp_setmeshshadinggainlutattr_1_argument (XDR *xdrs, rpc_cvi_isp_setmeshshadinggainlutattr_1_argument *objp)
{
	 if (!xdr_RPC_VI_PIPE (xdrs, &objp->ViPipe))
		 return FALSE;
	 if (!xdr_RPC_ISP_SET_ATTR_DATA_S (xdrs, &objp->stAttrData))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cvi_isp_setradialshadingattr_1_argument (XDR *xdrs, rpc_cvi_isp_setradialshadingattr_1_argument *objp)
{
	 if (!xdr_RPC_VI_PIPE (xdrs, &objp->ViPipe))
		 return FALSE;
	 if (!xdr_RPC_ISP_SET_ATTR_DATA_S (xdrs, &objp->stAttrData))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cvi_isp_setradialshadinggainlutattr_1_argument (XDR *xdrs, rpc_cvi_isp_setradialshadinggainlutattr_1_argument *objp)
{
	 if (!xdr_RPC_VI_PIPE (xdrs, &objp->ViPipe))
		 return FALSE;
	 if (!xdr_RPC_ISP_SET_ATTR_DATA_S (xdrs, &objp->stAttrData))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cvi_isp_settnrattr_1_argument (XDR *xdrs, rpc_cvi_isp_settnrattr_1_argument *objp)
{
	 if (!xdr_RPC_VI_PIPE (xdrs, &objp->ViPipe))
		 return FALSE;
	 if (!xdr_RPC_ISP_SET_ATTR_DATA_S (xdrs, &objp->stAttrData))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cvi_isp_settnrnoisemodelattr_1_argument (XDR *xdrs, rpc_cvi_isp_settnrnoisemodelattr_1_argument *objp)
{
	 if (!xdr_RPC_VI_PIPE (xdrs, &objp->ViPipe))
		 return FALSE;
	 if (!xdr_RPC_ISP_SET_ATTR_DATA_S (xdrs, &objp->stAttrData))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cvi_isp_settnrlumamotionattr_1_argument (XDR *xdrs, rpc_cvi_isp_settnrlumamotionattr_1_argument *objp)
{
	 if (!xdr_RPC_VI_PIPE (xdrs, &objp->ViPipe))
		 return FALSE;
	 if (!xdr_RPC_ISP_SET_ATTR_DATA_S (xdrs, &objp->stAttrData))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cvi_isp_settnrghostattr_1_argument (XDR *xdrs, rpc_cvi_isp_settnrghostattr_1_argument *objp)
{
	 if (!xdr_RPC_VI_PIPE (xdrs, &objp->ViPipe))
		 return FALSE;
	 if (!xdr_RPC_ISP_SET_ATTR_DATA_S (xdrs, &objp->stAttrData))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cvi_isp_settnrmtprtattr_1_argument (XDR *xdrs, rpc_cvi_isp_settnrmtprtattr_1_argument *objp)
{
	 if (!xdr_RPC_VI_PIPE (xdrs, &objp->ViPipe))
		 return FALSE;
	 if (!xdr_RPC_ISP_SET_ATTR_DATA_S (xdrs, &objp->stAttrData))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cvi_isp_setclutattr_1_argument (XDR *xdrs, rpc_cvi_isp_setclutattr_1_argument *objp)
{
	 if (!xdr_RPC_VI_PIPE (xdrs, &objp->ViPipe))
		 return FALSE;
	 if (!xdr_RPC_ISP_SET_ATTR_DATA_S (xdrs, &objp->stAttrData))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cvi_isp_setclutcoeff_1_argument (XDR *xdrs, rpc_cvi_isp_setclutcoeff_1_argument *objp)
{
	 if (!xdr_RPC_VI_PIPE (xdrs, &objp->ViPipe))
		 return FALSE;
	 if (!xdr_RPC_ISP_SET_ATTR_DATA_S (xdrs, &objp->stAttrData))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cvi_isp_setblacklevelattr_1_argument (XDR *xdrs, rpc_cvi_isp_setblacklevelattr_1_argument *objp)
{
	 if (!xdr_RPC_VI_PIPE (xdrs, &objp->ViPipe))
		 return FALSE;
	 if (!xdr_RPC_ISP_SET_ATTR_DATA_S (xdrs, &objp->stAttrData))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cvi_isp_setdemosaicattr_1_argument (XDR *xdrs, rpc_cvi_isp_setdemosaicattr_1_argument *objp)
{
	 if (!xdr_RPC_VI_PIPE (xdrs, &objp->ViPipe))
		 return FALSE;
	 if (!xdr_RPC_ISP_SET_ATTR_DATA_S (xdrs, &objp->stAttrData))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cvi_isp_setdemosaicdemoireattr_1_argument (XDR *xdrs, rpc_cvi_isp_setdemosaicdemoireattr_1_argument *objp)
{
	 if (!xdr_RPC_VI_PIPE (xdrs, &objp->ViPipe))
		 return FALSE;
	 if (!xdr_RPC_ISP_SET_ATTR_DATA_S (xdrs, &objp->stAttrData))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cvi_isp_setdemosaicfilterattr_1_argument (XDR *xdrs, rpc_cvi_isp_setdemosaicfilterattr_1_argument *objp)
{
	 if (!xdr_RPC_VI_PIPE (xdrs, &objp->ViPipe))
		 return FALSE;
	 if (!xdr_RPC_ISP_SET_ATTR_DATA_S (xdrs, &objp->stAttrData))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cvi_isp_setdemosaiceeattr_1_argument (XDR *xdrs, rpc_cvi_isp_setdemosaiceeattr_1_argument *objp)
{
	 if (!xdr_RPC_VI_PIPE (xdrs, &objp->ViPipe))
		 return FALSE;
	 if (!xdr_RPC_ISP_SET_ATTR_DATA_S (xdrs, &objp->stAttrData))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cvi_isp_setsaturationattr_1_argument (XDR *xdrs, rpc_cvi_isp_setsaturationattr_1_argument *objp)
{
	 if (!xdr_RPC_VI_PIPE (xdrs, &objp->ViPipe))
		 return FALSE;
	 if (!xdr_RPC_ISP_SET_ATTR_DATA_S (xdrs, &objp->stAttrData))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cvi_isp_setccmattr_1_argument (XDR *xdrs, rpc_cvi_isp_setccmattr_1_argument *objp)
{
	 if (!xdr_RPC_VI_PIPE (xdrs, &objp->ViPipe))
		 return FALSE;
	 if (!xdr_RPC_ISP_SET_ATTR_DATA_S (xdrs, &objp->stAttrData))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cvi_isp_sethsvattr_1_argument (XDR *xdrs, rpc_cvi_isp_sethsvattr_1_argument *objp)
{
	 if (!xdr_RPC_VI_PIPE (xdrs, &objp->ViPipe))
		 return FALSE;
	 if (!xdr_RPC_ISP_SET_ATTR_DATA_S (xdrs, &objp->stAttrData))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cvi_isp_setdpdynamicattr_1_argument (XDR *xdrs, rpc_cvi_isp_setdpdynamicattr_1_argument *objp)
{
	 if (!xdr_RPC_VI_PIPE (xdrs, &objp->ViPipe))
		 return FALSE;
	 if (!xdr_RPC_ISP_SET_ATTR_DATA_S (xdrs, &objp->stAttrData))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cvi_isp_setdpstaticattr_1_argument (XDR *xdrs, rpc_cvi_isp_setdpstaticattr_1_argument *objp)
{
	 if (!xdr_RPC_VI_PIPE (xdrs, &objp->ViPipe))
		 return FALSE;
	 if (!xdr_RPC_ISP_SET_ATTR_DATA_S (xdrs, &objp->stAttrData))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cvi_isp_setdpcalibrate_1_argument (XDR *xdrs, rpc_cvi_isp_setdpcalibrate_1_argument *objp)
{
	 if (!xdr_RPC_VI_PIPE (xdrs, &objp->ViPipe))
		 return FALSE;
	 if (!xdr_RPC_ISP_SET_ATTR_DATA_S (xdrs, &objp->stAttrData))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cvi_isp_setcrosstalkattr_1_argument (XDR *xdrs, rpc_cvi_isp_setcrosstalkattr_1_argument *objp)
{
	 if (!xdr_RPC_VI_PIPE (xdrs, &objp->ViPipe))
		 return FALSE;
	 if (!xdr_RPC_ISP_SET_ATTR_DATA_S (xdrs, &objp->stAttrData))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cvi_isp_setfswdrattr_1_argument (XDR *xdrs, rpc_cvi_isp_setfswdrattr_1_argument *objp)
{
	 if (!xdr_RPC_VI_PIPE (xdrs, &objp->ViPipe))
		 return FALSE;
	 if (!xdr_RPC_ISP_SET_ATTR_DATA_S (xdrs, &objp->stAttrData))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cvi_isp_setdrcattr_1_argument (XDR *xdrs, rpc_cvi_isp_setdrcattr_1_argument *objp)
{
	 if (!xdr_RPC_VI_PIPE (xdrs, &objp->ViPipe))
		 return FALSE;
	 if (!xdr_RPC_ISP_SET_ATTR_DATA_S (xdrs, &objp->stAttrData))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cvi_isp_setsharpenattr_1_argument (XDR *xdrs, rpc_cvi_isp_setsharpenattr_1_argument *objp)
{
	 if (!xdr_RPC_VI_PIPE (xdrs, &objp->ViPipe))
		 return FALSE;
	 if (!xdr_RPC_ISP_SET_ATTR_DATA_S (xdrs, &objp->stAttrData))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cvi_isp_setnoiseprofileattr_1_argument (XDR *xdrs, rpc_cvi_isp_setnoiseprofileattr_1_argument *objp)
{
	 if (!xdr_RPC_VI_PIPE (xdrs, &objp->ViPipe))
		 return FALSE;
	 if (!xdr_RPC_ISP_SET_ATTR_DATA_S (xdrs, &objp->stAttrData))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cvi_isp_setycontrastattr_1_argument (XDR *xdrs, rpc_cvi_isp_setycontrastattr_1_argument *objp)
{
	 if (!xdr_RPC_VI_PIPE (xdrs, &objp->ViPipe))
		 return FALSE;
	 if (!xdr_RPC_ISP_SET_ATTR_DATA_S (xdrs, &objp->stAttrData))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cvi_isp_setdcfinfo_1_argument (XDR *xdrs, rpc_cvi_isp_setdcfinfo_1_argument *objp)
{
	 if (!xdr_RPC_VI_PIPE (xdrs, &objp->ViPipe))
		 return FALSE;
	 if (!xdr_RPC_ISP_SET_ATTR_DATA_S (xdrs, &objp->stAttrData))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cvi_isp_getvdtimeout_1_argument (XDR *xdrs, rpc_cvi_isp_getvdtimeout_1_argument *objp)
{
	 if (!xdr_RPC_VI_PIPE (xdrs, &objp->ViPipe))
		 return FALSE;
	 if (!xdr_uint32_t (xdrs, &objp->enIspVDType))
		 return FALSE;
	 if (!xdr_uint32_t (xdrs, &objp->u32MilliSec))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cvi_isp_setmonoattr_1_argument (XDR *xdrs, rpc_cvi_isp_setmonoattr_1_argument *objp)
{
	 if (!xdr_RPC_VI_PIPE (xdrs, &objp->ViPipe))
		 return FALSE;
	 if (!xdr_RPC_ISP_SET_ATTR_DATA_S (xdrs, &objp->stAttrData))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cvi_isp_setdisattr_1_argument (XDR *xdrs, rpc_cvi_isp_setdisattr_1_argument *objp)
{
	 if (!xdr_RPC_VI_PIPE (xdrs, &objp->ViPipe))
		 return FALSE;
	 if (!xdr_RPC_ISP_SET_ATTR_DATA_S (xdrs, &objp->stAttrData))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cvi_isp_setdisconfig_1_argument (XDR *xdrs, rpc_cvi_isp_setdisconfig_1_argument *objp)
{
	 if (!xdr_RPC_VI_PIPE (xdrs, &objp->ViPipe))
		 return FALSE;
	 if (!xdr_RPC_ISP_SET_ATTR_DATA_S (xdrs, &objp->stAttrData))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cvi_isp_setvcattr_1_argument (XDR *xdrs, rpc_cvi_isp_setvcattr_1_argument *objp)
{
	 if (!xdr_RPC_VI_PIPE (xdrs, &objp->ViPipe))
		 return FALSE;
	 if (!xdr_RPC_ISP_SET_ATTR_DATA_S (xdrs, &objp->stAttrData))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cvi_isp_dumphwregistertofile_1_argument (XDR *xdrs, rpc_cvi_isp_dumphwregistertofile_1_argument *objp)
{
	 if (!xdr_RPC_VI_PIPE (xdrs, &objp->ViPipe))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->fileName, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cvi_isp_dumpframerawinfotofile_1_argument (XDR *xdrs, rpc_cvi_isp_dumpframerawinfotofile_1_argument *objp)
{
	 if (!xdr_RPC_VI_PIPE (xdrs, &objp->ViPipe))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->fileName, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cvi_isp_irautorunonce_1_argument (XDR *xdrs, rpc_cvi_isp_irautorunonce_1_argument *objp)
{
	 if (!xdr_uint32_t (xdrs, &objp->IspDev))
		 return FALSE;
	 if (!xdr_RPC_ISP_SET_ATTR_DATA_S (xdrs, &objp->stAttrData))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cvi_isp_setsmartinfo_1_argument (XDR *xdrs, rpc_cvi_isp_setsmartinfo_1_argument *objp)
{
	 if (!xdr_RPC_VI_PIPE (xdrs, &objp->ViPipe))
		 return FALSE;
	 if (!xdr_RPC_ISP_SET_ATTR_DATA_S (xdrs, &objp->stAttrData))
		 return FALSE;
	 if (!xdr_uint8_t (xdrs, &objp->TimeOut))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cvi_isp_settnrmotionadaptattr_1_argument (XDR *xdrs, rpc_cvi_isp_settnrmotionadaptattr_1_argument *objp)
{
	 if (!xdr_RPC_VI_PIPE (xdrs, &objp->ViPipe))
		 return FALSE;
	 if (!xdr_RPC_ISP_SET_ATTR_DATA_S (xdrs, &objp->stAttrData))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cvi_isp_setclutsaturationattr_1_argument (XDR *xdrs, rpc_cvi_isp_setclutsaturationattr_1_argument *objp)
{
	 if (!xdr_RPC_VI_PIPE (xdrs, &objp->ViPipe))
		 return FALSE;
	 if (!xdr_RPC_ISP_SET_ATTR_DATA_S (xdrs, &objp->stAttrData))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cvi_isp_getgammacurvebytype_1_argument (XDR *xdrs, rpc_cvi_isp_getgammacurvebytype_1_argument *objp)
{
	 if (!xdr_RPC_VI_PIPE (xdrs, &objp->ViPipe))
		 return FALSE;
	 if (!xdr_uint32_t (xdrs, &objp->curveType))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cvi_isp_setpresharpenattr_1_argument (XDR *xdrs, rpc_cvi_isp_setpresharpenattr_1_argument *objp)
{
	 if (!xdr_RPC_VI_PIPE (xdrs, &objp->ViPipe))
		 return FALSE;
	 if (!xdr_RPC_ISP_SET_ATTR_DATA_S (xdrs, &objp->stAttrData))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cvi_isp_setrgbcacattr_1_argument (XDR *xdrs, rpc_cvi_isp_setrgbcacattr_1_argument *objp)
{
	 if (!xdr_RPC_VI_PIPE (xdrs, &objp->ViPipe))
		 return FALSE;
	 if (!xdr_RPC_ISP_SET_ATTR_DATA_S (xdrs, &objp->stAttrData))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cvi_isp_setcnrmotionnrattr_1_argument (XDR *xdrs, rpc_cvi_isp_setcnrmotionnrattr_1_argument *objp)
{
	 if (!xdr_RPC_VI_PIPE (xdrs, &objp->ViPipe))
		 return FALSE;
	 if (!xdr_RPC_ISP_SET_ATTR_DATA_S (xdrs, &objp->stAttrData))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cvi_isp_setccmsaturationattr_1_argument (XDR *xdrs, rpc_cvi_isp_setccmsaturationattr_1_argument *objp)
{
	 if (!xdr_RPC_VI_PIPE (xdrs, &objp->ViPipe))
		 return FALSE;
	 if (!xdr_RPC_ISP_SET_ATTR_DATA_S (xdrs, &objp->stAttrData))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cvi_isp_setcaattr_1_argument (XDR *xdrs, rpc_cvi_isp_setcaattr_1_argument *objp)
{
	 if (!xdr_RPC_VI_PIPE (xdrs, &objp->ViPipe))
		 return FALSE;
	 if (!xdr_RPC_ISP_SET_ATTR_DATA_S (xdrs, &objp->stAttrData))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cvi_isp_setcscattr_1_argument (XDR *xdrs, rpc_cvi_isp_setcscattr_1_argument *objp)
{
	 if (!xdr_RPC_VI_PIPE (xdrs, &objp->ViPipe))
		 return FALSE;
	 if (!xdr_RPC_ISP_SET_ATTR_DATA_S (xdrs, &objp->stAttrData))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cvi_isp_setexposureattr_1_argument (XDR *xdrs, rpc_cvi_isp_setexposureattr_1_argument *objp)
{
	 if (!xdr_RPC_VI_PIPE (xdrs, &objp->ViPipe))
		 return FALSE;
	 if (!xdr_RPC_ISP_SET_ATTR_DATA_S (xdrs, &objp->stAttrData))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cvi_isp_setwdrexposureattr_1_argument (XDR *xdrs, rpc_cvi_isp_setwdrexposureattr_1_argument *objp)
{
	 if (!xdr_RPC_VI_PIPE (xdrs, &objp->ViPipe))
		 return FALSE;
	 if (!xdr_RPC_ISP_SET_ATTR_DATA_S (xdrs, &objp->stAttrData))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cvi_isp_setaerouteattr_1_argument (XDR *xdrs, rpc_cvi_isp_setaerouteattr_1_argument *objp)
{
	 if (!xdr_RPC_VI_PIPE (xdrs, &objp->ViPipe))
		 return FALSE;
	 if (!xdr_RPC_ISP_SET_ATTR_DATA_S (xdrs, &objp->stAttrData))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cvi_isp_setaerouteattrex_1_argument (XDR *xdrs, rpc_cvi_isp_setaerouteattrex_1_argument *objp)
{
	 if (!xdr_RPC_VI_PIPE (xdrs, &objp->ViPipe))
		 return FALSE;
	 if (!xdr_RPC_ISP_SET_ATTR_DATA_S (xdrs, &objp->stAttrData))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cvi_isp_aebracketingsetexpsoure_1_argument (XDR *xdrs, rpc_cvi_isp_aebracketingsetexpsoure_1_argument *objp)
{
	 if (!xdr_RPC_VI_PIPE (xdrs, &objp->ViPipe))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->leEvX10))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->seEvX10))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cvi_isp_setaestatisticsconfig_1_argument (XDR *xdrs, rpc_cvi_isp_setaestatisticsconfig_1_argument *objp)
{
	 if (!xdr_RPC_VI_PIPE (xdrs, &objp->ViPipe))
		 return FALSE;
	 if (!xdr_RPC_ISP_SET_ATTR_DATA_S (xdrs, &objp->stAttrData))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cvi_isp_setantiflicker_1_argument (XDR *xdrs, rpc_cvi_isp_setantiflicker_1_argument *objp)
{
	 if (!xdr_RPC_VI_PIPE (xdrs, &objp->ViPipe))
		 return FALSE;
	 if (!xdr_uint8_t (xdrs, &objp->enable))
		 return FALSE;
	 if (!xdr_uint8_t (xdrs, &objp->frequency))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cvi_isp_setwdrleonly_1_argument (XDR *xdrs, rpc_cvi_isp_setwdrleonly_1_argument *objp)
{
	 if (!xdr_RPC_VI_PIPE (xdrs, &objp->ViPipe))
		 return FALSE;
	 if (!xdr_uint8_t (xdrs, &objp->wdrLEOnly))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cvi_isp_setfastbootexposure_1_argument (XDR *xdrs, rpc_cvi_isp_setfastbootexposure_1_argument *objp)
{
	 if (!xdr_RPC_VI_PIPE (xdrs, &objp->ViPipe))
		 return FALSE;
	 if (!xdr_uint32_t (xdrs, &objp->expLine))
		 return FALSE;
	 if (!xdr_uint32_t (xdrs, &objp->again))
		 return FALSE;
	 if (!xdr_uint32_t (xdrs, &objp->dgain))
		 return FALSE;
	 if (!xdr_uint32_t (xdrs, &objp->ispdgain))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cvi_isp_setsmartexposureattr_1_argument (XDR *xdrs, rpc_cvi_isp_setsmartexposureattr_1_argument *objp)
{
	 if (!xdr_RPC_VI_PIPE (xdrs, &objp->ViPipe))
		 return FALSE;
	 if (!xdr_RPC_ISP_SET_ATTR_DATA_S (xdrs, &objp->stAttrData))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cvi_isp_setwbattr_1_argument (XDR *xdrs, rpc_cvi_isp_setwbattr_1_argument *objp)
{
	 if (!xdr_RPC_VI_PIPE (xdrs, &objp->ViPipe))
		 return FALSE;
	 if (!xdr_RPC_ISP_SET_ATTR_DATA_S (xdrs, &objp->stAttrData))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cvi_isp_setawbattrex_1_argument (XDR *xdrs, rpc_cvi_isp_setawbattrex_1_argument *objp)
{
	 if (!xdr_RPC_VI_PIPE (xdrs, &objp->ViPipe))
		 return FALSE;
	 if (!xdr_RPC_ISP_SET_ATTR_DATA_S (xdrs, &objp->stAttrData))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cvi_isp_setwbcalibration_1_argument (XDR *xdrs, rpc_cvi_isp_setwbcalibration_1_argument *objp)
{
	 if (!xdr_RPC_VI_PIPE (xdrs, &objp->ViPipe))
		 return FALSE;
	 if (!xdr_RPC_ISP_SET_ATTR_DATA_S (xdrs, &objp->stAttrData))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cvi_isp_setwbcalibrationex_1_argument (XDR *xdrs, rpc_cvi_isp_setwbcalibrationex_1_argument *objp)
{
	 if (!xdr_RPC_VI_PIPE (xdrs, &objp->ViPipe))
		 return FALSE;
	 if (!xdr_RPC_ISP_SET_ATTR_DATA_S (xdrs, &objp->stAttrData))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_cvi_isp_setawbwinstatictics_1_argument (XDR *xdrs, rpc_cvi_isp_setawbwinstatictics_1_argument *objp)
{
	 if (!xdr_RPC_VI_PIPE (xdrs, &objp->ViPipe))
		 return FALSE;
	 if (!xdr_RPC_ISP_SET_ATTR_DATA_S (xdrs, &objp->stAttrData))
		 return FALSE;
	return TRUE;
}
#pragma GCC diagnostic pop

