/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "isp_rpc.h"


void
isp_rpc_1(char *host)
{
	CLIENT *clnt;
	RPC_CVI_S32  *result_1;
	RPC_VI_PIPE rpc_cvi_isp_setpubattr_1_ViPipe;
	RPC_ISP_SET_ATTR_DATA_S rpc_cvi_isp_setpubattr_1_stAttrData;
	RPC_ISP_GET_ATTR_DATA_S  *result_2;
	RPC_VI_PIPE rpc_cvi_isp_getpubattr_1_ViPipe;
	RPC_CVI_S32  *result_3;
	RPC_ISP_SET_ATTR_DATA_S rpc_cvi_isp_setmodparam_1_stAttrData;
	RPC_ISP_GET_ATTR_DATA_S  *result_4;
	RPC_CVI_S32  *result_5;
	RPC_VI_PIPE rpc_cvi_isp_setctrlparam_1_ViPipe;
	RPC_ISP_SET_ATTR_DATA_S rpc_cvi_isp_setctrlparam_1_stAttrData;
	RPC_ISP_GET_ATTR_DATA_S  *result_6;
	RPC_VI_PIPE rpc_cvi_isp_getctrlparam_1_ViPipe;
	RPC_CVI_S32  *result_7;
	RPC_VI_PIPE rpc_cvi_isp_setfmwstate_1_ViPipe;
	uint32_t  rpc_cvi_isp_setfmwstate_1_enState;
	uint32_t  *result_8;
	RPC_VI_PIPE rpc_cvi_isp_getfmwstate_1_ViPipe;
	RPC_CVI_S32  *result_9;
	RPC_VI_PIPE rpc_cvi_isp_setmodulecontrol_1_ViPipe;
	RPC_ISP_SET_ATTR_DATA_S rpc_cvi_isp_setmodulecontrol_1_stAttrData;
	RPC_ISP_GET_ATTR_DATA_S  *result_10;
	RPC_VI_PIPE rpc_cvi_isp_getmodulecontrol_1_ViPipe;
	RPC_CVI_S32  *result_11;
	RPC_VI_PIPE rpc_cvi_isp_setregister_1_ViPipe;
	uint32_t  rpc_cvi_isp_setregister_1_u32Addr;
	uint32_t  rpc_cvi_isp_setregister_1_u32Value;
	uint32_t  *result_12;
	RPC_VI_PIPE rpc_cvi_isp_getregister_1_ViPipe;
	uint32_t  rpc_cvi_isp_getregister_1_u32Addr;
	RPC_CVI_S32  *result_13;
	RPC_VI_PIPE rpc_cvi_isp_setcolortoneattr_1_ViPipe;
	RPC_ISP_SET_ATTR_DATA_S rpc_cvi_isp_setcolortoneattr_1_stAttrData;
	RPC_ISP_GET_ATTR_DATA_S  *result_14;
	RPC_VI_PIPE rpc_cvi_isp_getcolortoneattr_1_ViPipe;
	RPC_CVI_S32  *result_15;
	RPC_VI_PIPE rpc_cvi_isp_setdehazeattr_1_ViPipe;
	RPC_ISP_SET_ATTR_DATA_S rpc_cvi_isp_setdehazeattr_1_stAttrData;
	RPC_ISP_GET_ATTR_DATA_S  *result_16;
	RPC_VI_PIPE rpc_cvi_isp_getdehazeattr_1_ViPipe;
	RPC_CVI_S32  *result_17;
	RPC_VI_PIPE rpc_cvi_isp_setgammaattr_1_ViPipe;
	RPC_ISP_SET_ATTR_DATA_S rpc_cvi_isp_setgammaattr_1_stAttrData;
	RPC_ISP_GET_ATTR_DATA_S  *result_18;
	RPC_VI_PIPE rpc_cvi_isp_getgammaattr_1_ViPipe;
	RPC_CVI_S32  *result_19;
	RPC_VI_PIPE rpc_cvi_isp_setgammacurvetype_1_ViPipe;
	uint32_t  rpc_cvi_isp_setgammacurvetype_1_curveType;
	RPC_CVI_S32  *result_20;
	RPC_VI_PIPE rpc_cvi_isp_setautogammaattr_1_ViPipe;
	RPC_ISP_SET_ATTR_DATA_S rpc_cvi_isp_setautogammaattr_1_stAttrData;
	RPC_ISP_GET_ATTR_DATA_S  *result_21;
	RPC_VI_PIPE rpc_cvi_isp_getautogammaattr_1_ViPipe;
	RPC_CVI_S32  *result_22;
	RPC_VI_PIPE rpc_cvi_isp_setstatisticsconfig_1_ViPipe;
	RPC_ISP_SET_ATTR_DATA_S rpc_cvi_isp_setstatisticsconfig_1_stAttrData;
	RPC_ISP_GET_ATTR_DATA_S  *result_23;
	RPC_VI_PIPE rpc_cvi_isp_getstatisticsconfig_1_ViPipe;
	RPC_CVI_S32  *result_24;
	RPC_VI_PIPE rpc_cvi_isp_setnrattr_1_ViPipe;
	RPC_ISP_SET_ATTR_DATA_S rpc_cvi_isp_setnrattr_1_stAttrData;
	RPC_ISP_GET_ATTR_DATA_S  *result_25;
	RPC_VI_PIPE rpc_cvi_isp_getnrattr_1_ViPipe;
	RPC_CVI_S32  *result_26;
	RPC_VI_PIPE rpc_cvi_isp_setnrfilterattr_1_ViPipe;
	RPC_ISP_SET_ATTR_DATA_S rpc_cvi_isp_setnrfilterattr_1_stAttrData;
	RPC_ISP_GET_ATTR_DATA_S  *result_27;
	RPC_VI_PIPE rpc_cvi_isp_getnrfilterattr_1_ViPipe;
	RPC_CVI_S32  *result_28;
	RPC_VI_PIPE rpc_cvi_isp_setrlscattr_1_ViPipe;
	RPC_ISP_SET_ATTR_DATA_S rpc_cvi_isp_setrlscattr_1_stAttrData;
	RPC_ISP_GET_ATTR_DATA_S  *result_29;
	RPC_VI_PIPE rpc_cvi_isp_getrlscattr_1_ViPipe;
	RPC_CVI_S32  *result_30;
	RPC_VI_PIPE rpc_cvi_isp_setynrattr_1_ViPipe;
	RPC_ISP_SET_ATTR_DATA_S rpc_cvi_isp_setynrattr_1_stAttrData;
	RPC_ISP_GET_ATTR_DATA_S  *result_31;
	RPC_VI_PIPE rpc_cvi_isp_getynrattr_1_ViPipe;
	RPC_CVI_S32  *result_32;
	RPC_VI_PIPE rpc_cvi_isp_setynrmotionnrattr_1_ViPipe;
	RPC_ISP_SET_ATTR_DATA_S rpc_cvi_isp_setynrmotionnrattr_1_stAttrData;
	RPC_ISP_GET_ATTR_DATA_S  *result_33;
	RPC_VI_PIPE rpc_cvi_isp_getynrmotionnrattr_1_ViPipe;
	RPC_CVI_S32  *result_34;
	RPC_VI_PIPE rpc_cvi_isp_setynrfilterattr_1_ViPipe;
	RPC_ISP_SET_ATTR_DATA_S rpc_cvi_isp_setynrfilterattr_1_stAttrData;
	RPC_ISP_GET_ATTR_DATA_S  *result_35;
	RPC_VI_PIPE rpc_cvi_isp_getynrfilterattr_1_ViPipe;
	RPC_CVI_S32  *result_36;
	RPC_VI_PIPE rpc_cvi_isp_setcnrattr_1_ViPipe;
	RPC_ISP_SET_ATTR_DATA_S rpc_cvi_isp_setcnrattr_1_stAttrData;
	RPC_ISP_GET_ATTR_DATA_S  *result_37;
	RPC_VI_PIPE rpc_cvi_isp_getcnrattr_1_ViPipe;
	RPC_CVI_S32  *result_38;
	RPC_VI_PIPE rpc_cvi_isp_setcacattr_1_ViPipe;
	RPC_ISP_SET_ATTR_DATA_S rpc_cvi_isp_setcacattr_1_stAttrData;
	RPC_ISP_GET_ATTR_DATA_S  *result_39;
	RPC_VI_PIPE rpc_cvi_isp_getcacattr_1_ViPipe;
	RPC_CVI_S32  *result_40;
	RPC_VI_PIPE rpc_cvi_isp_setdciattr_1_ViPipe;
	RPC_ISP_SET_ATTR_DATA_S rpc_cvi_isp_setdciattr_1_stAttrData;
	RPC_ISP_GET_ATTR_DATA_S  *result_41;
	RPC_VI_PIPE rpc_cvi_isp_getdciattr_1_ViPipe;
	RPC_CVI_S32  *result_42;
	RPC_VI_PIPE rpc_cvi_isp_setmeshshadingattr_1_ViPipe;
	RPC_ISP_SET_ATTR_DATA_S rpc_cvi_isp_setmeshshadingattr_1_stAttrData;
	RPC_ISP_GET_ATTR_DATA_S  *result_43;
	RPC_VI_PIPE rpc_cvi_isp_getmeshshadingattr_1_ViPipe;
	RPC_CVI_S32  *result_44;
	RPC_VI_PIPE rpc_cvi_isp_setmeshshadinggainlutattr_1_ViPipe;
	RPC_ISP_SET_ATTR_DATA_S rpc_cvi_isp_setmeshshadinggainlutattr_1_stAttrData;
	RPC_ISP_GET_ATTR_DATA_S  *result_45;
	RPC_VI_PIPE rpc_cvi_isp_getmeshshadinggainlutattr_1_ViPipe;
	RPC_CVI_S32  *result_46;
	RPC_VI_PIPE rpc_cvi_isp_setradialshadingattr_1_ViPipe;
	RPC_ISP_SET_ATTR_DATA_S rpc_cvi_isp_setradialshadingattr_1_stAttrData;
	RPC_ISP_GET_ATTR_DATA_S  *result_47;
	RPC_VI_PIPE rpc_cvi_isp_getradialshadingattr_1_ViPipe;
	RPC_CVI_S32  *result_48;
	RPC_VI_PIPE rpc_cvi_isp_setradialshadinggainlutattr_1_ViPipe;
	RPC_ISP_SET_ATTR_DATA_S rpc_cvi_isp_setradialshadinggainlutattr_1_stAttrData;
	RPC_ISP_GET_ATTR_DATA_S  *result_49;
	RPC_VI_PIPE rpc_cvi_isp_getradialshadinggainlutattr_1_ViPipe;
	RPC_CVI_S32  *result_50;
	RPC_VI_PIPE rpc_cvi_isp_settnrattr_1_ViPipe;
	RPC_ISP_SET_ATTR_DATA_S rpc_cvi_isp_settnrattr_1_stAttrData;
	RPC_ISP_GET_ATTR_DATA_S  *result_51;
	RPC_VI_PIPE rpc_cvi_isp_gettnrattr_1_ViPipe;
	RPC_CVI_S32  *result_52;
	RPC_VI_PIPE rpc_cvi_isp_settnrnoisemodelattr_1_ViPipe;
	RPC_ISP_SET_ATTR_DATA_S rpc_cvi_isp_settnrnoisemodelattr_1_stAttrData;
	RPC_ISP_GET_ATTR_DATA_S  *result_53;
	RPC_VI_PIPE rpc_cvi_isp_gettnrnoisemodelattr_1_ViPipe;
	RPC_CVI_S32  *result_54;
	RPC_VI_PIPE rpc_cvi_isp_settnrlumamotionattr_1_ViPipe;
	RPC_ISP_SET_ATTR_DATA_S rpc_cvi_isp_settnrlumamotionattr_1_stAttrData;
	RPC_ISP_GET_ATTR_DATA_S  *result_55;
	RPC_VI_PIPE rpc_cvi_isp_gettnrlumamotionattr_1_ViPipe;
	RPC_CVI_S32  *result_56;
	RPC_VI_PIPE rpc_cvi_isp_settnrghostattr_1_ViPipe;
	RPC_ISP_SET_ATTR_DATA_S rpc_cvi_isp_settnrghostattr_1_stAttrData;
	RPC_ISP_GET_ATTR_DATA_S  *result_57;
	RPC_VI_PIPE rpc_cvi_isp_gettnrghostattr_1_ViPipe;
	RPC_CVI_S32  *result_58;
	RPC_VI_PIPE rpc_cvi_isp_settnrmtprtattr_1_ViPipe;
	RPC_ISP_SET_ATTR_DATA_S rpc_cvi_isp_settnrmtprtattr_1_stAttrData;
	RPC_ISP_GET_ATTR_DATA_S  *result_59;
	RPC_VI_PIPE rpc_cvi_isp_gettnrmtprtattr_1_ViPipe;
	RPC_CVI_S32  *result_60;
	RPC_VI_PIPE rpc_cvi_isp_setclutattr_1_ViPipe;
	RPC_ISP_SET_ATTR_DATA_S rpc_cvi_isp_setclutattr_1_stAttrData;
	RPC_ISP_GET_ATTR_DATA_S  *result_61;
	RPC_VI_PIPE rpc_cvi_isp_getclutattr_1_ViPipe;
	RPC_CVI_S32  *result_62;
	RPC_VI_PIPE rpc_cvi_isp_setclutcoeff_1_ViPipe;
	RPC_ISP_SET_ATTR_DATA_S rpc_cvi_isp_setclutcoeff_1_stAttrData;
	RPC_ISP_GET_ATTR_DATA_S  *result_63;
	RPC_VI_PIPE rpc_cvi_isp_getclutcoeff_1_ViPipe;
	RPC_CVI_S32  *result_64;
	RPC_VI_PIPE rpc_cvi_isp_setblacklevelattr_1_ViPipe;
	RPC_ISP_SET_ATTR_DATA_S rpc_cvi_isp_setblacklevelattr_1_stAttrData;
	RPC_ISP_GET_ATTR_DATA_S  *result_65;
	RPC_VI_PIPE rpc_cvi_isp_getblacklevelattr_1_ViPipe;
	RPC_CVI_S32  *result_66;
	RPC_VI_PIPE rpc_cvi_isp_setdemosaicattr_1_ViPipe;
	RPC_ISP_SET_ATTR_DATA_S rpc_cvi_isp_setdemosaicattr_1_stAttrData;
	RPC_ISP_GET_ATTR_DATA_S  *result_67;
	RPC_VI_PIPE rpc_cvi_isp_getdemosaicattr_1_ViPipe;
	RPC_CVI_S32  *result_68;
	RPC_VI_PIPE rpc_cvi_isp_setdemosaicdemoireattr_1_ViPipe;
	RPC_ISP_SET_ATTR_DATA_S rpc_cvi_isp_setdemosaicdemoireattr_1_stAttrData;
	RPC_ISP_GET_ATTR_DATA_S  *result_69;
	RPC_VI_PIPE rpc_cvi_isp_getdemosaicdemoireattr_1_ViPipe;
	RPC_CVI_S32  *result_70;
	RPC_VI_PIPE rpc_cvi_isp_setdemosaicfilterattr_1_ViPipe;
	RPC_ISP_SET_ATTR_DATA_S rpc_cvi_isp_setdemosaicfilterattr_1_stAttrData;
	RPC_ISP_GET_ATTR_DATA_S  *result_71;
	RPC_VI_PIPE rpc_cvi_isp_getdemosaicfilterattr_1_ViPipe;
	RPC_CVI_S32  *result_72;
	RPC_VI_PIPE rpc_cvi_isp_setdemosaiceeattr_1_ViPipe;
	RPC_ISP_SET_ATTR_DATA_S rpc_cvi_isp_setdemosaiceeattr_1_stAttrData;
	RPC_ISP_GET_ATTR_DATA_S  *result_73;
	RPC_VI_PIPE rpc_cvi_isp_getdemosaiceeattr_1_ViPipe;
	RPC_CVI_S32  *result_74;
	RPC_VI_PIPE rpc_cvi_isp_setsaturationattr_1_ViPipe;
	RPC_ISP_SET_ATTR_DATA_S rpc_cvi_isp_setsaturationattr_1_stAttrData;
	RPC_ISP_GET_ATTR_DATA_S  *result_75;
	RPC_VI_PIPE rpc_cvi_isp_getsaturationattr_1_ViPipe;
	RPC_CVI_S32  *result_76;
	RPC_VI_PIPE rpc_cvi_isp_setccmattr_1_ViPipe;
	RPC_ISP_SET_ATTR_DATA_S rpc_cvi_isp_setccmattr_1_stAttrData;
	RPC_ISP_GET_ATTR_DATA_S  *result_77;
	RPC_VI_PIPE rpc_cvi_isp_getccmattr_1_ViPipe;
	RPC_CVI_S32  *result_78;
	RPC_VI_PIPE rpc_cvi_isp_sethsvattr_1_ViPipe;
	RPC_ISP_SET_ATTR_DATA_S rpc_cvi_isp_sethsvattr_1_stAttrData;
	RPC_ISP_GET_ATTR_DATA_S  *result_79;
	RPC_VI_PIPE rpc_cvi_isp_gethsvattr_1_ViPipe;
	RPC_CVI_S32  *result_80;
	RPC_VI_PIPE rpc_cvi_isp_setdpdynamicattr_1_ViPipe;
	RPC_ISP_SET_ATTR_DATA_S rpc_cvi_isp_setdpdynamicattr_1_stAttrData;
	RPC_ISP_GET_ATTR_DATA_S  *result_81;
	RPC_VI_PIPE rpc_cvi_isp_getdpdynamicattr_1_ViPipe;
	RPC_CVI_S32  *result_82;
	RPC_VI_PIPE rpc_cvi_isp_setdpstaticattr_1_ViPipe;
	RPC_ISP_SET_ATTR_DATA_S rpc_cvi_isp_setdpstaticattr_1_stAttrData;
	RPC_ISP_GET_ATTR_DATA_S  *result_83;
	RPC_VI_PIPE rpc_cvi_isp_getdpstaticattr_1_ViPipe;
	RPC_CVI_S32  *result_84;
	RPC_VI_PIPE rpc_cvi_isp_setdpcalibrate_1_ViPipe;
	RPC_ISP_SET_ATTR_DATA_S rpc_cvi_isp_setdpcalibrate_1_stAttrData;
	RPC_ISP_GET_ATTR_DATA_S  *result_85;
	RPC_VI_PIPE rpc_cvi_isp_getdpcalibrate_1_ViPipe;
	RPC_CVI_S32  *result_86;
	RPC_VI_PIPE rpc_cvi_isp_setcrosstalkattr_1_ViPipe;
	RPC_ISP_SET_ATTR_DATA_S rpc_cvi_isp_setcrosstalkattr_1_stAttrData;
	RPC_ISP_GET_ATTR_DATA_S  *result_87;
	RPC_VI_PIPE rpc_cvi_isp_getcrosstalkattr_1_ViPipe;
	RPC_ISP_GET_ATTR_DATA_S  *result_88;
	RPC_VI_PIPE rpc_cvi_isp_getaestatistics_1_ViPipe;
	RPC_ISP_GET_ATTR_DATA_S  *result_89;
	RPC_VI_PIPE rpc_cvi_isp_getwbstatistics_1_ViPipe;
	RPC_ISP_GET_ATTR_DATA_S  *result_90;
	RPC_VI_PIPE rpc_cvi_isp_getfocusstatistics_1_ViPipe;
	RPC_ISP_GET_ATTR_DATA_S  *result_91;
	RPC_VI_PIPE rpc_cvi_isp_getlightboxgain_1_ViPipe;
	RPC_CVI_S32  *result_92;
	RPC_VI_PIPE rpc_cvi_isp_setfswdrattr_1_ViPipe;
	RPC_ISP_SET_ATTR_DATA_S rpc_cvi_isp_setfswdrattr_1_stAttrData;
	RPC_ISP_GET_ATTR_DATA_S  *result_93;
	RPC_VI_PIPE rpc_cvi_isp_getfswdrattr_1_ViPipe;
	RPC_CVI_S32  *result_94;
	RPC_VI_PIPE rpc_cvi_isp_setdrcattr_1_ViPipe;
	RPC_ISP_SET_ATTR_DATA_S rpc_cvi_isp_setdrcattr_1_stAttrData;
	RPC_ISP_GET_ATTR_DATA_S  *result_95;
	RPC_VI_PIPE rpc_cvi_isp_getdrcattr_1_ViPipe;
	RPC_CVI_S32  *result_96;
	RPC_VI_PIPE rpc_cvi_isp_setsharpenattr_1_ViPipe;
	RPC_ISP_SET_ATTR_DATA_S rpc_cvi_isp_setsharpenattr_1_stAttrData;
	RPC_ISP_GET_ATTR_DATA_S  *result_97;
	RPC_VI_PIPE rpc_cvi_isp_getsharpenattr_1_ViPipe;
	RPC_CVI_S32  *result_98;
	RPC_VI_PIPE rpc_cvi_isp_setnoiseprofileattr_1_ViPipe;
	RPC_ISP_SET_ATTR_DATA_S rpc_cvi_isp_setnoiseprofileattr_1_stAttrData;
	RPC_ISP_GET_ATTR_DATA_S  *result_99;
	RPC_VI_PIPE rpc_cvi_isp_getnoiseprofileattr_1_ViPipe;
	RPC_CVI_S32  *result_100;
	RPC_VI_PIPE rpc_cvi_isp_setycontrastattr_1_ViPipe;
	RPC_ISP_SET_ATTR_DATA_S rpc_cvi_isp_setycontrastattr_1_stAttrData;
	RPC_ISP_GET_ATTR_DATA_S  *result_101;
	RPC_VI_PIPE rpc_cvi_isp_getycontrastattr_1_ViPipe;
	RPC_CVI_S32  *result_102;
	RPC_VI_PIPE rpc_cvi_isp_setdcfinfo_1_ViPipe;
	RPC_ISP_SET_ATTR_DATA_S rpc_cvi_isp_setdcfinfo_1_stAttrData;
	RPC_ISP_GET_ATTR_DATA_S  *result_103;
	RPC_VI_PIPE rpc_cvi_isp_getdcfinfo_1_ViPipe;
	RPC_ISP_GET_ATTR_DATA_S  *result_104;
	RPC_VI_PIPE rpc_cvi_isp_queryinnerstateinfo_1_ViPipe;
	RPC_CVI_S32  *result_105;
	RPC_VI_PIPE rpc_cvi_isp_getvdtimeout_1_ViPipe;
	uint32_t  rpc_cvi_isp_getvdtimeout_1_enIspVDType;
	uint32_t  rpc_cvi_isp_getvdtimeout_1_u32MilliSec;
	RPC_CVI_S32  *result_106;
	RPC_VI_PIPE rpc_cvi_isp_setmonoattr_1_ViPipe;
	RPC_ISP_SET_ATTR_DATA_S rpc_cvi_isp_setmonoattr_1_stAttrData;
	RPC_ISP_GET_ATTR_DATA_S  *result_107;
	RPC_VI_PIPE rpc_cvi_isp_getmonoattr_1_ViPipe;
	RPC_CVI_S32  *result_108;
	RPC_VI_PIPE rpc_cvi_isp_setdisattr_1_ViPipe;
	RPC_ISP_SET_ATTR_DATA_S rpc_cvi_isp_setdisattr_1_stAttrData;
	RPC_ISP_GET_ATTR_DATA_S  *result_109;
	RPC_VI_PIPE rpc_cvi_isp_getdisattr_1_ViPipe;
	RPC_CVI_S32  *result_110;
	RPC_VI_PIPE rpc_cvi_isp_setdisconfig_1_ViPipe;
	RPC_ISP_SET_ATTR_DATA_S rpc_cvi_isp_setdisconfig_1_stAttrData;
	RPC_ISP_GET_ATTR_DATA_S  *result_111;
	RPC_VI_PIPE rpc_cvi_isp_getdisconfig_1_ViPipe;
	RPC_CVI_S32  *result_112;
	RPC_VI_PIPE rpc_cvi_isp_getbinstatus_1_ViPipe;
	RPC_CVI_S32  *result_113;
	RPC_VI_PIPE rpc_cvi_isp_setvcattr_1_ViPipe;
	RPC_ISP_SET_ATTR_DATA_S rpc_cvi_isp_setvcattr_1_stAttrData;
	RPC_ISP_GET_ATTR_DATA_S  *result_114;
	RPC_VI_PIPE rpc_cvi_isp_getvcattr_1_ViPipe;
	RPC_CVI_S32  *result_115;
	RPC_VI_PIPE rpc_cvi_isp_dumphwregistertofile_1_ViPipe;
	char *rpc_cvi_isp_dumphwregistertofile_1_fileName;
	RPC_CVI_S32  *result_116;
	RPC_VI_PIPE rpc_cvi_isp_dumpframerawinfotofile_1_ViPipe;
	char *rpc_cvi_isp_dumpframerawinfotofile_1_fileName;
	RPC_ISP_GET_ATTR_DATA_S  *result_117;
	uint32_t  rpc_cvi_isp_irautorunonce_1_IspDev;
	RPC_ISP_SET_ATTR_DATA_S rpc_cvi_isp_irautorunonce_1_stAttrData;
	RPC_CVI_S32  *result_118;
	RPC_VI_PIPE rpc_cvi_isp_setsmartinfo_1_ViPipe;
	RPC_ISP_SET_ATTR_DATA_S rpc_cvi_isp_setsmartinfo_1_stAttrData;
	uint8_t  rpc_cvi_isp_setsmartinfo_1_TimeOut;
	RPC_ISP_GET_ATTR_DATA_S  *result_119;
	RPC_VI_PIPE rpc_cvi_isp_getsmartinfo_1_ViPipe;
	RPC_CVI_S32  *result_120;
	RPC_VI_PIPE rpc_cvi_isp_settnrmotionadaptattr_1_ViPipe;
	RPC_ISP_SET_ATTR_DATA_S rpc_cvi_isp_settnrmotionadaptattr_1_stAttrData;
	RPC_ISP_GET_ATTR_DATA_S  *result_121;
	RPC_VI_PIPE rpc_cvi_isp_gettnrmotionadaptattr_1_ViPipe;
	RPC_CVI_S32  *result_122;
	RPC_VI_PIPE rpc_cvi_isp_setclutsaturationattr_1_ViPipe;
	RPC_ISP_SET_ATTR_DATA_S rpc_cvi_isp_setclutsaturationattr_1_stAttrData;
	RPC_ISP_GET_ATTR_DATA_S  *result_123;
	RPC_VI_PIPE rpc_cvi_isp_getclutsaturationattr_1_ViPipe;
	RPC_ISP_GET_ATTR_DATA_S  *result_124;
	RPC_VI_PIPE rpc_cvi_isp_getgammacurvebytype_1_ViPipe;
	uint32_t  rpc_cvi_isp_getgammacurvebytype_1_curveType;
	RPC_CVI_S32  *result_125;
	RPC_VI_PIPE rpc_cvi_isp_setpresharpenattr_1_ViPipe;
	RPC_ISP_SET_ATTR_DATA_S rpc_cvi_isp_setpresharpenattr_1_stAttrData;
	RPC_ISP_GET_ATTR_DATA_S  *result_126;
	RPC_VI_PIPE rpc_cvi_isp_getpresharpenattr_1_ViPipe;
	RPC_CVI_S32  *result_127;
	RPC_VI_PIPE rpc_cvi_isp_setrgbcacattr_1_ViPipe;
	RPC_ISP_SET_ATTR_DATA_S rpc_cvi_isp_setrgbcacattr_1_stAttrData;
	RPC_ISP_GET_ATTR_DATA_S  *result_128;
	RPC_VI_PIPE rpc_cvi_isp_getrgbcacattr_1_ViPipe;
	RPC_CVI_S32  *result_129;
	RPC_VI_PIPE rpc_cvi_isp_setcnrmotionnrattr_1_ViPipe;
	RPC_ISP_SET_ATTR_DATA_S rpc_cvi_isp_setcnrmotionnrattr_1_stAttrData;
	RPC_ISP_GET_ATTR_DATA_S  *result_130;
	RPC_VI_PIPE rpc_cvi_isp_getcnrmotionnrattr_1_ViPipe;
	RPC_CVI_S32  *result_131;
	RPC_VI_PIPE rpc_cvi_isp_setccmsaturationattr_1_ViPipe;
	RPC_ISP_SET_ATTR_DATA_S rpc_cvi_isp_setccmsaturationattr_1_stAttrData;
	RPC_ISP_GET_ATTR_DATA_S  *result_132;
	RPC_VI_PIPE rpc_cvi_isp_getccmsaturationattr_1_ViPipe;
	RPC_CVI_S32  *result_133;
	RPC_VI_PIPE rpc_cvi_isp_setcaattr_1_ViPipe;
	RPC_ISP_SET_ATTR_DATA_S rpc_cvi_isp_setcaattr_1_stAttrData;
	RPC_ISP_GET_ATTR_DATA_S  *result_134;
	RPC_VI_PIPE rpc_cvi_isp_getcaattr_1_ViPipe;
	RPC_CVI_S32  *result_135;
	RPC_VI_PIPE rpc_cvi_isp_setcscattr_1_ViPipe;
	RPC_ISP_SET_ATTR_DATA_S rpc_cvi_isp_setcscattr_1_stAttrData;
	RPC_ISP_GET_ATTR_DATA_S  *result_136;
	RPC_VI_PIPE rpc_cvi_isp_getcscattr_1_ViPipe;
	RPC_CVI_S32  *result_137;
	RPC_VI_PIPE rpc_cvi_isp_setexposureattr_1_ViPipe;
	RPC_ISP_SET_ATTR_DATA_S rpc_cvi_isp_setexposureattr_1_stAttrData;
	RPC_ISP_GET_ATTR_DATA_S  *result_138;
	RPC_VI_PIPE rpc_cvi_isp_getexposureattr_1_ViPipe;
	RPC_ISP_GET_ATTR_DATA_S  *result_139;
	RPC_VI_PIPE rpc_cvi_isp_queryexposureinfo_1_ViPipe;
	RPC_CVI_S32  *result_140;
	RPC_VI_PIPE rpc_cvi_isp_setwdrexposureattr_1_ViPipe;
	RPC_ISP_SET_ATTR_DATA_S rpc_cvi_isp_setwdrexposureattr_1_stAttrData;
	RPC_ISP_GET_ATTR_DATA_S  *result_141;
	RPC_VI_PIPE rpc_cvi_isp_getwdrexposureattr_1_ViPipe;
	RPC_CVI_S32  *result_142;
	RPC_VI_PIPE rpc_cvi_isp_setaerouteattr_1_ViPipe;
	RPC_ISP_SET_ATTR_DATA_S rpc_cvi_isp_setaerouteattr_1_stAttrData;
	RPC_ISP_GET_ATTR_DATA_S  *result_143;
	RPC_VI_PIPE rpc_cvi_isp_getaerouteattr_1_ViPipe;
	RPC_CVI_S32  *result_144;
	RPC_VI_PIPE rpc_cvi_isp_setaerouteattrex_1_ViPipe;
	RPC_ISP_SET_ATTR_DATA_S rpc_cvi_isp_setaerouteattrex_1_stAttrData;
	RPC_ISP_GET_ATTR_DATA_S  *result_145;
	RPC_VI_PIPE rpc_cvi_isp_getaerouteattrex_1_ViPipe;
	RPC_CVI_S32  *result_146;
	RPC_VI_PIPE rpc_cvi_isp_aebracketingstart_1_ViPipe;
	RPC_CVI_S32  *result_147;
	RPC_VI_PIPE rpc_cvi_isp_aebracketingsetexpsoure_1_ViPipe;
	int rpc_cvi_isp_aebracketingsetexpsoure_1_leEvX10;
	int rpc_cvi_isp_aebracketingsetexpsoure_1_seEvX10;
	RPC_CVI_S32  *result_148;
	RPC_VI_PIPE rpc_cvi_isp_aebracketingfinish_1_ViPipe;
	RPC_CVI_S32  *result_149;
	uint8_t  rpc_cvi_isp_aebracketingsetsimple_1_enable;
	RPC_CVI_S32  *result_150;
	RPC_VI_PIPE rpc_cvi_isp_setaestatisticsconfig_1_ViPipe;
	RPC_ISP_SET_ATTR_DATA_S rpc_cvi_isp_setaestatisticsconfig_1_stAttrData;
	RPC_ISP_GET_ATTR_DATA_S  *result_151;
	RPC_VI_PIPE rpc_cvi_isp_getaestatisticsconfig_1_ViPipe;
	RPC_CVI_S32  *result_152;
	RPC_VI_PIPE rpc_cvi_isp_setantiflicker_1_ViPipe;
	uint8_t  rpc_cvi_isp_setantiflicker_1_enable;
	uint8_t  rpc_cvi_isp_setantiflicker_1_frequency;
	uint32_t  *result_153;
	RPC_VI_PIPE rpc_cvi_isp_getantiflicker_1_ViPipe;
	RPC_CVI_S32  *result_154;
	RPC_VI_PIPE rpc_cvi_isp_setwdrleonly_1_ViPipe;
	uint8_t  rpc_cvi_isp_setwdrleonly_1_wdrLEOnly;
	uint32_t  *result_155;
	RPC_VI_PIPE rpc_cvi_isp_getframeid_1_ViPipe;
	RPC_CVI_S32  *result_156;
	char *rpc_cvi_isp_setaelogpath_1_fileName;
	RPC_ISP_GET_ATTR_DATA_S  *result_157;
	int rpc_cvi_isp_getaelogpath_1_pathSize;
	RPC_CVI_S32  *result_158;
	char *rpc_cvi_isp_setaelogname_1_fileName;
	RPC_ISP_GET_ATTR_DATA_S  *result_159;
	int rpc_cvi_isp_getaelogname_1_nameSize;
	float  *result_160;
	RPC_VI_PIPE rpc_cvi_isp_queryfps_1_ViPipe;
	RPC_ISP_GET_ATTR_DATA_S  *result_161;
	RPC_VI_PIPE rpc_cvi_isp_getaelogbuf_1_ViPipe;
	RPC_ISP_GET_ATTR_DATA_S  *result_162;
	RPC_VI_PIPE rpc_cvi_isp_getaelogbufsize_1_ViPipe;
	RPC_ISP_GET_ATTR_DATA_S  *result_163;
	RPC_VI_PIPE rpc_cvi_isp_getaebinbuf_1_ViPipe;
	RPC_ISP_GET_ATTR_DATA_S  *result_164;
	RPC_VI_PIPE rpc_cvi_isp_getaebinbufsize_1_ViPipe;
	RPC_ISP_GET_ATTR_DATA_S  *result_165;
	RPC_VI_PIPE rpc_cvi_isp_getcurrentlvx100_1_ViPipe;
	RPC_CVI_S32  *result_166;
	RPC_VI_PIPE rpc_cvi_isp_setfastbootexposure_1_ViPipe;
	uint32_t  rpc_cvi_isp_setfastbootexposure_1_expLine;
	uint32_t  rpc_cvi_isp_setfastbootexposure_1_again;
	uint32_t  rpc_cvi_isp_setfastbootexposure_1_dgain;
	uint32_t  rpc_cvi_isp_setfastbootexposure_1_ispdgain;
	RPC_CVI_S32  *result_167;
	RPC_VI_PIPE rpc_cvi_isp_setsmartexposureattr_1_ViPipe;
	RPC_ISP_SET_ATTR_DATA_S rpc_cvi_isp_setsmartexposureattr_1_stAttrData;
	RPC_ISP_GET_ATTR_DATA_S  *result_168;
	RPC_VI_PIPE rpc_cvi_isp_getsmartexposureattr_1_ViPipe;
	RPC_CVI_S32  *result_169;
	RPC_VI_PIPE rpc_cvi_isp_setwbattr_1_ViPipe;
	RPC_ISP_SET_ATTR_DATA_S rpc_cvi_isp_setwbattr_1_stAttrData;
	RPC_ISP_GET_ATTR_DATA_S  *result_170;
	RPC_VI_PIPE rpc_cvi_isp_getwbattr_1_ViPipe;
	RPC_CVI_S32  *result_171;
	RPC_VI_PIPE rpc_cvi_isp_setawbattrex_1_ViPipe;
	RPC_ISP_SET_ATTR_DATA_S rpc_cvi_isp_setawbattrex_1_stAttrData;
	RPC_ISP_GET_ATTR_DATA_S  *result_172;
	RPC_VI_PIPE rpc_cvi_isp_getawbattrex_1_ViPipe;
	RPC_ISP_GET_ATTR_DATA_S  *result_173;
	RPC_VI_PIPE rpc_cvi_isp_querywbinfo_1_ViPipe;
	RPC_CVI_S32  *result_174;
	RPC_VI_PIPE rpc_cvi_isp_setwbcalibration_1_ViPipe;
	RPC_ISP_SET_ATTR_DATA_S rpc_cvi_isp_setwbcalibration_1_stAttrData;
	RPC_ISP_GET_ATTR_DATA_S  *result_175;
	RPC_VI_PIPE rpc_cvi_isp_getwbcalibration_1_ViPipe;
	RPC_CVI_S32  *result_176;
	RPC_VI_PIPE rpc_cvi_isp_setwbcalibrationex_1_ViPipe;
	RPC_ISP_SET_ATTR_DATA_S rpc_cvi_isp_setwbcalibrationex_1_stAttrData;
	RPC_ISP_GET_ATTR_DATA_S  *result_177;
	RPC_VI_PIPE rpc_cvi_isp_getwbcalibrationex_1_ViPipe;
	RPC_CVI_S32  *result_178;
	RPC_VI_PIPE rpc_cvi_isp_setawbwinstatictics_1_ViPipe;
	RPC_ISP_SET_ATTR_DATA_S rpc_cvi_isp_setawbwinstatictics_1_stAttrData;
	RPC_ISP_GET_ATTR_DATA_S  *result_179;
	RPC_VI_PIPE rpc_cvi_isp_getawbwinstatictics_1_ViPipe;
	RPC_ISP_GET_ATTR_DATA_S  *result_180;
	RPC_VI_PIPE rpc_cvi_isp_getawbsnaplogbuf_1_ViPipe;
	RPC_ISP_GET_ATTR_DATA_S  *result_181;
	RPC_VI_PIPE rpc_cvi_isp_getawbdbgbinbuf_1_ViPipe;
	RPC_CVI_S32  *result_182;
	RPC_ISP_GET_ATTR_DATA_S  *result_183;
	RPC_VI_PIPE rpc_cvi_isp_getawbcurve_1_ViPipe;
	RPC_CVI_S32  *result_184;
	char *rpc_cvi_isp_setawblogpath_1_fileName;
	RPC_CVI_S32  *result_185;
	char *rpc_cvi_isp_setawblogname_1_fileName;

#ifndef	DEBUG
	clnt = clnt_create (host, ISP_RPC, ISP_RPC_VERSION, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = rpc_cvi_isp_setpubattr_1(rpc_cvi_isp_setpubattr_1_ViPipe, rpc_cvi_isp_setpubattr_1_stAttrData, clnt);
	if (result_1 == (RPC_CVI_S32 *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = rpc_cvi_isp_getpubattr_1(rpc_cvi_isp_getpubattr_1_ViPipe, clnt);
	if (result_2 == (RPC_ISP_GET_ATTR_DATA_S *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = rpc_cvi_isp_setmodparam_1(rpc_cvi_isp_setmodparam_1_stAttrData, clnt);
	if (result_3 == (RPC_CVI_S32 *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_4 = rpc_cvi_isp_getmodparam_1(clnt);
	if (result_4 == (RPC_ISP_GET_ATTR_DATA_S *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_5 = rpc_cvi_isp_setctrlparam_1(rpc_cvi_isp_setctrlparam_1_ViPipe, rpc_cvi_isp_setctrlparam_1_stAttrData, clnt);
	if (result_5 == (RPC_CVI_S32 *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_6 = rpc_cvi_isp_getctrlparam_1(rpc_cvi_isp_getctrlparam_1_ViPipe, clnt);
	if (result_6 == (RPC_ISP_GET_ATTR_DATA_S *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_7 = rpc_cvi_isp_setfmwstate_1(rpc_cvi_isp_setfmwstate_1_ViPipe, rpc_cvi_isp_setfmwstate_1_enState, clnt);
	if (result_7 == (RPC_CVI_S32 *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_8 = rpc_cvi_isp_getfmwstate_1(rpc_cvi_isp_getfmwstate_1_ViPipe, clnt);
	if (result_8 == (uint32_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_9 = rpc_cvi_isp_setmodulecontrol_1(rpc_cvi_isp_setmodulecontrol_1_ViPipe, rpc_cvi_isp_setmodulecontrol_1_stAttrData, clnt);
	if (result_9 == (RPC_CVI_S32 *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_10 = rpc_cvi_isp_getmodulecontrol_1(rpc_cvi_isp_getmodulecontrol_1_ViPipe, clnt);
	if (result_10 == (RPC_ISP_GET_ATTR_DATA_S *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_11 = rpc_cvi_isp_setregister_1(rpc_cvi_isp_setregister_1_ViPipe, rpc_cvi_isp_setregister_1_u32Addr, rpc_cvi_isp_setregister_1_u32Value, clnt);
	if (result_11 == (RPC_CVI_S32 *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_12 = rpc_cvi_isp_getregister_1(rpc_cvi_isp_getregister_1_ViPipe, rpc_cvi_isp_getregister_1_u32Addr, clnt);
	if (result_12 == (uint32_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_13 = rpc_cvi_isp_setcolortoneattr_1(rpc_cvi_isp_setcolortoneattr_1_ViPipe, rpc_cvi_isp_setcolortoneattr_1_stAttrData, clnt);
	if (result_13 == (RPC_CVI_S32 *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_14 = rpc_cvi_isp_getcolortoneattr_1(rpc_cvi_isp_getcolortoneattr_1_ViPipe, clnt);
	if (result_14 == (RPC_ISP_GET_ATTR_DATA_S *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_15 = rpc_cvi_isp_setdehazeattr_1(rpc_cvi_isp_setdehazeattr_1_ViPipe, rpc_cvi_isp_setdehazeattr_1_stAttrData, clnt);
	if (result_15 == (RPC_CVI_S32 *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_16 = rpc_cvi_isp_getdehazeattr_1(rpc_cvi_isp_getdehazeattr_1_ViPipe, clnt);
	if (result_16 == (RPC_ISP_GET_ATTR_DATA_S *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_17 = rpc_cvi_isp_setgammaattr_1(rpc_cvi_isp_setgammaattr_1_ViPipe, rpc_cvi_isp_setgammaattr_1_stAttrData, clnt);
	if (result_17 == (RPC_CVI_S32 *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_18 = rpc_cvi_isp_getgammaattr_1(rpc_cvi_isp_getgammaattr_1_ViPipe, clnt);
	if (result_18 == (RPC_ISP_GET_ATTR_DATA_S *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_19 = rpc_cvi_isp_setgammacurvetype_1(rpc_cvi_isp_setgammacurvetype_1_ViPipe, rpc_cvi_isp_setgammacurvetype_1_curveType, clnt);
	if (result_19 == (RPC_CVI_S32 *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_20 = rpc_cvi_isp_setautogammaattr_1(rpc_cvi_isp_setautogammaattr_1_ViPipe, rpc_cvi_isp_setautogammaattr_1_stAttrData, clnt);
	if (result_20 == (RPC_CVI_S32 *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_21 = rpc_cvi_isp_getautogammaattr_1(rpc_cvi_isp_getautogammaattr_1_ViPipe, clnt);
	if (result_21 == (RPC_ISP_GET_ATTR_DATA_S *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_22 = rpc_cvi_isp_setstatisticsconfig_1(rpc_cvi_isp_setstatisticsconfig_1_ViPipe, rpc_cvi_isp_setstatisticsconfig_1_stAttrData, clnt);
	if (result_22 == (RPC_CVI_S32 *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_23 = rpc_cvi_isp_getstatisticsconfig_1(rpc_cvi_isp_getstatisticsconfig_1_ViPipe, clnt);
	if (result_23 == (RPC_ISP_GET_ATTR_DATA_S *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_24 = rpc_cvi_isp_setnrattr_1(rpc_cvi_isp_setnrattr_1_ViPipe, rpc_cvi_isp_setnrattr_1_stAttrData, clnt);
	if (result_24 == (RPC_CVI_S32 *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_25 = rpc_cvi_isp_getnrattr_1(rpc_cvi_isp_getnrattr_1_ViPipe, clnt);
	if (result_25 == (RPC_ISP_GET_ATTR_DATA_S *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_26 = rpc_cvi_isp_setnrfilterattr_1(rpc_cvi_isp_setnrfilterattr_1_ViPipe, rpc_cvi_isp_setnrfilterattr_1_stAttrData, clnt);
	if (result_26 == (RPC_CVI_S32 *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_27 = rpc_cvi_isp_getnrfilterattr_1(rpc_cvi_isp_getnrfilterattr_1_ViPipe, clnt);
	if (result_27 == (RPC_ISP_GET_ATTR_DATA_S *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_28 = rpc_cvi_isp_setrlscattr_1(rpc_cvi_isp_setrlscattr_1_ViPipe, rpc_cvi_isp_setrlscattr_1_stAttrData, clnt);
	if (result_28 == (RPC_CVI_S32 *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_29 = rpc_cvi_isp_getrlscattr_1(rpc_cvi_isp_getrlscattr_1_ViPipe, clnt);
	if (result_29 == (RPC_ISP_GET_ATTR_DATA_S *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_30 = rpc_cvi_isp_setynrattr_1(rpc_cvi_isp_setynrattr_1_ViPipe, rpc_cvi_isp_setynrattr_1_stAttrData, clnt);
	if (result_30 == (RPC_CVI_S32 *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_31 = rpc_cvi_isp_getynrattr_1(rpc_cvi_isp_getynrattr_1_ViPipe, clnt);
	if (result_31 == (RPC_ISP_GET_ATTR_DATA_S *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_32 = rpc_cvi_isp_setynrmotionnrattr_1(rpc_cvi_isp_setynrmotionnrattr_1_ViPipe, rpc_cvi_isp_setynrmotionnrattr_1_stAttrData, clnt);
	if (result_32 == (RPC_CVI_S32 *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_33 = rpc_cvi_isp_getynrmotionnrattr_1(rpc_cvi_isp_getynrmotionnrattr_1_ViPipe, clnt);
	if (result_33 == (RPC_ISP_GET_ATTR_DATA_S *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_34 = rpc_cvi_isp_setynrfilterattr_1(rpc_cvi_isp_setynrfilterattr_1_ViPipe, rpc_cvi_isp_setynrfilterattr_1_stAttrData, clnt);
	if (result_34 == (RPC_CVI_S32 *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_35 = rpc_cvi_isp_getynrfilterattr_1(rpc_cvi_isp_getynrfilterattr_1_ViPipe, clnt);
	if (result_35 == (RPC_ISP_GET_ATTR_DATA_S *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_36 = rpc_cvi_isp_setcnrattr_1(rpc_cvi_isp_setcnrattr_1_ViPipe, rpc_cvi_isp_setcnrattr_1_stAttrData, clnt);
	if (result_36 == (RPC_CVI_S32 *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_37 = rpc_cvi_isp_getcnrattr_1(rpc_cvi_isp_getcnrattr_1_ViPipe, clnt);
	if (result_37 == (RPC_ISP_GET_ATTR_DATA_S *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_38 = rpc_cvi_isp_setcacattr_1(rpc_cvi_isp_setcacattr_1_ViPipe, rpc_cvi_isp_setcacattr_1_stAttrData, clnt);
	if (result_38 == (RPC_CVI_S32 *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_39 = rpc_cvi_isp_getcacattr_1(rpc_cvi_isp_getcacattr_1_ViPipe, clnt);
	if (result_39 == (RPC_ISP_GET_ATTR_DATA_S *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_40 = rpc_cvi_isp_setdciattr_1(rpc_cvi_isp_setdciattr_1_ViPipe, rpc_cvi_isp_setdciattr_1_stAttrData, clnt);
	if (result_40 == (RPC_CVI_S32 *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_41 = rpc_cvi_isp_getdciattr_1(rpc_cvi_isp_getdciattr_1_ViPipe, clnt);
	if (result_41 == (RPC_ISP_GET_ATTR_DATA_S *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_42 = rpc_cvi_isp_setmeshshadingattr_1(rpc_cvi_isp_setmeshshadingattr_1_ViPipe, rpc_cvi_isp_setmeshshadingattr_1_stAttrData, clnt);
	if (result_42 == (RPC_CVI_S32 *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_43 = rpc_cvi_isp_getmeshshadingattr_1(rpc_cvi_isp_getmeshshadingattr_1_ViPipe, clnt);
	if (result_43 == (RPC_ISP_GET_ATTR_DATA_S *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_44 = rpc_cvi_isp_setmeshshadinggainlutattr_1(rpc_cvi_isp_setmeshshadinggainlutattr_1_ViPipe, rpc_cvi_isp_setmeshshadinggainlutattr_1_stAttrData, clnt);
	if (result_44 == (RPC_CVI_S32 *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_45 = rpc_cvi_isp_getmeshshadinggainlutattr_1(rpc_cvi_isp_getmeshshadinggainlutattr_1_ViPipe, clnt);
	if (result_45 == (RPC_ISP_GET_ATTR_DATA_S *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_46 = rpc_cvi_isp_setradialshadingattr_1(rpc_cvi_isp_setradialshadingattr_1_ViPipe, rpc_cvi_isp_setradialshadingattr_1_stAttrData, clnt);
	if (result_46 == (RPC_CVI_S32 *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_47 = rpc_cvi_isp_getradialshadingattr_1(rpc_cvi_isp_getradialshadingattr_1_ViPipe, clnt);
	if (result_47 == (RPC_ISP_GET_ATTR_DATA_S *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_48 = rpc_cvi_isp_setradialshadinggainlutattr_1(rpc_cvi_isp_setradialshadinggainlutattr_1_ViPipe, rpc_cvi_isp_setradialshadinggainlutattr_1_stAttrData, clnt);
	if (result_48 == (RPC_CVI_S32 *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_49 = rpc_cvi_isp_getradialshadinggainlutattr_1(rpc_cvi_isp_getradialshadinggainlutattr_1_ViPipe, clnt);
	if (result_49 == (RPC_ISP_GET_ATTR_DATA_S *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_50 = rpc_cvi_isp_settnrattr_1(rpc_cvi_isp_settnrattr_1_ViPipe, rpc_cvi_isp_settnrattr_1_stAttrData, clnt);
	if (result_50 == (RPC_CVI_S32 *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_51 = rpc_cvi_isp_gettnrattr_1(rpc_cvi_isp_gettnrattr_1_ViPipe, clnt);
	if (result_51 == (RPC_ISP_GET_ATTR_DATA_S *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_52 = rpc_cvi_isp_settnrnoisemodelattr_1(rpc_cvi_isp_settnrnoisemodelattr_1_ViPipe, rpc_cvi_isp_settnrnoisemodelattr_1_stAttrData, clnt);
	if (result_52 == (RPC_CVI_S32 *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_53 = rpc_cvi_isp_gettnrnoisemodelattr_1(rpc_cvi_isp_gettnrnoisemodelattr_1_ViPipe, clnt);
	if (result_53 == (RPC_ISP_GET_ATTR_DATA_S *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_54 = rpc_cvi_isp_settnrlumamotionattr_1(rpc_cvi_isp_settnrlumamotionattr_1_ViPipe, rpc_cvi_isp_settnrlumamotionattr_1_stAttrData, clnt);
	if (result_54 == (RPC_CVI_S32 *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_55 = rpc_cvi_isp_gettnrlumamotionattr_1(rpc_cvi_isp_gettnrlumamotionattr_1_ViPipe, clnt);
	if (result_55 == (RPC_ISP_GET_ATTR_DATA_S *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_56 = rpc_cvi_isp_settnrghostattr_1(rpc_cvi_isp_settnrghostattr_1_ViPipe, rpc_cvi_isp_settnrghostattr_1_stAttrData, clnt);
	if (result_56 == (RPC_CVI_S32 *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_57 = rpc_cvi_isp_gettnrghostattr_1(rpc_cvi_isp_gettnrghostattr_1_ViPipe, clnt);
	if (result_57 == (RPC_ISP_GET_ATTR_DATA_S *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_58 = rpc_cvi_isp_settnrmtprtattr_1(rpc_cvi_isp_settnrmtprtattr_1_ViPipe, rpc_cvi_isp_settnrmtprtattr_1_stAttrData, clnt);
	if (result_58 == (RPC_CVI_S32 *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_59 = rpc_cvi_isp_gettnrmtprtattr_1(rpc_cvi_isp_gettnrmtprtattr_1_ViPipe, clnt);
	if (result_59 == (RPC_ISP_GET_ATTR_DATA_S *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_60 = rpc_cvi_isp_setclutattr_1(rpc_cvi_isp_setclutattr_1_ViPipe, rpc_cvi_isp_setclutattr_1_stAttrData, clnt);
	if (result_60 == (RPC_CVI_S32 *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_61 = rpc_cvi_isp_getclutattr_1(rpc_cvi_isp_getclutattr_1_ViPipe, clnt);
	if (result_61 == (RPC_ISP_GET_ATTR_DATA_S *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_62 = rpc_cvi_isp_setclutcoeff_1(rpc_cvi_isp_setclutcoeff_1_ViPipe, rpc_cvi_isp_setclutcoeff_1_stAttrData, clnt);
	if (result_62 == (RPC_CVI_S32 *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_63 = rpc_cvi_isp_getclutcoeff_1(rpc_cvi_isp_getclutcoeff_1_ViPipe, clnt);
	if (result_63 == (RPC_ISP_GET_ATTR_DATA_S *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_64 = rpc_cvi_isp_setblacklevelattr_1(rpc_cvi_isp_setblacklevelattr_1_ViPipe, rpc_cvi_isp_setblacklevelattr_1_stAttrData, clnt);
	if (result_64 == (RPC_CVI_S32 *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_65 = rpc_cvi_isp_getblacklevelattr_1(rpc_cvi_isp_getblacklevelattr_1_ViPipe, clnt);
	if (result_65 == (RPC_ISP_GET_ATTR_DATA_S *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_66 = rpc_cvi_isp_setdemosaicattr_1(rpc_cvi_isp_setdemosaicattr_1_ViPipe, rpc_cvi_isp_setdemosaicattr_1_stAttrData, clnt);
	if (result_66 == (RPC_CVI_S32 *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_67 = rpc_cvi_isp_getdemosaicattr_1(rpc_cvi_isp_getdemosaicattr_1_ViPipe, clnt);
	if (result_67 == (RPC_ISP_GET_ATTR_DATA_S *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_68 = rpc_cvi_isp_setdemosaicdemoireattr_1(rpc_cvi_isp_setdemosaicdemoireattr_1_ViPipe, rpc_cvi_isp_setdemosaicdemoireattr_1_stAttrData, clnt);
	if (result_68 == (RPC_CVI_S32 *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_69 = rpc_cvi_isp_getdemosaicdemoireattr_1(rpc_cvi_isp_getdemosaicdemoireattr_1_ViPipe, clnt);
	if (result_69 == (RPC_ISP_GET_ATTR_DATA_S *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_70 = rpc_cvi_isp_setdemosaicfilterattr_1(rpc_cvi_isp_setdemosaicfilterattr_1_ViPipe, rpc_cvi_isp_setdemosaicfilterattr_1_stAttrData, clnt);
	if (result_70 == (RPC_CVI_S32 *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_71 = rpc_cvi_isp_getdemosaicfilterattr_1(rpc_cvi_isp_getdemosaicfilterattr_1_ViPipe, clnt);
	if (result_71 == (RPC_ISP_GET_ATTR_DATA_S *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_72 = rpc_cvi_isp_setdemosaiceeattr_1(rpc_cvi_isp_setdemosaiceeattr_1_ViPipe, rpc_cvi_isp_setdemosaiceeattr_1_stAttrData, clnt);
	if (result_72 == (RPC_CVI_S32 *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_73 = rpc_cvi_isp_getdemosaiceeattr_1(rpc_cvi_isp_getdemosaiceeattr_1_ViPipe, clnt);
	if (result_73 == (RPC_ISP_GET_ATTR_DATA_S *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_74 = rpc_cvi_isp_setsaturationattr_1(rpc_cvi_isp_setsaturationattr_1_ViPipe, rpc_cvi_isp_setsaturationattr_1_stAttrData, clnt);
	if (result_74 == (RPC_CVI_S32 *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_75 = rpc_cvi_isp_getsaturationattr_1(rpc_cvi_isp_getsaturationattr_1_ViPipe, clnt);
	if (result_75 == (RPC_ISP_GET_ATTR_DATA_S *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_76 = rpc_cvi_isp_setccmattr_1(rpc_cvi_isp_setccmattr_1_ViPipe, rpc_cvi_isp_setccmattr_1_stAttrData, clnt);
	if (result_76 == (RPC_CVI_S32 *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_77 = rpc_cvi_isp_getccmattr_1(rpc_cvi_isp_getccmattr_1_ViPipe, clnt);
	if (result_77 == (RPC_ISP_GET_ATTR_DATA_S *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_78 = rpc_cvi_isp_sethsvattr_1(rpc_cvi_isp_sethsvattr_1_ViPipe, rpc_cvi_isp_sethsvattr_1_stAttrData, clnt);
	if (result_78 == (RPC_CVI_S32 *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_79 = rpc_cvi_isp_gethsvattr_1(rpc_cvi_isp_gethsvattr_1_ViPipe, clnt);
	if (result_79 == (RPC_ISP_GET_ATTR_DATA_S *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_80 = rpc_cvi_isp_setdpdynamicattr_1(rpc_cvi_isp_setdpdynamicattr_1_ViPipe, rpc_cvi_isp_setdpdynamicattr_1_stAttrData, clnt);
	if (result_80 == (RPC_CVI_S32 *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_81 = rpc_cvi_isp_getdpdynamicattr_1(rpc_cvi_isp_getdpdynamicattr_1_ViPipe, clnt);
	if (result_81 == (RPC_ISP_GET_ATTR_DATA_S *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_82 = rpc_cvi_isp_setdpstaticattr_1(rpc_cvi_isp_setdpstaticattr_1_ViPipe, rpc_cvi_isp_setdpstaticattr_1_stAttrData, clnt);
	if (result_82 == (RPC_CVI_S32 *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_83 = rpc_cvi_isp_getdpstaticattr_1(rpc_cvi_isp_getdpstaticattr_1_ViPipe, clnt);
	if (result_83 == (RPC_ISP_GET_ATTR_DATA_S *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_84 = rpc_cvi_isp_setdpcalibrate_1(rpc_cvi_isp_setdpcalibrate_1_ViPipe, rpc_cvi_isp_setdpcalibrate_1_stAttrData, clnt);
	if (result_84 == (RPC_CVI_S32 *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_85 = rpc_cvi_isp_getdpcalibrate_1(rpc_cvi_isp_getdpcalibrate_1_ViPipe, clnt);
	if (result_85 == (RPC_ISP_GET_ATTR_DATA_S *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_86 = rpc_cvi_isp_setcrosstalkattr_1(rpc_cvi_isp_setcrosstalkattr_1_ViPipe, rpc_cvi_isp_setcrosstalkattr_1_stAttrData, clnt);
	if (result_86 == (RPC_CVI_S32 *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_87 = rpc_cvi_isp_getcrosstalkattr_1(rpc_cvi_isp_getcrosstalkattr_1_ViPipe, clnt);
	if (result_87 == (RPC_ISP_GET_ATTR_DATA_S *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_88 = rpc_cvi_isp_getaestatistics_1(rpc_cvi_isp_getaestatistics_1_ViPipe, clnt);
	if (result_88 == (RPC_ISP_GET_ATTR_DATA_S *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_89 = rpc_cvi_isp_getwbstatistics_1(rpc_cvi_isp_getwbstatistics_1_ViPipe, clnt);
	if (result_89 == (RPC_ISP_GET_ATTR_DATA_S *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_90 = rpc_cvi_isp_getfocusstatistics_1(rpc_cvi_isp_getfocusstatistics_1_ViPipe, clnt);
	if (result_90 == (RPC_ISP_GET_ATTR_DATA_S *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_91 = rpc_cvi_isp_getlightboxgain_1(rpc_cvi_isp_getlightboxgain_1_ViPipe, clnt);
	if (result_91 == (RPC_ISP_GET_ATTR_DATA_S *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_92 = rpc_cvi_isp_setfswdrattr_1(rpc_cvi_isp_setfswdrattr_1_ViPipe, rpc_cvi_isp_setfswdrattr_1_stAttrData, clnt);
	if (result_92 == (RPC_CVI_S32 *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_93 = rpc_cvi_isp_getfswdrattr_1(rpc_cvi_isp_getfswdrattr_1_ViPipe, clnt);
	if (result_93 == (RPC_ISP_GET_ATTR_DATA_S *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_94 = rpc_cvi_isp_setdrcattr_1(rpc_cvi_isp_setdrcattr_1_ViPipe, rpc_cvi_isp_setdrcattr_1_stAttrData, clnt);
	if (result_94 == (RPC_CVI_S32 *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_95 = rpc_cvi_isp_getdrcattr_1(rpc_cvi_isp_getdrcattr_1_ViPipe, clnt);
	if (result_95 == (RPC_ISP_GET_ATTR_DATA_S *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_96 = rpc_cvi_isp_setsharpenattr_1(rpc_cvi_isp_setsharpenattr_1_ViPipe, rpc_cvi_isp_setsharpenattr_1_stAttrData, clnt);
	if (result_96 == (RPC_CVI_S32 *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_97 = rpc_cvi_isp_getsharpenattr_1(rpc_cvi_isp_getsharpenattr_1_ViPipe, clnt);
	if (result_97 == (RPC_ISP_GET_ATTR_DATA_S *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_98 = rpc_cvi_isp_setnoiseprofileattr_1(rpc_cvi_isp_setnoiseprofileattr_1_ViPipe, rpc_cvi_isp_setnoiseprofileattr_1_stAttrData, clnt);
	if (result_98 == (RPC_CVI_S32 *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_99 = rpc_cvi_isp_getnoiseprofileattr_1(rpc_cvi_isp_getnoiseprofileattr_1_ViPipe, clnt);
	if (result_99 == (RPC_ISP_GET_ATTR_DATA_S *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_100 = rpc_cvi_isp_setycontrastattr_1(rpc_cvi_isp_setycontrastattr_1_ViPipe, rpc_cvi_isp_setycontrastattr_1_stAttrData, clnt);
	if (result_100 == (RPC_CVI_S32 *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_101 = rpc_cvi_isp_getycontrastattr_1(rpc_cvi_isp_getycontrastattr_1_ViPipe, clnt);
	if (result_101 == (RPC_ISP_GET_ATTR_DATA_S *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_102 = rpc_cvi_isp_setdcfinfo_1(rpc_cvi_isp_setdcfinfo_1_ViPipe, rpc_cvi_isp_setdcfinfo_1_stAttrData, clnt);
	if (result_102 == (RPC_CVI_S32 *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_103 = rpc_cvi_isp_getdcfinfo_1(rpc_cvi_isp_getdcfinfo_1_ViPipe, clnt);
	if (result_103 == (RPC_ISP_GET_ATTR_DATA_S *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_104 = rpc_cvi_isp_queryinnerstateinfo_1(rpc_cvi_isp_queryinnerstateinfo_1_ViPipe, clnt);
	if (result_104 == (RPC_ISP_GET_ATTR_DATA_S *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_105 = rpc_cvi_isp_getvdtimeout_1(rpc_cvi_isp_getvdtimeout_1_ViPipe, rpc_cvi_isp_getvdtimeout_1_enIspVDType, rpc_cvi_isp_getvdtimeout_1_u32MilliSec, clnt);
	if (result_105 == (RPC_CVI_S32 *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_106 = rpc_cvi_isp_setmonoattr_1(rpc_cvi_isp_setmonoattr_1_ViPipe, rpc_cvi_isp_setmonoattr_1_stAttrData, clnt);
	if (result_106 == (RPC_CVI_S32 *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_107 = rpc_cvi_isp_getmonoattr_1(rpc_cvi_isp_getmonoattr_1_ViPipe, clnt);
	if (result_107 == (RPC_ISP_GET_ATTR_DATA_S *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_108 = rpc_cvi_isp_setdisattr_1(rpc_cvi_isp_setdisattr_1_ViPipe, rpc_cvi_isp_setdisattr_1_stAttrData, clnt);
	if (result_108 == (RPC_CVI_S32 *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_109 = rpc_cvi_isp_getdisattr_1(rpc_cvi_isp_getdisattr_1_ViPipe, clnt);
	if (result_109 == (RPC_ISP_GET_ATTR_DATA_S *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_110 = rpc_cvi_isp_setdisconfig_1(rpc_cvi_isp_setdisconfig_1_ViPipe, rpc_cvi_isp_setdisconfig_1_stAttrData, clnt);
	if (result_110 == (RPC_CVI_S32 *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_111 = rpc_cvi_isp_getdisconfig_1(rpc_cvi_isp_getdisconfig_1_ViPipe, clnt);
	if (result_111 == (RPC_ISP_GET_ATTR_DATA_S *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_112 = rpc_cvi_isp_getbinstatus_1(rpc_cvi_isp_getbinstatus_1_ViPipe, clnt);
	if (result_112 == (RPC_CVI_S32 *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_113 = rpc_cvi_isp_setvcattr_1(rpc_cvi_isp_setvcattr_1_ViPipe, rpc_cvi_isp_setvcattr_1_stAttrData, clnt);
	if (result_113 == (RPC_CVI_S32 *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_114 = rpc_cvi_isp_getvcattr_1(rpc_cvi_isp_getvcattr_1_ViPipe, clnt);
	if (result_114 == (RPC_ISP_GET_ATTR_DATA_S *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_115 = rpc_cvi_isp_dumphwregistertofile_1(rpc_cvi_isp_dumphwregistertofile_1_ViPipe, rpc_cvi_isp_dumphwregistertofile_1_fileName, clnt);
	if (result_115 == (RPC_CVI_S32 *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_116 = rpc_cvi_isp_dumpframerawinfotofile_1(rpc_cvi_isp_dumpframerawinfotofile_1_ViPipe, rpc_cvi_isp_dumpframerawinfotofile_1_fileName, clnt);
	if (result_116 == (RPC_CVI_S32 *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_117 = rpc_cvi_isp_irautorunonce_1(rpc_cvi_isp_irautorunonce_1_IspDev, rpc_cvi_isp_irautorunonce_1_stAttrData, clnt);
	if (result_117 == (RPC_ISP_GET_ATTR_DATA_S *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_118 = rpc_cvi_isp_setsmartinfo_1(rpc_cvi_isp_setsmartinfo_1_ViPipe, rpc_cvi_isp_setsmartinfo_1_stAttrData, rpc_cvi_isp_setsmartinfo_1_TimeOut, clnt);
	if (result_118 == (RPC_CVI_S32 *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_119 = rpc_cvi_isp_getsmartinfo_1(rpc_cvi_isp_getsmartinfo_1_ViPipe, clnt);
	if (result_119 == (RPC_ISP_GET_ATTR_DATA_S *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_120 = rpc_cvi_isp_settnrmotionadaptattr_1(rpc_cvi_isp_settnrmotionadaptattr_1_ViPipe, rpc_cvi_isp_settnrmotionadaptattr_1_stAttrData, clnt);
	if (result_120 == (RPC_CVI_S32 *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_121 = rpc_cvi_isp_gettnrmotionadaptattr_1(rpc_cvi_isp_gettnrmotionadaptattr_1_ViPipe, clnt);
	if (result_121 == (RPC_ISP_GET_ATTR_DATA_S *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_122 = rpc_cvi_isp_setclutsaturationattr_1(rpc_cvi_isp_setclutsaturationattr_1_ViPipe, rpc_cvi_isp_setclutsaturationattr_1_stAttrData, clnt);
	if (result_122 == (RPC_CVI_S32 *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_123 = rpc_cvi_isp_getclutsaturationattr_1(rpc_cvi_isp_getclutsaturationattr_1_ViPipe, clnt);
	if (result_123 == (RPC_ISP_GET_ATTR_DATA_S *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_124 = rpc_cvi_isp_getgammacurvebytype_1(rpc_cvi_isp_getgammacurvebytype_1_ViPipe, rpc_cvi_isp_getgammacurvebytype_1_curveType, clnt);
	if (result_124 == (RPC_ISP_GET_ATTR_DATA_S *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_125 = rpc_cvi_isp_setpresharpenattr_1(rpc_cvi_isp_setpresharpenattr_1_ViPipe, rpc_cvi_isp_setpresharpenattr_1_stAttrData, clnt);
	if (result_125 == (RPC_CVI_S32 *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_126 = rpc_cvi_isp_getpresharpenattr_1(rpc_cvi_isp_getpresharpenattr_1_ViPipe, clnt);
	if (result_126 == (RPC_ISP_GET_ATTR_DATA_S *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_127 = rpc_cvi_isp_setrgbcacattr_1(rpc_cvi_isp_setrgbcacattr_1_ViPipe, rpc_cvi_isp_setrgbcacattr_1_stAttrData, clnt);
	if (result_127 == (RPC_CVI_S32 *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_128 = rpc_cvi_isp_getrgbcacattr_1(rpc_cvi_isp_getrgbcacattr_1_ViPipe, clnt);
	if (result_128 == (RPC_ISP_GET_ATTR_DATA_S *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_129 = rpc_cvi_isp_setcnrmotionnrattr_1(rpc_cvi_isp_setcnrmotionnrattr_1_ViPipe, rpc_cvi_isp_setcnrmotionnrattr_1_stAttrData, clnt);
	if (result_129 == (RPC_CVI_S32 *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_130 = rpc_cvi_isp_getcnrmotionnrattr_1(rpc_cvi_isp_getcnrmotionnrattr_1_ViPipe, clnt);
	if (result_130 == (RPC_ISP_GET_ATTR_DATA_S *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_131 = rpc_cvi_isp_setccmsaturationattr_1(rpc_cvi_isp_setccmsaturationattr_1_ViPipe, rpc_cvi_isp_setccmsaturationattr_1_stAttrData, clnt);
	if (result_131 == (RPC_CVI_S32 *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_132 = rpc_cvi_isp_getccmsaturationattr_1(rpc_cvi_isp_getccmsaturationattr_1_ViPipe, clnt);
	if (result_132 == (RPC_ISP_GET_ATTR_DATA_S *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_133 = rpc_cvi_isp_setcaattr_1(rpc_cvi_isp_setcaattr_1_ViPipe, rpc_cvi_isp_setcaattr_1_stAttrData, clnt);
	if (result_133 == (RPC_CVI_S32 *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_134 = rpc_cvi_isp_getcaattr_1(rpc_cvi_isp_getcaattr_1_ViPipe, clnt);
	if (result_134 == (RPC_ISP_GET_ATTR_DATA_S *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_135 = rpc_cvi_isp_setcscattr_1(rpc_cvi_isp_setcscattr_1_ViPipe, rpc_cvi_isp_setcscattr_1_stAttrData, clnt);
	if (result_135 == (RPC_CVI_S32 *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_136 = rpc_cvi_isp_getcscattr_1(rpc_cvi_isp_getcscattr_1_ViPipe, clnt);
	if (result_136 == (RPC_ISP_GET_ATTR_DATA_S *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_137 = rpc_cvi_isp_setexposureattr_1(rpc_cvi_isp_setexposureattr_1_ViPipe, rpc_cvi_isp_setexposureattr_1_stAttrData, clnt);
	if (result_137 == (RPC_CVI_S32 *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_138 = rpc_cvi_isp_getexposureattr_1(rpc_cvi_isp_getexposureattr_1_ViPipe, clnt);
	if (result_138 == (RPC_ISP_GET_ATTR_DATA_S *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_139 = rpc_cvi_isp_queryexposureinfo_1(rpc_cvi_isp_queryexposureinfo_1_ViPipe, clnt);
	if (result_139 == (RPC_ISP_GET_ATTR_DATA_S *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_140 = rpc_cvi_isp_setwdrexposureattr_1(rpc_cvi_isp_setwdrexposureattr_1_ViPipe, rpc_cvi_isp_setwdrexposureattr_1_stAttrData, clnt);
	if (result_140 == (RPC_CVI_S32 *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_141 = rpc_cvi_isp_getwdrexposureattr_1(rpc_cvi_isp_getwdrexposureattr_1_ViPipe, clnt);
	if (result_141 == (RPC_ISP_GET_ATTR_DATA_S *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_142 = rpc_cvi_isp_setaerouteattr_1(rpc_cvi_isp_setaerouteattr_1_ViPipe, rpc_cvi_isp_setaerouteattr_1_stAttrData, clnt);
	if (result_142 == (RPC_CVI_S32 *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_143 = rpc_cvi_isp_getaerouteattr_1(rpc_cvi_isp_getaerouteattr_1_ViPipe, clnt);
	if (result_143 == (RPC_ISP_GET_ATTR_DATA_S *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_144 = rpc_cvi_isp_setaerouteattrex_1(rpc_cvi_isp_setaerouteattrex_1_ViPipe, rpc_cvi_isp_setaerouteattrex_1_stAttrData, clnt);
	if (result_144 == (RPC_CVI_S32 *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_145 = rpc_cvi_isp_getaerouteattrex_1(rpc_cvi_isp_getaerouteattrex_1_ViPipe, clnt);
	if (result_145 == (RPC_ISP_GET_ATTR_DATA_S *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_146 = rpc_cvi_isp_aebracketingstart_1(rpc_cvi_isp_aebracketingstart_1_ViPipe, clnt);
	if (result_146 == (RPC_CVI_S32 *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_147 = rpc_cvi_isp_aebracketingsetexpsoure_1(rpc_cvi_isp_aebracketingsetexpsoure_1_ViPipe, rpc_cvi_isp_aebracketingsetexpsoure_1_leEvX10, rpc_cvi_isp_aebracketingsetexpsoure_1_seEvX10, clnt);
	if (result_147 == (RPC_CVI_S32 *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_148 = rpc_cvi_isp_aebracketingfinish_1(rpc_cvi_isp_aebracketingfinish_1_ViPipe, clnt);
	if (result_148 == (RPC_CVI_S32 *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_149 = rpc_cvi_isp_aebracketingsetsimple_1(rpc_cvi_isp_aebracketingsetsimple_1_enable, clnt);
	if (result_149 == (RPC_CVI_S32 *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_150 = rpc_cvi_isp_setaestatisticsconfig_1(rpc_cvi_isp_setaestatisticsconfig_1_ViPipe, rpc_cvi_isp_setaestatisticsconfig_1_stAttrData, clnt);
	if (result_150 == (RPC_CVI_S32 *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_151 = rpc_cvi_isp_getaestatisticsconfig_1(rpc_cvi_isp_getaestatisticsconfig_1_ViPipe, clnt);
	if (result_151 == (RPC_ISP_GET_ATTR_DATA_S *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_152 = rpc_cvi_isp_setantiflicker_1(rpc_cvi_isp_setantiflicker_1_ViPipe, rpc_cvi_isp_setantiflicker_1_enable, rpc_cvi_isp_setantiflicker_1_frequency, clnt);
	if (result_152 == (RPC_CVI_S32 *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_153 = rpc_cvi_isp_getantiflicker_1(rpc_cvi_isp_getantiflicker_1_ViPipe, clnt);
	if (result_153 == (uint32_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_154 = rpc_cvi_isp_setwdrleonly_1(rpc_cvi_isp_setwdrleonly_1_ViPipe, rpc_cvi_isp_setwdrleonly_1_wdrLEOnly, clnt);
	if (result_154 == (RPC_CVI_S32 *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_155 = rpc_cvi_isp_getframeid_1(rpc_cvi_isp_getframeid_1_ViPipe, clnt);
	if (result_155 == (uint32_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_156 = rpc_cvi_isp_setaelogpath_1(rpc_cvi_isp_setaelogpath_1_fileName, clnt);
	if (result_156 == (RPC_CVI_S32 *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_157 = rpc_cvi_isp_getaelogpath_1(rpc_cvi_isp_getaelogpath_1_pathSize, clnt);
	if (result_157 == (RPC_ISP_GET_ATTR_DATA_S *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_158 = rpc_cvi_isp_setaelogname_1(rpc_cvi_isp_setaelogname_1_fileName, clnt);
	if (result_158 == (RPC_CVI_S32 *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_159 = rpc_cvi_isp_getaelogname_1(rpc_cvi_isp_getaelogname_1_nameSize, clnt);
	if (result_159 == (RPC_ISP_GET_ATTR_DATA_S *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_160 = rpc_cvi_isp_queryfps_1(rpc_cvi_isp_queryfps_1_ViPipe, clnt);
	if (result_160 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_161 = rpc_cvi_isp_getaelogbuf_1(rpc_cvi_isp_getaelogbuf_1_ViPipe, clnt);
	if (result_161 == (RPC_ISP_GET_ATTR_DATA_S *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_162 = rpc_cvi_isp_getaelogbufsize_1(rpc_cvi_isp_getaelogbufsize_1_ViPipe, clnt);
	if (result_162 == (RPC_ISP_GET_ATTR_DATA_S *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_163 = rpc_cvi_isp_getaebinbuf_1(rpc_cvi_isp_getaebinbuf_1_ViPipe, clnt);
	if (result_163 == (RPC_ISP_GET_ATTR_DATA_S *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_164 = rpc_cvi_isp_getaebinbufsize_1(rpc_cvi_isp_getaebinbufsize_1_ViPipe, clnt);
	if (result_164 == (RPC_ISP_GET_ATTR_DATA_S *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_165 = rpc_cvi_isp_getcurrentlvx100_1(rpc_cvi_isp_getcurrentlvx100_1_ViPipe, clnt);
	if (result_165 == (RPC_ISP_GET_ATTR_DATA_S *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_166 = rpc_cvi_isp_setfastbootexposure_1(rpc_cvi_isp_setfastbootexposure_1_ViPipe, rpc_cvi_isp_setfastbootexposure_1_expLine, rpc_cvi_isp_setfastbootexposure_1_again, rpc_cvi_isp_setfastbootexposure_1_dgain, rpc_cvi_isp_setfastbootexposure_1_ispdgain, clnt);
	if (result_166 == (RPC_CVI_S32 *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_167 = rpc_cvi_isp_setsmartexposureattr_1(rpc_cvi_isp_setsmartexposureattr_1_ViPipe, rpc_cvi_isp_setsmartexposureattr_1_stAttrData, clnt);
	if (result_167 == (RPC_CVI_S32 *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_168 = rpc_cvi_isp_getsmartexposureattr_1(rpc_cvi_isp_getsmartexposureattr_1_ViPipe, clnt);
	if (result_168 == (RPC_ISP_GET_ATTR_DATA_S *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_169 = rpc_cvi_isp_setwbattr_1(rpc_cvi_isp_setwbattr_1_ViPipe, rpc_cvi_isp_setwbattr_1_stAttrData, clnt);
	if (result_169 == (RPC_CVI_S32 *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_170 = rpc_cvi_isp_getwbattr_1(rpc_cvi_isp_getwbattr_1_ViPipe, clnt);
	if (result_170 == (RPC_ISP_GET_ATTR_DATA_S *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_171 = rpc_cvi_isp_setawbattrex_1(rpc_cvi_isp_setawbattrex_1_ViPipe, rpc_cvi_isp_setawbattrex_1_stAttrData, clnt);
	if (result_171 == (RPC_CVI_S32 *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_172 = rpc_cvi_isp_getawbattrex_1(rpc_cvi_isp_getawbattrex_1_ViPipe, clnt);
	if (result_172 == (RPC_ISP_GET_ATTR_DATA_S *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_173 = rpc_cvi_isp_querywbinfo_1(rpc_cvi_isp_querywbinfo_1_ViPipe, clnt);
	if (result_173 == (RPC_ISP_GET_ATTR_DATA_S *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_174 = rpc_cvi_isp_setwbcalibration_1(rpc_cvi_isp_setwbcalibration_1_ViPipe, rpc_cvi_isp_setwbcalibration_1_stAttrData, clnt);
	if (result_174 == (RPC_CVI_S32 *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_175 = rpc_cvi_isp_getwbcalibration_1(rpc_cvi_isp_getwbcalibration_1_ViPipe, clnt);
	if (result_175 == (RPC_ISP_GET_ATTR_DATA_S *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_176 = rpc_cvi_isp_setwbcalibrationex_1(rpc_cvi_isp_setwbcalibrationex_1_ViPipe, rpc_cvi_isp_setwbcalibrationex_1_stAttrData, clnt);
	if (result_176 == (RPC_CVI_S32 *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_177 = rpc_cvi_isp_getwbcalibrationex_1(rpc_cvi_isp_getwbcalibrationex_1_ViPipe, clnt);
	if (result_177 == (RPC_ISP_GET_ATTR_DATA_S *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_178 = rpc_cvi_isp_setawbwinstatictics_1(rpc_cvi_isp_setawbwinstatictics_1_ViPipe, rpc_cvi_isp_setawbwinstatictics_1_stAttrData, clnt);
	if (result_178 == (RPC_CVI_S32 *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_179 = rpc_cvi_isp_getawbwinstatictics_1(rpc_cvi_isp_getawbwinstatictics_1_ViPipe, clnt);
	if (result_179 == (RPC_ISP_GET_ATTR_DATA_S *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_180 = rpc_cvi_isp_getawbsnaplogbuf_1(rpc_cvi_isp_getawbsnaplogbuf_1_ViPipe, clnt);
	if (result_180 == (RPC_ISP_GET_ATTR_DATA_S *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_181 = rpc_cvi_isp_getawbdbgbinbuf_1(rpc_cvi_isp_getawbdbgbinbuf_1_ViPipe, clnt);
	if (result_181 == (RPC_ISP_GET_ATTR_DATA_S *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_182 = rpc_cvi_isp_getawbdbgbinsize_1(clnt);
	if (result_182 == (RPC_CVI_S32 *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_183 = rpc_cvi_isp_getawbcurve_1(rpc_cvi_isp_getawbcurve_1_ViPipe, clnt);
	if (result_183 == (RPC_ISP_GET_ATTR_DATA_S *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_184 = rpc_cvi_isp_setawblogpath_1(rpc_cvi_isp_setawblogpath_1_fileName, clnt);
	if (result_184 == (RPC_CVI_S32 *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_185 = rpc_cvi_isp_setawblogname_1(rpc_cvi_isp_setawblogname_1_fileName, clnt);
	if (result_185 == (RPC_CVI_S32 *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	isp_rpc_1 (host);
exit (0);
}
