/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "isp_rpc.h"

RPC_CVI_S32 *
rpc_cvi_isp_setpubattr_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getpubattr_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setmodparam_1_svc(RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getmodparam_1_svc(struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setctrlparam_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getctrlparam_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setfmwstate_1_svc(RPC_VI_PIPE ViPipe, uint32_t enState,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */

	return &result;
}

uint32_t *
rpc_cvi_isp_getfmwstate_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static uint32_t  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setmodulecontrol_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getmodulecontrol_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setregister_1_svc(RPC_VI_PIPE ViPipe, uint32_t u32Addr, uint32_t u32Value,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */

	return &result;
}

uint32_t *
rpc_cvi_isp_getregister_1_svc(RPC_VI_PIPE ViPipe, uint32_t u32Addr,  struct svc_req *rqstp)
{
	static uint32_t  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setcolortoneattr_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getcolortoneattr_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setdehazeattr_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getdehazeattr_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setgammaattr_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getgammaattr_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setgammacurvetype_1_svc(RPC_VI_PIPE ViPipe, uint32_t curveType,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setautogammaattr_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getautogammaattr_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setstatisticsconfig_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getstatisticsconfig_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setnrattr_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getnrattr_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setnrfilterattr_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getnrfilterattr_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setrlscattr_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getrlscattr_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setynrattr_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getynrattr_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setynrmotionnrattr_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getynrmotionnrattr_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setynrfilterattr_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getynrfilterattr_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setcnrattr_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getcnrattr_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setcacattr_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getcacattr_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setdciattr_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getdciattr_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setmeshshadingattr_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getmeshshadingattr_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setmeshshadinggainlutattr_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getmeshshadinggainlutattr_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setradialshadingattr_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getradialshadingattr_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setradialshadinggainlutattr_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getradialshadinggainlutattr_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_settnrattr_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_gettnrattr_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_settnrnoisemodelattr_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_gettnrnoisemodelattr_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_settnrlumamotionattr_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_gettnrlumamotionattr_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_settnrghostattr_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_gettnrghostattr_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_settnrmtprtattr_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_gettnrmtprtattr_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setclutattr_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getclutattr_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setclutcoeff_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getclutcoeff_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setblacklevelattr_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getblacklevelattr_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setdemosaicattr_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getdemosaicattr_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setdemosaicdemoireattr_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getdemosaicdemoireattr_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setdemosaicfilterattr_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getdemosaicfilterattr_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setdemosaiceeattr_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getdemosaiceeattr_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setsaturationattr_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getsaturationattr_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setccmattr_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getccmattr_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_sethsvattr_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_gethsvattr_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setdpdynamicattr_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getdpdynamicattr_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setdpstaticattr_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getdpstaticattr_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setdpcalibrate_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getdpcalibrate_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setcrosstalkattr_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getcrosstalkattr_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getaestatistics_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getwbstatistics_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getfocusstatistics_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getlightboxgain_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setfswdrattr_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getfswdrattr_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setdrcattr_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getdrcattr_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setsharpenattr_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getsharpenattr_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setnoiseprofileattr_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getnoiseprofileattr_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setycontrastattr_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getycontrastattr_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setdcfinfo_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getdcfinfo_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_queryinnerstateinfo_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_getvdtimeout_1_svc(RPC_VI_PIPE ViPipe, uint32_t enIspVDType, uint32_t u32MilliSec,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setmonoattr_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getmonoattr_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setdisattr_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getdisattr_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setdisconfig_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getdisconfig_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_getbinstatus_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setvcattr_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getvcattr_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_dumphwregistertofile_1_svc(RPC_VI_PIPE ViPipe, char *fileName,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_dumpframerawinfotofile_1_svc(RPC_VI_PIPE ViPipe, char *fileName,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_irautorunonce_1_svc(uint32_t IspDev, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setsmartinfo_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData, uint8_t TimeOut,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getsmartinfo_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_settnrmotionadaptattr_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_gettnrmotionadaptattr_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setclutsaturationattr_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getclutsaturationattr_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getgammacurvebytype_1_svc(RPC_VI_PIPE ViPipe, uint32_t curveType,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setpresharpenattr_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getpresharpenattr_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setrgbcacattr_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getrgbcacattr_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setcnrmotionnrattr_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getcnrmotionnrattr_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setccmsaturationattr_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getccmsaturationattr_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setcaattr_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getcaattr_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setcscattr_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getcscattr_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setexposureattr_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getexposureattr_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_queryexposureinfo_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setwdrexposureattr_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getwdrexposureattr_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setaerouteattr_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getaerouteattr_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setaerouteattrex_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getaerouteattrex_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_aebracketingstart_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_aebracketingsetexpsoure_1_svc(RPC_VI_PIPE ViPipe, int leEvX10, int seEvX10,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_aebracketingfinish_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_aebracketingsetsimple_1_svc(uint8_t enable,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setaestatisticsconfig_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getaestatisticsconfig_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setantiflicker_1_svc(RPC_VI_PIPE ViPipe, uint8_t enable, uint8_t frequency,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */

	return &result;
}

uint32_t *
rpc_cvi_isp_getantiflicker_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static uint32_t  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setwdrleonly_1_svc(RPC_VI_PIPE ViPipe, uint8_t wdrLEOnly,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */

	return &result;
}

uint32_t *
rpc_cvi_isp_getframeid_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static uint32_t  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setaelogpath_1_svc(char *fileName,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getaelogpath_1_svc(int pathSize,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setaelogname_1_svc(char *fileName,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getaelogname_1_svc(int nameSize,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */

	return &result;
}

float *
rpc_cvi_isp_queryfps_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static float  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getaelogbuf_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getaelogbufsize_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getaebinbuf_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getaebinbufsize_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getcurrentlvx100_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setfastbootexposure_1_svc(RPC_VI_PIPE ViPipe, uint32_t expLine, uint32_t again, uint32_t dgain, uint32_t ispdgain,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setsmartexposureattr_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getsmartexposureattr_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setwbattr_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getwbattr_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setawbattrex_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getawbattrex_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_querywbinfo_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setwbcalibration_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getwbcalibration_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setwbcalibrationex_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getwbcalibrationex_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setawbwinstatictics_1_svc(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getawbwinstatictics_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getawbsnaplogbuf_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getawbdbgbinbuf_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_getawbdbgbinsize_1_svc(struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getawbcurve_1_svc(RPC_VI_PIPE ViPipe,  struct svc_req *rqstp)
{
	static RPC_ISP_GET_ATTR_DATA_S  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setawblogpath_1_svc(char *fileName,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */

	return &result;
}

RPC_CVI_S32 *
rpc_cvi_isp_setawblogname_1_svc(char *fileName,  struct svc_req *rqstp)
{
	static RPC_CVI_S32  result;

	/*
	 * insert server code here
	 */

	return &result;
}
