/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "isp_rpc.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

RPC_CVI_S32 *
rpc_cvi_isp_setpubattr_1(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  CLIENT *clnt)
{
	rpc_cvi_isp_setpubattr_1_argument arg;
	static RPC_CVI_S32 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.ViPipe = ViPipe;
	arg.stAttrData = stAttrData;
	if (clnt_call (clnt, RPC_CVI_ISP_SetPubAttr, (xdrproc_t) xdr_rpc_cvi_isp_setpubattr_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_RPC_CVI_S32, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getpubattr_1(RPC_VI_PIPE ViPipe,  CLIENT *clnt)
{
	static RPC_ISP_GET_ATTR_DATA_S clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RPC_CVI_ISP_GetPubAttr,
		(xdrproc_t) xdr_RPC_VI_PIPE, (caddr_t) &ViPipe,
		(xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_CVI_S32 *
rpc_cvi_isp_setmodparam_1(RPC_ISP_SET_ATTR_DATA_S stAttrData,  CLIENT *clnt)
{
	static RPC_CVI_S32 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RPC_CVI_ISP_SetModParam,
		(xdrproc_t) xdr_RPC_ISP_SET_ATTR_DATA_S, (caddr_t) &stAttrData,
		(xdrproc_t) xdr_RPC_CVI_S32, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getmodparam_1(CLIENT *clnt)
{
	static RPC_ISP_GET_ATTR_DATA_S clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	 if (clnt_call (clnt, RPC_CVI_ISP_GetModParam, (xdrproc_t) xdr_void, (caddr_t) NULL,
		(xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_CVI_S32 *
rpc_cvi_isp_setctrlparam_1(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  CLIENT *clnt)
{
	rpc_cvi_isp_setctrlparam_1_argument arg;
	static RPC_CVI_S32 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.ViPipe = ViPipe;
	arg.stAttrData = stAttrData;
	if (clnt_call (clnt, RPC_CVI_ISP_SetCtrlParam, (xdrproc_t) xdr_rpc_cvi_isp_setctrlparam_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_RPC_CVI_S32, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getctrlparam_1(RPC_VI_PIPE ViPipe,  CLIENT *clnt)
{
	static RPC_ISP_GET_ATTR_DATA_S clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RPC_CVI_ISP_GetCtrlParam,
		(xdrproc_t) xdr_RPC_VI_PIPE, (caddr_t) &ViPipe,
		(xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_CVI_S32 *
rpc_cvi_isp_setfmwstate_1(RPC_VI_PIPE ViPipe, uint32_t enState,  CLIENT *clnt)
{
	rpc_cvi_isp_setfmwstate_1_argument arg;
	static RPC_CVI_S32 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.ViPipe = ViPipe;
	arg.enState = enState;
	if (clnt_call (clnt, RPC_CVI_ISP_SetFMWState, (xdrproc_t) xdr_rpc_cvi_isp_setfmwstate_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_RPC_CVI_S32, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

uint32_t *
rpc_cvi_isp_getfmwstate_1(RPC_VI_PIPE ViPipe,  CLIENT *clnt)
{
	static uint32_t clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RPC_CVI_ISP_GetFMWState,
		(xdrproc_t) xdr_RPC_VI_PIPE, (caddr_t) &ViPipe,
		(xdrproc_t) xdr_uint32_t, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_CVI_S32 *
rpc_cvi_isp_setmodulecontrol_1(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  CLIENT *clnt)
{
	rpc_cvi_isp_setmodulecontrol_1_argument arg;
	static RPC_CVI_S32 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.ViPipe = ViPipe;
	arg.stAttrData = stAttrData;
	if (clnt_call (clnt, RPC_CVI_ISP_SetModuleControl, (xdrproc_t) xdr_rpc_cvi_isp_setmodulecontrol_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_RPC_CVI_S32, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getmodulecontrol_1(RPC_VI_PIPE ViPipe,  CLIENT *clnt)
{
	static RPC_ISP_GET_ATTR_DATA_S clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RPC_CVI_ISP_GetModuleControl,
		(xdrproc_t) xdr_RPC_VI_PIPE, (caddr_t) &ViPipe,
		(xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_CVI_S32 *
rpc_cvi_isp_setregister_1(RPC_VI_PIPE ViPipe, uint32_t u32Addr, uint32_t u32Value,  CLIENT *clnt)
{
	rpc_cvi_isp_setregister_1_argument arg;
	static RPC_CVI_S32 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.ViPipe = ViPipe;
	arg.u32Addr = u32Addr;
	arg.u32Value = u32Value;
	if (clnt_call (clnt, RPC_CVI_ISP_SetRegister, (xdrproc_t) xdr_rpc_cvi_isp_setregister_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_RPC_CVI_S32, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

uint32_t *
rpc_cvi_isp_getregister_1(RPC_VI_PIPE ViPipe, uint32_t u32Addr,  CLIENT *clnt)
{
	rpc_cvi_isp_getregister_1_argument arg;
	static uint32_t clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.ViPipe = ViPipe;
	arg.u32Addr = u32Addr;
	if (clnt_call (clnt, RPC_CVI_ISP_GetRegister, (xdrproc_t) xdr_rpc_cvi_isp_getregister_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_uint32_t, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_CVI_S32 *
rpc_cvi_isp_setcolortoneattr_1(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  CLIENT *clnt)
{
	rpc_cvi_isp_setcolortoneattr_1_argument arg;
	static RPC_CVI_S32 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.ViPipe = ViPipe;
	arg.stAttrData = stAttrData;
	if (clnt_call (clnt, RPC_CVI_ISP_SetColorToneAttr, (xdrproc_t) xdr_rpc_cvi_isp_setcolortoneattr_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_RPC_CVI_S32, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getcolortoneattr_1(RPC_VI_PIPE ViPipe,  CLIENT *clnt)
{
	static RPC_ISP_GET_ATTR_DATA_S clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RPC_CVI_ISP_GetColorToneAttr,
		(xdrproc_t) xdr_RPC_VI_PIPE, (caddr_t) &ViPipe,
		(xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_CVI_S32 *
rpc_cvi_isp_setdehazeattr_1(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  CLIENT *clnt)
{
	rpc_cvi_isp_setdehazeattr_1_argument arg;
	static RPC_CVI_S32 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.ViPipe = ViPipe;
	arg.stAttrData = stAttrData;
	if (clnt_call (clnt, RPC_CVI_ISP_SetDehazeAttr, (xdrproc_t) xdr_rpc_cvi_isp_setdehazeattr_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_RPC_CVI_S32, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getdehazeattr_1(RPC_VI_PIPE ViPipe,  CLIENT *clnt)
{
	static RPC_ISP_GET_ATTR_DATA_S clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RPC_CVI_ISP_GetDehazeAttr,
		(xdrproc_t) xdr_RPC_VI_PIPE, (caddr_t) &ViPipe,
		(xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_CVI_S32 *
rpc_cvi_isp_setgammaattr_1(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  CLIENT *clnt)
{
	rpc_cvi_isp_setgammaattr_1_argument arg;
	static RPC_CVI_S32 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.ViPipe = ViPipe;
	arg.stAttrData = stAttrData;
	if (clnt_call (clnt, RPC_CVI_ISP_SetGammaAttr, (xdrproc_t) xdr_rpc_cvi_isp_setgammaattr_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_RPC_CVI_S32, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getgammaattr_1(RPC_VI_PIPE ViPipe,  CLIENT *clnt)
{
	static RPC_ISP_GET_ATTR_DATA_S clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RPC_CVI_ISP_GetGammaAttr,
		(xdrproc_t) xdr_RPC_VI_PIPE, (caddr_t) &ViPipe,
		(xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_CVI_S32 *
rpc_cvi_isp_setgammacurvetype_1(RPC_VI_PIPE ViPipe, uint32_t curveType,  CLIENT *clnt)
{
	rpc_cvi_isp_setgammacurvetype_1_argument arg;
	static RPC_CVI_S32 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.ViPipe = ViPipe;
	arg.curveType = curveType;
	if (clnt_call (clnt, RPC_CVI_ISP_SetGammaCurveType, (xdrproc_t) xdr_rpc_cvi_isp_setgammacurvetype_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_RPC_CVI_S32, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_CVI_S32 *
rpc_cvi_isp_setautogammaattr_1(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  CLIENT *clnt)
{
	rpc_cvi_isp_setautogammaattr_1_argument arg;
	static RPC_CVI_S32 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.ViPipe = ViPipe;
	arg.stAttrData = stAttrData;
	if (clnt_call (clnt, RPC_CVI_ISP_SetAutoGammaAttr, (xdrproc_t) xdr_rpc_cvi_isp_setautogammaattr_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_RPC_CVI_S32, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getautogammaattr_1(RPC_VI_PIPE ViPipe,  CLIENT *clnt)
{
	static RPC_ISP_GET_ATTR_DATA_S clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RPC_CVI_ISP_GetAutoGammaAttr,
		(xdrproc_t) xdr_RPC_VI_PIPE, (caddr_t) &ViPipe,
		(xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_CVI_S32 *
rpc_cvi_isp_setstatisticsconfig_1(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  CLIENT *clnt)
{
	rpc_cvi_isp_setstatisticsconfig_1_argument arg;
	static RPC_CVI_S32 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.ViPipe = ViPipe;
	arg.stAttrData = stAttrData;
	if (clnt_call (clnt, RPC_CVI_ISP_SetStatisticsConfig, (xdrproc_t) xdr_rpc_cvi_isp_setstatisticsconfig_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_RPC_CVI_S32, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getstatisticsconfig_1(RPC_VI_PIPE ViPipe,  CLIENT *clnt)
{
	static RPC_ISP_GET_ATTR_DATA_S clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RPC_CVI_ISP_GetStatisticsConfig,
		(xdrproc_t) xdr_RPC_VI_PIPE, (caddr_t) &ViPipe,
		(xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_CVI_S32 *
rpc_cvi_isp_setnrattr_1(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  CLIENT *clnt)
{
	rpc_cvi_isp_setnrattr_1_argument arg;
	static RPC_CVI_S32 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.ViPipe = ViPipe;
	arg.stAttrData = stAttrData;
	if (clnt_call (clnt, RPC_CVI_ISP_SetNRAttr, (xdrproc_t) xdr_rpc_cvi_isp_setnrattr_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_RPC_CVI_S32, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getnrattr_1(RPC_VI_PIPE ViPipe,  CLIENT *clnt)
{
	static RPC_ISP_GET_ATTR_DATA_S clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RPC_CVI_ISP_GetNRAttr,
		(xdrproc_t) xdr_RPC_VI_PIPE, (caddr_t) &ViPipe,
		(xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_CVI_S32 *
rpc_cvi_isp_setnrfilterattr_1(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  CLIENT *clnt)
{
	rpc_cvi_isp_setnrfilterattr_1_argument arg;
	static RPC_CVI_S32 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.ViPipe = ViPipe;
	arg.stAttrData = stAttrData;
	if (clnt_call (clnt, RPC_CVI_ISP_SetNRFilterAttr, (xdrproc_t) xdr_rpc_cvi_isp_setnrfilterattr_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_RPC_CVI_S32, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getnrfilterattr_1(RPC_VI_PIPE ViPipe,  CLIENT *clnt)
{
	static RPC_ISP_GET_ATTR_DATA_S clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RPC_CVI_ISP_GetNRFilterAttr,
		(xdrproc_t) xdr_RPC_VI_PIPE, (caddr_t) &ViPipe,
		(xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_CVI_S32 *
rpc_cvi_isp_setrlscattr_1(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  CLIENT *clnt)
{
	rpc_cvi_isp_setrlscattr_1_argument arg;
	static RPC_CVI_S32 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.ViPipe = ViPipe;
	arg.stAttrData = stAttrData;
	if (clnt_call (clnt, RPC_CVI_ISP_SetRLSCAttr, (xdrproc_t) xdr_rpc_cvi_isp_setrlscattr_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_RPC_CVI_S32, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getrlscattr_1(RPC_VI_PIPE ViPipe,  CLIENT *clnt)
{
	static RPC_ISP_GET_ATTR_DATA_S clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RPC_CVI_ISP_GetRLSCAttr,
		(xdrproc_t) xdr_RPC_VI_PIPE, (caddr_t) &ViPipe,
		(xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_CVI_S32 *
rpc_cvi_isp_setynrattr_1(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  CLIENT *clnt)
{
	rpc_cvi_isp_setynrattr_1_argument arg;
	static RPC_CVI_S32 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.ViPipe = ViPipe;
	arg.stAttrData = stAttrData;
	if (clnt_call (clnt, RPC_CVI_ISP_SetYNRAttr, (xdrproc_t) xdr_rpc_cvi_isp_setynrattr_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_RPC_CVI_S32, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getynrattr_1(RPC_VI_PIPE ViPipe,  CLIENT *clnt)
{
	static RPC_ISP_GET_ATTR_DATA_S clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RPC_CVI_ISP_GetYNRAttr,
		(xdrproc_t) xdr_RPC_VI_PIPE, (caddr_t) &ViPipe,
		(xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_CVI_S32 *
rpc_cvi_isp_setynrmotionnrattr_1(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  CLIENT *clnt)
{
	rpc_cvi_isp_setynrmotionnrattr_1_argument arg;
	static RPC_CVI_S32 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.ViPipe = ViPipe;
	arg.stAttrData = stAttrData;
	if (clnt_call (clnt, RPC_CVI_ISP_SetYNRMotionNRAttr, (xdrproc_t) xdr_rpc_cvi_isp_setynrmotionnrattr_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_RPC_CVI_S32, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getynrmotionnrattr_1(RPC_VI_PIPE ViPipe,  CLIENT *clnt)
{
	static RPC_ISP_GET_ATTR_DATA_S clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RPC_CVI_ISP_GetYNRMotionNRAttr,
		(xdrproc_t) xdr_RPC_VI_PIPE, (caddr_t) &ViPipe,
		(xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_CVI_S32 *
rpc_cvi_isp_setynrfilterattr_1(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  CLIENT *clnt)
{
	rpc_cvi_isp_setynrfilterattr_1_argument arg;
	static RPC_CVI_S32 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.ViPipe = ViPipe;
	arg.stAttrData = stAttrData;
	if (clnt_call (clnt, RPC_CVI_ISP_SetYNRFilterAttr, (xdrproc_t) xdr_rpc_cvi_isp_setynrfilterattr_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_RPC_CVI_S32, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getynrfilterattr_1(RPC_VI_PIPE ViPipe,  CLIENT *clnt)
{
	static RPC_ISP_GET_ATTR_DATA_S clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RPC_CVI_ISP_GetYNRFilterAttr,
		(xdrproc_t) xdr_RPC_VI_PIPE, (caddr_t) &ViPipe,
		(xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_CVI_S32 *
rpc_cvi_isp_setcnrattr_1(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  CLIENT *clnt)
{
	rpc_cvi_isp_setcnrattr_1_argument arg;
	static RPC_CVI_S32 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.ViPipe = ViPipe;
	arg.stAttrData = stAttrData;
	if (clnt_call (clnt, RPC_CVI_ISP_SetCNRAttr, (xdrproc_t) xdr_rpc_cvi_isp_setcnrattr_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_RPC_CVI_S32, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getcnrattr_1(RPC_VI_PIPE ViPipe,  CLIENT *clnt)
{
	static RPC_ISP_GET_ATTR_DATA_S clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RPC_CVI_ISP_GetCNRAttr,
		(xdrproc_t) xdr_RPC_VI_PIPE, (caddr_t) &ViPipe,
		(xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_CVI_S32 *
rpc_cvi_isp_setcacattr_1(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  CLIENT *clnt)
{
	rpc_cvi_isp_setcacattr_1_argument arg;
	static RPC_CVI_S32 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.ViPipe = ViPipe;
	arg.stAttrData = stAttrData;
	if (clnt_call (clnt, RPC_CVI_ISP_SetCACAttr, (xdrproc_t) xdr_rpc_cvi_isp_setcacattr_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_RPC_CVI_S32, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getcacattr_1(RPC_VI_PIPE ViPipe,  CLIENT *clnt)
{
	static RPC_ISP_GET_ATTR_DATA_S clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RPC_CVI_ISP_GetCACAttr,
		(xdrproc_t) xdr_RPC_VI_PIPE, (caddr_t) &ViPipe,
		(xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_CVI_S32 *
rpc_cvi_isp_setdciattr_1(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  CLIENT *clnt)
{
	rpc_cvi_isp_setdciattr_1_argument arg;
	static RPC_CVI_S32 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.ViPipe = ViPipe;
	arg.stAttrData = stAttrData;
	if (clnt_call (clnt, RPC_CVI_ISP_SetDCIAttr, (xdrproc_t) xdr_rpc_cvi_isp_setdciattr_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_RPC_CVI_S32, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getdciattr_1(RPC_VI_PIPE ViPipe,  CLIENT *clnt)
{
	static RPC_ISP_GET_ATTR_DATA_S clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RPC_CVI_ISP_GetDCIAttr,
		(xdrproc_t) xdr_RPC_VI_PIPE, (caddr_t) &ViPipe,
		(xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_CVI_S32 *
rpc_cvi_isp_setmeshshadingattr_1(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  CLIENT *clnt)
{
	rpc_cvi_isp_setmeshshadingattr_1_argument arg;
	static RPC_CVI_S32 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.ViPipe = ViPipe;
	arg.stAttrData = stAttrData;
	if (clnt_call (clnt, RPC_CVI_ISP_SetMeshShadingAttr, (xdrproc_t) xdr_rpc_cvi_isp_setmeshshadingattr_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_RPC_CVI_S32, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getmeshshadingattr_1(RPC_VI_PIPE ViPipe,  CLIENT *clnt)
{
	static RPC_ISP_GET_ATTR_DATA_S clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RPC_CVI_ISP_GetMeshShadingAttr,
		(xdrproc_t) xdr_RPC_VI_PIPE, (caddr_t) &ViPipe,
		(xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_CVI_S32 *
rpc_cvi_isp_setmeshshadinggainlutattr_1(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  CLIENT *clnt)
{
	rpc_cvi_isp_setmeshshadinggainlutattr_1_argument arg;
	static RPC_CVI_S32 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.ViPipe = ViPipe;
	arg.stAttrData = stAttrData;
	if (clnt_call (clnt, RPC_CVI_ISP_SetMeshShadingGainLutAttr, (xdrproc_t) xdr_rpc_cvi_isp_setmeshshadinggainlutattr_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_RPC_CVI_S32, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getmeshshadinggainlutattr_1(RPC_VI_PIPE ViPipe,  CLIENT *clnt)
{
	static RPC_ISP_GET_ATTR_DATA_S clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RPC_CVI_ISP_GetMeshShadingGainLutAttr,
		(xdrproc_t) xdr_RPC_VI_PIPE, (caddr_t) &ViPipe,
		(xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_CVI_S32 *
rpc_cvi_isp_setradialshadingattr_1(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  CLIENT *clnt)
{
	rpc_cvi_isp_setradialshadingattr_1_argument arg;
	static RPC_CVI_S32 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.ViPipe = ViPipe;
	arg.stAttrData = stAttrData;
	if (clnt_call (clnt, RPC_CVI_ISP_SetRadialShadingAttr, (xdrproc_t) xdr_rpc_cvi_isp_setradialshadingattr_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_RPC_CVI_S32, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getradialshadingattr_1(RPC_VI_PIPE ViPipe,  CLIENT *clnt)
{
	static RPC_ISP_GET_ATTR_DATA_S clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RPC_CVI_ISP_GetRadialShadingAttr,
		(xdrproc_t) xdr_RPC_VI_PIPE, (caddr_t) &ViPipe,
		(xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_CVI_S32 *
rpc_cvi_isp_setradialshadinggainlutattr_1(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  CLIENT *clnt)
{
	rpc_cvi_isp_setradialshadinggainlutattr_1_argument arg;
	static RPC_CVI_S32 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.ViPipe = ViPipe;
	arg.stAttrData = stAttrData;
	if (clnt_call (clnt, RPC_CVI_ISP_SetRadialShadingGainLutAttr, (xdrproc_t) xdr_rpc_cvi_isp_setradialshadinggainlutattr_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_RPC_CVI_S32, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getradialshadinggainlutattr_1(RPC_VI_PIPE ViPipe,  CLIENT *clnt)
{
	static RPC_ISP_GET_ATTR_DATA_S clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RPC_CVI_ISP_GetRadialShadingGainLutAttr,
		(xdrproc_t) xdr_RPC_VI_PIPE, (caddr_t) &ViPipe,
		(xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_CVI_S32 *
rpc_cvi_isp_settnrattr_1(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  CLIENT *clnt)
{
	rpc_cvi_isp_settnrattr_1_argument arg;
	static RPC_CVI_S32 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.ViPipe = ViPipe;
	arg.stAttrData = stAttrData;
	if (clnt_call (clnt, RPC_CVI_ISP_SetTNRAttr, (xdrproc_t) xdr_rpc_cvi_isp_settnrattr_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_RPC_CVI_S32, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_gettnrattr_1(RPC_VI_PIPE ViPipe,  CLIENT *clnt)
{
	static RPC_ISP_GET_ATTR_DATA_S clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RPC_CVI_ISP_GetTNRAttr,
		(xdrproc_t) xdr_RPC_VI_PIPE, (caddr_t) &ViPipe,
		(xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_CVI_S32 *
rpc_cvi_isp_settnrnoisemodelattr_1(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  CLIENT *clnt)
{
	rpc_cvi_isp_settnrnoisemodelattr_1_argument arg;
	static RPC_CVI_S32 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.ViPipe = ViPipe;
	arg.stAttrData = stAttrData;
	if (clnt_call (clnt, RPC_CVI_ISP_SetTNRNoiseModelAttr, (xdrproc_t) xdr_rpc_cvi_isp_settnrnoisemodelattr_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_RPC_CVI_S32, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_gettnrnoisemodelattr_1(RPC_VI_PIPE ViPipe,  CLIENT *clnt)
{
	static RPC_ISP_GET_ATTR_DATA_S clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RPC_CVI_ISP_GetTNRNoiseModelAttr,
		(xdrproc_t) xdr_RPC_VI_PIPE, (caddr_t) &ViPipe,
		(xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_CVI_S32 *
rpc_cvi_isp_settnrlumamotionattr_1(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  CLIENT *clnt)
{
	rpc_cvi_isp_settnrlumamotionattr_1_argument arg;
	static RPC_CVI_S32 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.ViPipe = ViPipe;
	arg.stAttrData = stAttrData;
	if (clnt_call (clnt, RPC_CVI_ISP_SetTNRLumaMotionAttr, (xdrproc_t) xdr_rpc_cvi_isp_settnrlumamotionattr_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_RPC_CVI_S32, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_gettnrlumamotionattr_1(RPC_VI_PIPE ViPipe,  CLIENT *clnt)
{
	static RPC_ISP_GET_ATTR_DATA_S clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RPC_CVI_ISP_GetTNRLumaMotionAttr,
		(xdrproc_t) xdr_RPC_VI_PIPE, (caddr_t) &ViPipe,
		(xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_CVI_S32 *
rpc_cvi_isp_settnrghostattr_1(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  CLIENT *clnt)
{
	rpc_cvi_isp_settnrghostattr_1_argument arg;
	static RPC_CVI_S32 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.ViPipe = ViPipe;
	arg.stAttrData = stAttrData;
	if (clnt_call (clnt, RPC_CVI_ISP_SetTNRGhostAttr, (xdrproc_t) xdr_rpc_cvi_isp_settnrghostattr_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_RPC_CVI_S32, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_gettnrghostattr_1(RPC_VI_PIPE ViPipe,  CLIENT *clnt)
{
	static RPC_ISP_GET_ATTR_DATA_S clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RPC_CVI_ISP_GetTNRGhostAttr,
		(xdrproc_t) xdr_RPC_VI_PIPE, (caddr_t) &ViPipe,
		(xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_CVI_S32 *
rpc_cvi_isp_settnrmtprtattr_1(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  CLIENT *clnt)
{
	rpc_cvi_isp_settnrmtprtattr_1_argument arg;
	static RPC_CVI_S32 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.ViPipe = ViPipe;
	arg.stAttrData = stAttrData;
	if (clnt_call (clnt, RPC_CVI_ISP_SetTNRMtPrtAttr, (xdrproc_t) xdr_rpc_cvi_isp_settnrmtprtattr_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_RPC_CVI_S32, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_gettnrmtprtattr_1(RPC_VI_PIPE ViPipe,  CLIENT *clnt)
{
	static RPC_ISP_GET_ATTR_DATA_S clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RPC_CVI_ISP_GetTNRMtPrtAttr,
		(xdrproc_t) xdr_RPC_VI_PIPE, (caddr_t) &ViPipe,
		(xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_CVI_S32 *
rpc_cvi_isp_setclutattr_1(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  CLIENT *clnt)
{
	rpc_cvi_isp_setclutattr_1_argument arg;
	static RPC_CVI_S32 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.ViPipe = ViPipe;
	arg.stAttrData = stAttrData;
	if (clnt_call (clnt, RPC_CVI_ISP_SetCLutAttr, (xdrproc_t) xdr_rpc_cvi_isp_setclutattr_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_RPC_CVI_S32, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getclutattr_1(RPC_VI_PIPE ViPipe,  CLIENT *clnt)
{
	static RPC_ISP_GET_ATTR_DATA_S clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RPC_CVI_ISP_GetCLutAttr,
		(xdrproc_t) xdr_RPC_VI_PIPE, (caddr_t) &ViPipe,
		(xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_CVI_S32 *
rpc_cvi_isp_setclutcoeff_1(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  CLIENT *clnt)
{
	rpc_cvi_isp_setclutcoeff_1_argument arg;
	static RPC_CVI_S32 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.ViPipe = ViPipe;
	arg.stAttrData = stAttrData;
	if (clnt_call (clnt, RPC_CVI_ISP_SetCLutCoeff, (xdrproc_t) xdr_rpc_cvi_isp_setclutcoeff_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_RPC_CVI_S32, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getclutcoeff_1(RPC_VI_PIPE ViPipe,  CLIENT *clnt)
{
	static RPC_ISP_GET_ATTR_DATA_S clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RPC_CVI_ISP_GetCLutCoeff,
		(xdrproc_t) xdr_RPC_VI_PIPE, (caddr_t) &ViPipe,
		(xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_CVI_S32 *
rpc_cvi_isp_setblacklevelattr_1(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  CLIENT *clnt)
{
	rpc_cvi_isp_setblacklevelattr_1_argument arg;
	static RPC_CVI_S32 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.ViPipe = ViPipe;
	arg.stAttrData = stAttrData;
	if (clnt_call (clnt, RPC_CVI_ISP_SetBlackLevelAttr, (xdrproc_t) xdr_rpc_cvi_isp_setblacklevelattr_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_RPC_CVI_S32, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getblacklevelattr_1(RPC_VI_PIPE ViPipe,  CLIENT *clnt)
{
	static RPC_ISP_GET_ATTR_DATA_S clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RPC_CVI_ISP_GetBlackLevelAttr,
		(xdrproc_t) xdr_RPC_VI_PIPE, (caddr_t) &ViPipe,
		(xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_CVI_S32 *
rpc_cvi_isp_setdemosaicattr_1(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  CLIENT *clnt)
{
	rpc_cvi_isp_setdemosaicattr_1_argument arg;
	static RPC_CVI_S32 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.ViPipe = ViPipe;
	arg.stAttrData = stAttrData;
	if (clnt_call (clnt, RPC_CVI_ISP_SetDemosaicAttr, (xdrproc_t) xdr_rpc_cvi_isp_setdemosaicattr_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_RPC_CVI_S32, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getdemosaicattr_1(RPC_VI_PIPE ViPipe,  CLIENT *clnt)
{
	static RPC_ISP_GET_ATTR_DATA_S clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RPC_CVI_ISP_GetDemosaicAttr,
		(xdrproc_t) xdr_RPC_VI_PIPE, (caddr_t) &ViPipe,
		(xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_CVI_S32 *
rpc_cvi_isp_setdemosaicdemoireattr_1(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  CLIENT *clnt)
{
	rpc_cvi_isp_setdemosaicdemoireattr_1_argument arg;
	static RPC_CVI_S32 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.ViPipe = ViPipe;
	arg.stAttrData = stAttrData;
	if (clnt_call (clnt, RPC_CVI_ISP_SetDemosaicDemoireAttr, (xdrproc_t) xdr_rpc_cvi_isp_setdemosaicdemoireattr_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_RPC_CVI_S32, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getdemosaicdemoireattr_1(RPC_VI_PIPE ViPipe,  CLIENT *clnt)
{
	static RPC_ISP_GET_ATTR_DATA_S clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RPC_CVI_ISP_GetDemosaicDemoireAttr,
		(xdrproc_t) xdr_RPC_VI_PIPE, (caddr_t) &ViPipe,
		(xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_CVI_S32 *
rpc_cvi_isp_setdemosaicfilterattr_1(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  CLIENT *clnt)
{
	rpc_cvi_isp_setdemosaicfilterattr_1_argument arg;
	static RPC_CVI_S32 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.ViPipe = ViPipe;
	arg.stAttrData = stAttrData;
	if (clnt_call (clnt, RPC_CVI_ISP_SetDemosaicFilterAttr, (xdrproc_t) xdr_rpc_cvi_isp_setdemosaicfilterattr_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_RPC_CVI_S32, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getdemosaicfilterattr_1(RPC_VI_PIPE ViPipe,  CLIENT *clnt)
{
	static RPC_ISP_GET_ATTR_DATA_S clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RPC_CVI_ISP_GetDemosaicFilterAttr,
		(xdrproc_t) xdr_RPC_VI_PIPE, (caddr_t) &ViPipe,
		(xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_CVI_S32 *
rpc_cvi_isp_setdemosaiceeattr_1(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  CLIENT *clnt)
{
	rpc_cvi_isp_setdemosaiceeattr_1_argument arg;
	static RPC_CVI_S32 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.ViPipe = ViPipe;
	arg.stAttrData = stAttrData;
	if (clnt_call (clnt, RPC_CVI_ISP_SetDemosaicEEAttr, (xdrproc_t) xdr_rpc_cvi_isp_setdemosaiceeattr_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_RPC_CVI_S32, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getdemosaiceeattr_1(RPC_VI_PIPE ViPipe,  CLIENT *clnt)
{
	static RPC_ISP_GET_ATTR_DATA_S clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RPC_CVI_ISP_GetDemosaicEEAttr,
		(xdrproc_t) xdr_RPC_VI_PIPE, (caddr_t) &ViPipe,
		(xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_CVI_S32 *
rpc_cvi_isp_setsaturationattr_1(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  CLIENT *clnt)
{
	rpc_cvi_isp_setsaturationattr_1_argument arg;
	static RPC_CVI_S32 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.ViPipe = ViPipe;
	arg.stAttrData = stAttrData;
	if (clnt_call (clnt, RPC_CVI_ISP_SetSaturationAttr, (xdrproc_t) xdr_rpc_cvi_isp_setsaturationattr_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_RPC_CVI_S32, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getsaturationattr_1(RPC_VI_PIPE ViPipe,  CLIENT *clnt)
{
	static RPC_ISP_GET_ATTR_DATA_S clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RPC_CVI_ISP_GetSaturationAttr,
		(xdrproc_t) xdr_RPC_VI_PIPE, (caddr_t) &ViPipe,
		(xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_CVI_S32 *
rpc_cvi_isp_setccmattr_1(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  CLIENT *clnt)
{
	rpc_cvi_isp_setccmattr_1_argument arg;
	static RPC_CVI_S32 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.ViPipe = ViPipe;
	arg.stAttrData = stAttrData;
	if (clnt_call (clnt, RPC_CVI_ISP_SetCCMAttr, (xdrproc_t) xdr_rpc_cvi_isp_setccmattr_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_RPC_CVI_S32, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getccmattr_1(RPC_VI_PIPE ViPipe,  CLIENT *clnt)
{
	static RPC_ISP_GET_ATTR_DATA_S clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RPC_CVI_ISP_GetCCMAttr,
		(xdrproc_t) xdr_RPC_VI_PIPE, (caddr_t) &ViPipe,
		(xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_CVI_S32 *
rpc_cvi_isp_sethsvattr_1(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  CLIENT *clnt)
{
	rpc_cvi_isp_sethsvattr_1_argument arg;
	static RPC_CVI_S32 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.ViPipe = ViPipe;
	arg.stAttrData = stAttrData;
	if (clnt_call (clnt, RPC_CVI_ISP_SetHSVAttr, (xdrproc_t) xdr_rpc_cvi_isp_sethsvattr_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_RPC_CVI_S32, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_gethsvattr_1(RPC_VI_PIPE ViPipe,  CLIENT *clnt)
{
	static RPC_ISP_GET_ATTR_DATA_S clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RPC_CVI_ISP_GetHSVAttr,
		(xdrproc_t) xdr_RPC_VI_PIPE, (caddr_t) &ViPipe,
		(xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_CVI_S32 *
rpc_cvi_isp_setdpdynamicattr_1(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  CLIENT *clnt)
{
	rpc_cvi_isp_setdpdynamicattr_1_argument arg;
	static RPC_CVI_S32 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.ViPipe = ViPipe;
	arg.stAttrData = stAttrData;
	if (clnt_call (clnt, RPC_CVI_ISP_SetDPDynamicAttr, (xdrproc_t) xdr_rpc_cvi_isp_setdpdynamicattr_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_RPC_CVI_S32, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getdpdynamicattr_1(RPC_VI_PIPE ViPipe,  CLIENT *clnt)
{
	static RPC_ISP_GET_ATTR_DATA_S clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RPC_CVI_ISP_GetDPDynamicAttr,
		(xdrproc_t) xdr_RPC_VI_PIPE, (caddr_t) &ViPipe,
		(xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_CVI_S32 *
rpc_cvi_isp_setdpstaticattr_1(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  CLIENT *clnt)
{
	rpc_cvi_isp_setdpstaticattr_1_argument arg;
	static RPC_CVI_S32 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.ViPipe = ViPipe;
	arg.stAttrData = stAttrData;
	if (clnt_call (clnt, RPC_CVI_ISP_SetDPStaticAttr, (xdrproc_t) xdr_rpc_cvi_isp_setdpstaticattr_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_RPC_CVI_S32, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getdpstaticattr_1(RPC_VI_PIPE ViPipe,  CLIENT *clnt)
{
	static RPC_ISP_GET_ATTR_DATA_S clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RPC_CVI_ISP_GetDPStaticAttr,
		(xdrproc_t) xdr_RPC_VI_PIPE, (caddr_t) &ViPipe,
		(xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_CVI_S32 *
rpc_cvi_isp_setdpcalibrate_1(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  CLIENT *clnt)
{
	rpc_cvi_isp_setdpcalibrate_1_argument arg;
	static RPC_CVI_S32 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.ViPipe = ViPipe;
	arg.stAttrData = stAttrData;
	if (clnt_call (clnt, RPC_CVI_ISP_SetDPCalibrate, (xdrproc_t) xdr_rpc_cvi_isp_setdpcalibrate_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_RPC_CVI_S32, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getdpcalibrate_1(RPC_VI_PIPE ViPipe,  CLIENT *clnt)
{
	static RPC_ISP_GET_ATTR_DATA_S clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RPC_CVI_ISP_GetDPCalibrate,
		(xdrproc_t) xdr_RPC_VI_PIPE, (caddr_t) &ViPipe,
		(xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_CVI_S32 *
rpc_cvi_isp_setcrosstalkattr_1(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  CLIENT *clnt)
{
	rpc_cvi_isp_setcrosstalkattr_1_argument arg;
	static RPC_CVI_S32 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.ViPipe = ViPipe;
	arg.stAttrData = stAttrData;
	if (clnt_call (clnt, RPC_CVI_ISP_SetCrosstalkAttr, (xdrproc_t) xdr_rpc_cvi_isp_setcrosstalkattr_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_RPC_CVI_S32, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getcrosstalkattr_1(RPC_VI_PIPE ViPipe,  CLIENT *clnt)
{
	static RPC_ISP_GET_ATTR_DATA_S clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RPC_CVI_ISP_GetCrosstalkAttr,
		(xdrproc_t) xdr_RPC_VI_PIPE, (caddr_t) &ViPipe,
		(xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getaestatistics_1(RPC_VI_PIPE ViPipe,  CLIENT *clnt)
{
	static RPC_ISP_GET_ATTR_DATA_S clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RPC_CVI_ISP_GetAEStatistics,
		(xdrproc_t) xdr_RPC_VI_PIPE, (caddr_t) &ViPipe,
		(xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getwbstatistics_1(RPC_VI_PIPE ViPipe,  CLIENT *clnt)
{
	static RPC_ISP_GET_ATTR_DATA_S clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RPC_CVI_ISP_GetWBStatistics,
		(xdrproc_t) xdr_RPC_VI_PIPE, (caddr_t) &ViPipe,
		(xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getfocusstatistics_1(RPC_VI_PIPE ViPipe,  CLIENT *clnt)
{
	static RPC_ISP_GET_ATTR_DATA_S clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RPC_CVI_ISP_GetFocusStatistics,
		(xdrproc_t) xdr_RPC_VI_PIPE, (caddr_t) &ViPipe,
		(xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getlightboxgain_1(RPC_VI_PIPE ViPipe,  CLIENT *clnt)
{
	static RPC_ISP_GET_ATTR_DATA_S clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RPC_CVI_ISP_GetLightboxGain,
		(xdrproc_t) xdr_RPC_VI_PIPE, (caddr_t) &ViPipe,
		(xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_CVI_S32 *
rpc_cvi_isp_setfswdrattr_1(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  CLIENT *clnt)
{
	rpc_cvi_isp_setfswdrattr_1_argument arg;
	static RPC_CVI_S32 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.ViPipe = ViPipe;
	arg.stAttrData = stAttrData;
	if (clnt_call (clnt, RPC_CVI_ISP_SetFSWDRAttr, (xdrproc_t) xdr_rpc_cvi_isp_setfswdrattr_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_RPC_CVI_S32, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getfswdrattr_1(RPC_VI_PIPE ViPipe,  CLIENT *clnt)
{
	static RPC_ISP_GET_ATTR_DATA_S clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RPC_CVI_ISP_GetFSWDRAttr,
		(xdrproc_t) xdr_RPC_VI_PIPE, (caddr_t) &ViPipe,
		(xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_CVI_S32 *
rpc_cvi_isp_setdrcattr_1(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  CLIENT *clnt)
{
	rpc_cvi_isp_setdrcattr_1_argument arg;
	static RPC_CVI_S32 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.ViPipe = ViPipe;
	arg.stAttrData = stAttrData;
	if (clnt_call (clnt, RPC_CVI_ISP_SetDRCAttr, (xdrproc_t) xdr_rpc_cvi_isp_setdrcattr_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_RPC_CVI_S32, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getdrcattr_1(RPC_VI_PIPE ViPipe,  CLIENT *clnt)
{
	static RPC_ISP_GET_ATTR_DATA_S clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RPC_CVI_ISP_GetDRCAttr,
		(xdrproc_t) xdr_RPC_VI_PIPE, (caddr_t) &ViPipe,
		(xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_CVI_S32 *
rpc_cvi_isp_setsharpenattr_1(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  CLIENT *clnt)
{
	rpc_cvi_isp_setsharpenattr_1_argument arg;
	static RPC_CVI_S32 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.ViPipe = ViPipe;
	arg.stAttrData = stAttrData;
	if (clnt_call (clnt, RPC_CVI_ISP_SetSharpenAttr, (xdrproc_t) xdr_rpc_cvi_isp_setsharpenattr_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_RPC_CVI_S32, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getsharpenattr_1(RPC_VI_PIPE ViPipe,  CLIENT *clnt)
{
	static RPC_ISP_GET_ATTR_DATA_S clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RPC_CVI_ISP_GetSharpenAttr,
		(xdrproc_t) xdr_RPC_VI_PIPE, (caddr_t) &ViPipe,
		(xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_CVI_S32 *
rpc_cvi_isp_setnoiseprofileattr_1(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  CLIENT *clnt)
{
	rpc_cvi_isp_setnoiseprofileattr_1_argument arg;
	static RPC_CVI_S32 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.ViPipe = ViPipe;
	arg.stAttrData = stAttrData;
	if (clnt_call (clnt, RPC_CVI_ISP_SetNoiseProfileAttr, (xdrproc_t) xdr_rpc_cvi_isp_setnoiseprofileattr_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_RPC_CVI_S32, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getnoiseprofileattr_1(RPC_VI_PIPE ViPipe,  CLIENT *clnt)
{
	static RPC_ISP_GET_ATTR_DATA_S clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RPC_CVI_ISP_GetNoiseProfileAttr,
		(xdrproc_t) xdr_RPC_VI_PIPE, (caddr_t) &ViPipe,
		(xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_CVI_S32 *
rpc_cvi_isp_setycontrastattr_1(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  CLIENT *clnt)
{
	rpc_cvi_isp_setycontrastattr_1_argument arg;
	static RPC_CVI_S32 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.ViPipe = ViPipe;
	arg.stAttrData = stAttrData;
	if (clnt_call (clnt, RPC_CVI_ISP_SetYContrastAttr, (xdrproc_t) xdr_rpc_cvi_isp_setycontrastattr_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_RPC_CVI_S32, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getycontrastattr_1(RPC_VI_PIPE ViPipe,  CLIENT *clnt)
{
	static RPC_ISP_GET_ATTR_DATA_S clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RPC_CVI_ISP_GetYContrastAttr,
		(xdrproc_t) xdr_RPC_VI_PIPE, (caddr_t) &ViPipe,
		(xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_CVI_S32 *
rpc_cvi_isp_setdcfinfo_1(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  CLIENT *clnt)
{
	rpc_cvi_isp_setdcfinfo_1_argument arg;
	static RPC_CVI_S32 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.ViPipe = ViPipe;
	arg.stAttrData = stAttrData;
	if (clnt_call (clnt, RPC_CVI_ISP_SetDCFInfo, (xdrproc_t) xdr_rpc_cvi_isp_setdcfinfo_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_RPC_CVI_S32, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getdcfinfo_1(RPC_VI_PIPE ViPipe,  CLIENT *clnt)
{
	static RPC_ISP_GET_ATTR_DATA_S clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RPC_CVI_ISP_GetDCFInfo,
		(xdrproc_t) xdr_RPC_VI_PIPE, (caddr_t) &ViPipe,
		(xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_queryinnerstateinfo_1(RPC_VI_PIPE ViPipe,  CLIENT *clnt)
{
	static RPC_ISP_GET_ATTR_DATA_S clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RPC_CVI_ISP_QueryInnerStateInfo,
		(xdrproc_t) xdr_RPC_VI_PIPE, (caddr_t) &ViPipe,
		(xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_CVI_S32 *
rpc_cvi_isp_getvdtimeout_1(RPC_VI_PIPE ViPipe, uint32_t enIspVDType, uint32_t u32MilliSec,  CLIENT *clnt)
{
	rpc_cvi_isp_getvdtimeout_1_argument arg;
	static RPC_CVI_S32 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.ViPipe = ViPipe;
	arg.enIspVDType = enIspVDType;
	arg.u32MilliSec = u32MilliSec;
	if (clnt_call (clnt, RPC_CVI_ISP_GetVDTimeOut, (xdrproc_t) xdr_rpc_cvi_isp_getvdtimeout_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_RPC_CVI_S32, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_CVI_S32 *
rpc_cvi_isp_setmonoattr_1(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  CLIENT *clnt)
{
	rpc_cvi_isp_setmonoattr_1_argument arg;
	static RPC_CVI_S32 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.ViPipe = ViPipe;
	arg.stAttrData = stAttrData;
	if (clnt_call (clnt, RPC_CVI_ISP_SetMonoAttr, (xdrproc_t) xdr_rpc_cvi_isp_setmonoattr_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_RPC_CVI_S32, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getmonoattr_1(RPC_VI_PIPE ViPipe,  CLIENT *clnt)
{
	static RPC_ISP_GET_ATTR_DATA_S clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RPC_CVI_ISP_GetMonoAttr,
		(xdrproc_t) xdr_RPC_VI_PIPE, (caddr_t) &ViPipe,
		(xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_CVI_S32 *
rpc_cvi_isp_setdisattr_1(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  CLIENT *clnt)
{
	rpc_cvi_isp_setdisattr_1_argument arg;
	static RPC_CVI_S32 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.ViPipe = ViPipe;
	arg.stAttrData = stAttrData;
	if (clnt_call (clnt, RPC_CVI_ISP_SetDisAttr, (xdrproc_t) xdr_rpc_cvi_isp_setdisattr_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_RPC_CVI_S32, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getdisattr_1(RPC_VI_PIPE ViPipe,  CLIENT *clnt)
{
	static RPC_ISP_GET_ATTR_DATA_S clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RPC_CVI_ISP_GetDisAttr,
		(xdrproc_t) xdr_RPC_VI_PIPE, (caddr_t) &ViPipe,
		(xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_CVI_S32 *
rpc_cvi_isp_setdisconfig_1(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  CLIENT *clnt)
{
	rpc_cvi_isp_setdisconfig_1_argument arg;
	static RPC_CVI_S32 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.ViPipe = ViPipe;
	arg.stAttrData = stAttrData;
	if (clnt_call (clnt, RPC_CVI_ISP_SetDisConfig, (xdrproc_t) xdr_rpc_cvi_isp_setdisconfig_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_RPC_CVI_S32, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getdisconfig_1(RPC_VI_PIPE ViPipe,  CLIENT *clnt)
{
	static RPC_ISP_GET_ATTR_DATA_S clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RPC_CVI_ISP_GetDisConfig,
		(xdrproc_t) xdr_RPC_VI_PIPE, (caddr_t) &ViPipe,
		(xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_CVI_S32 *
rpc_cvi_isp_getbinstatus_1(RPC_VI_PIPE ViPipe,  CLIENT *clnt)
{
	static RPC_CVI_S32 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RPC_CVI_ISP_GetBinStatus,
		(xdrproc_t) xdr_RPC_VI_PIPE, (caddr_t) &ViPipe,
		(xdrproc_t) xdr_RPC_CVI_S32, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_CVI_S32 *
rpc_cvi_isp_setvcattr_1(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  CLIENT *clnt)
{
	rpc_cvi_isp_setvcattr_1_argument arg;
	static RPC_CVI_S32 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.ViPipe = ViPipe;
	arg.stAttrData = stAttrData;
	if (clnt_call (clnt, RPC_CVI_ISP_SetVCAttr, (xdrproc_t) xdr_rpc_cvi_isp_setvcattr_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_RPC_CVI_S32, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getvcattr_1(RPC_VI_PIPE ViPipe,  CLIENT *clnt)
{
	static RPC_ISP_GET_ATTR_DATA_S clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RPC_CVI_ISP_GetVCAttr,
		(xdrproc_t) xdr_RPC_VI_PIPE, (caddr_t) &ViPipe,
		(xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_CVI_S32 *
rpc_cvi_isp_dumphwregistertofile_1(RPC_VI_PIPE ViPipe, char *fileName,  CLIENT *clnt)
{
	rpc_cvi_isp_dumphwregistertofile_1_argument arg;
	static RPC_CVI_S32 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.ViPipe = ViPipe;
	arg.fileName = fileName;
	if (clnt_call (clnt, RPC_CVI_ISP_DumpHwRegisterToFile, (xdrproc_t) xdr_rpc_cvi_isp_dumphwregistertofile_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_RPC_CVI_S32, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_CVI_S32 *
rpc_cvi_isp_dumpframerawinfotofile_1(RPC_VI_PIPE ViPipe, char *fileName,  CLIENT *clnt)
{
	rpc_cvi_isp_dumpframerawinfotofile_1_argument arg;
	static RPC_CVI_S32 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.ViPipe = ViPipe;
	arg.fileName = fileName;
	if (clnt_call (clnt, RPC_CVI_ISP_DumpFrameRawInfoToFile, (xdrproc_t) xdr_rpc_cvi_isp_dumpframerawinfotofile_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_RPC_CVI_S32, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_irautorunonce_1(uint32_t IspDev, RPC_ISP_SET_ATTR_DATA_S stAttrData,  CLIENT *clnt)
{
	rpc_cvi_isp_irautorunonce_1_argument arg;
	static RPC_ISP_GET_ATTR_DATA_S clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.IspDev = IspDev;
	arg.stAttrData = stAttrData;
	if (clnt_call (clnt, RPC_CVI_ISP_IrAutoRunOnce, (xdrproc_t) xdr_rpc_cvi_isp_irautorunonce_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_CVI_S32 *
rpc_cvi_isp_setsmartinfo_1(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData, uint8_t TimeOut,  CLIENT *clnt)
{
	rpc_cvi_isp_setsmartinfo_1_argument arg;
	static RPC_CVI_S32 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.ViPipe = ViPipe;
	arg.stAttrData = stAttrData;
	arg.TimeOut = TimeOut;
	if (clnt_call (clnt, RPC_CVI_ISP_SetSmartInfo, (xdrproc_t) xdr_rpc_cvi_isp_setsmartinfo_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_RPC_CVI_S32, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getsmartinfo_1(RPC_VI_PIPE ViPipe,  CLIENT *clnt)
{
	static RPC_ISP_GET_ATTR_DATA_S clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RPC_CVI_ISP_GetSmartInfo,
		(xdrproc_t) xdr_RPC_VI_PIPE, (caddr_t) &ViPipe,
		(xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_CVI_S32 *
rpc_cvi_isp_settnrmotionadaptattr_1(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  CLIENT *clnt)
{
	rpc_cvi_isp_settnrmotionadaptattr_1_argument arg;
	static RPC_CVI_S32 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.ViPipe = ViPipe;
	arg.stAttrData = stAttrData;
	if (clnt_call (clnt, RPC_CVI_ISP_SetTNRMotionAdaptAttr, (xdrproc_t) xdr_rpc_cvi_isp_settnrmotionadaptattr_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_RPC_CVI_S32, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_gettnrmotionadaptattr_1(RPC_VI_PIPE ViPipe,  CLIENT *clnt)
{
	static RPC_ISP_GET_ATTR_DATA_S clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RPC_CVI_ISP_GetTNRMotionAdaptAttr,
		(xdrproc_t) xdr_RPC_VI_PIPE, (caddr_t) &ViPipe,
		(xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_CVI_S32 *
rpc_cvi_isp_setclutsaturationattr_1(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  CLIENT *clnt)
{
	rpc_cvi_isp_setclutsaturationattr_1_argument arg;
	static RPC_CVI_S32 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.ViPipe = ViPipe;
	arg.stAttrData = stAttrData;
	if (clnt_call (clnt, RPC_CVI_ISP_SetClutSaturationAttr, (xdrproc_t) xdr_rpc_cvi_isp_setclutsaturationattr_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_RPC_CVI_S32, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getclutsaturationattr_1(RPC_VI_PIPE ViPipe,  CLIENT *clnt)
{
	static RPC_ISP_GET_ATTR_DATA_S clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RPC_CVI_ISP_GetClutSaturationAttr,
		(xdrproc_t) xdr_RPC_VI_PIPE, (caddr_t) &ViPipe,
		(xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getgammacurvebytype_1(RPC_VI_PIPE ViPipe, uint32_t curveType,  CLIENT *clnt)
{
	rpc_cvi_isp_getgammacurvebytype_1_argument arg;
	static RPC_ISP_GET_ATTR_DATA_S clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.ViPipe = ViPipe;
	arg.curveType = curveType;
	if (clnt_call (clnt, RPC_CVI_ISP_GetGammaCurveByType, (xdrproc_t) xdr_rpc_cvi_isp_getgammacurvebytype_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_CVI_S32 *
rpc_cvi_isp_setpresharpenattr_1(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  CLIENT *clnt)
{
	rpc_cvi_isp_setpresharpenattr_1_argument arg;
	static RPC_CVI_S32 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.ViPipe = ViPipe;
	arg.stAttrData = stAttrData;
	if (clnt_call (clnt, RPC_CVI_ISP_SetPreSharpenAttr, (xdrproc_t) xdr_rpc_cvi_isp_setpresharpenattr_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_RPC_CVI_S32, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getpresharpenattr_1(RPC_VI_PIPE ViPipe,  CLIENT *clnt)
{
	static RPC_ISP_GET_ATTR_DATA_S clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RPC_CVI_ISP_GetPreSharpenAttr,
		(xdrproc_t) xdr_RPC_VI_PIPE, (caddr_t) &ViPipe,
		(xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_CVI_S32 *
rpc_cvi_isp_setrgbcacattr_1(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  CLIENT *clnt)
{
	rpc_cvi_isp_setrgbcacattr_1_argument arg;
	static RPC_CVI_S32 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.ViPipe = ViPipe;
	arg.stAttrData = stAttrData;
	if (clnt_call (clnt, RPC_CVI_ISP_SetRGBCACAttr, (xdrproc_t) xdr_rpc_cvi_isp_setrgbcacattr_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_RPC_CVI_S32, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getrgbcacattr_1(RPC_VI_PIPE ViPipe,  CLIENT *clnt)
{
	static RPC_ISP_GET_ATTR_DATA_S clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RPC_CVI_ISP_GetRGBCACAttr,
		(xdrproc_t) xdr_RPC_VI_PIPE, (caddr_t) &ViPipe,
		(xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_CVI_S32 *
rpc_cvi_isp_setcnrmotionnrattr_1(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  CLIENT *clnt)
{
	rpc_cvi_isp_setcnrmotionnrattr_1_argument arg;
	static RPC_CVI_S32 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.ViPipe = ViPipe;
	arg.stAttrData = stAttrData;
	if (clnt_call (clnt, RPC_CVI_ISP_SetCNRMotionNRAttr, (xdrproc_t) xdr_rpc_cvi_isp_setcnrmotionnrattr_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_RPC_CVI_S32, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getcnrmotionnrattr_1(RPC_VI_PIPE ViPipe,  CLIENT *clnt)
{
	static RPC_ISP_GET_ATTR_DATA_S clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RPC_CVI_ISP_GetCNRMotionNRAttr,
		(xdrproc_t) xdr_RPC_VI_PIPE, (caddr_t) &ViPipe,
		(xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_CVI_S32 *
rpc_cvi_isp_setccmsaturationattr_1(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  CLIENT *clnt)
{
	rpc_cvi_isp_setccmsaturationattr_1_argument arg;
	static RPC_CVI_S32 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.ViPipe = ViPipe;
	arg.stAttrData = stAttrData;
	if (clnt_call (clnt, RPC_CVI_ISP_SetCCMSaturationAttr, (xdrproc_t) xdr_rpc_cvi_isp_setccmsaturationattr_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_RPC_CVI_S32, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getccmsaturationattr_1(RPC_VI_PIPE ViPipe,  CLIENT *clnt)
{
	static RPC_ISP_GET_ATTR_DATA_S clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RPC_CVI_ISP_GetCCMSaturationAttr,
		(xdrproc_t) xdr_RPC_VI_PIPE, (caddr_t) &ViPipe,
		(xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_CVI_S32 *
rpc_cvi_isp_setcaattr_1(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  CLIENT *clnt)
{
	rpc_cvi_isp_setcaattr_1_argument arg;
	static RPC_CVI_S32 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.ViPipe = ViPipe;
	arg.stAttrData = stAttrData;
	if (clnt_call (clnt, RPC_CVI_ISP_SetCAAttr, (xdrproc_t) xdr_rpc_cvi_isp_setcaattr_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_RPC_CVI_S32, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getcaattr_1(RPC_VI_PIPE ViPipe,  CLIENT *clnt)
{
	static RPC_ISP_GET_ATTR_DATA_S clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RPC_CVI_ISP_GetCAAttr,
		(xdrproc_t) xdr_RPC_VI_PIPE, (caddr_t) &ViPipe,
		(xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_CVI_S32 *
rpc_cvi_isp_setcscattr_1(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  CLIENT *clnt)
{
	rpc_cvi_isp_setcscattr_1_argument arg;
	static RPC_CVI_S32 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.ViPipe = ViPipe;
	arg.stAttrData = stAttrData;
	if (clnt_call (clnt, RPC_CVI_ISP_SetCSCAttr, (xdrproc_t) xdr_rpc_cvi_isp_setcscattr_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_RPC_CVI_S32, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getcscattr_1(RPC_VI_PIPE ViPipe,  CLIENT *clnt)
{
	static RPC_ISP_GET_ATTR_DATA_S clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RPC_CVI_ISP_GetCSCAttr,
		(xdrproc_t) xdr_RPC_VI_PIPE, (caddr_t) &ViPipe,
		(xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_CVI_S32 *
rpc_cvi_isp_setexposureattr_1(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  CLIENT *clnt)
{
	rpc_cvi_isp_setexposureattr_1_argument arg;
	static RPC_CVI_S32 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.ViPipe = ViPipe;
	arg.stAttrData = stAttrData;
	if (clnt_call (clnt, RPC_CVI_ISP_SetExposureAttr, (xdrproc_t) xdr_rpc_cvi_isp_setexposureattr_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_RPC_CVI_S32, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getexposureattr_1(RPC_VI_PIPE ViPipe,  CLIENT *clnt)
{
	static RPC_ISP_GET_ATTR_DATA_S clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RPC_CVI_ISP_GetExposureAttr,
		(xdrproc_t) xdr_RPC_VI_PIPE, (caddr_t) &ViPipe,
		(xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_queryexposureinfo_1(RPC_VI_PIPE ViPipe,  CLIENT *clnt)
{
	static RPC_ISP_GET_ATTR_DATA_S clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RPC_CVI_ISP_QueryExposureInfo,
		(xdrproc_t) xdr_RPC_VI_PIPE, (caddr_t) &ViPipe,
		(xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_CVI_S32 *
rpc_cvi_isp_setwdrexposureattr_1(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  CLIENT *clnt)
{
	rpc_cvi_isp_setwdrexposureattr_1_argument arg;
	static RPC_CVI_S32 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.ViPipe = ViPipe;
	arg.stAttrData = stAttrData;
	if (clnt_call (clnt, RPC_CVI_ISP_SetWDRExposureAttr, (xdrproc_t) xdr_rpc_cvi_isp_setwdrexposureattr_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_RPC_CVI_S32, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getwdrexposureattr_1(RPC_VI_PIPE ViPipe,  CLIENT *clnt)
{
	static RPC_ISP_GET_ATTR_DATA_S clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RPC_CVI_ISP_GetWDRExposureAttr,
		(xdrproc_t) xdr_RPC_VI_PIPE, (caddr_t) &ViPipe,
		(xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_CVI_S32 *
rpc_cvi_isp_setaerouteattr_1(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  CLIENT *clnt)
{
	rpc_cvi_isp_setaerouteattr_1_argument arg;
	static RPC_CVI_S32 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.ViPipe = ViPipe;
	arg.stAttrData = stAttrData;
	if (clnt_call (clnt, RPC_CVI_ISP_SetAERouteAttr, (xdrproc_t) xdr_rpc_cvi_isp_setaerouteattr_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_RPC_CVI_S32, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getaerouteattr_1(RPC_VI_PIPE ViPipe,  CLIENT *clnt)
{
	static RPC_ISP_GET_ATTR_DATA_S clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RPC_CVI_ISP_GetAERouteAttr,
		(xdrproc_t) xdr_RPC_VI_PIPE, (caddr_t) &ViPipe,
		(xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_CVI_S32 *
rpc_cvi_isp_setaerouteattrex_1(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  CLIENT *clnt)
{
	rpc_cvi_isp_setaerouteattrex_1_argument arg;
	static RPC_CVI_S32 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.ViPipe = ViPipe;
	arg.stAttrData = stAttrData;
	if (clnt_call (clnt, RPC_CVI_ISP_SetAERouteAttrEx, (xdrproc_t) xdr_rpc_cvi_isp_setaerouteattrex_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_RPC_CVI_S32, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getaerouteattrex_1(RPC_VI_PIPE ViPipe,  CLIENT *clnt)
{
	static RPC_ISP_GET_ATTR_DATA_S clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RPC_CVI_ISP_GetAERouteAttrEx,
		(xdrproc_t) xdr_RPC_VI_PIPE, (caddr_t) &ViPipe,
		(xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_CVI_S32 *
rpc_cvi_isp_aebracketingstart_1(RPC_VI_PIPE ViPipe,  CLIENT *clnt)
{
	static RPC_CVI_S32 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RPC_CVI_ISP_AEBracketingStart,
		(xdrproc_t) xdr_RPC_VI_PIPE, (caddr_t) &ViPipe,
		(xdrproc_t) xdr_RPC_CVI_S32, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_CVI_S32 *
rpc_cvi_isp_aebracketingsetexpsoure_1(RPC_VI_PIPE ViPipe, int leEvX10, int seEvX10,  CLIENT *clnt)
{
	rpc_cvi_isp_aebracketingsetexpsoure_1_argument arg;
	static RPC_CVI_S32 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.ViPipe = ViPipe;
	arg.leEvX10 = leEvX10;
	arg.seEvX10 = seEvX10;
	if (clnt_call (clnt, RPC_CVI_ISP_AEBracketingSetExpsoure, (xdrproc_t) xdr_rpc_cvi_isp_aebracketingsetexpsoure_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_RPC_CVI_S32, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_CVI_S32 *
rpc_cvi_isp_aebracketingfinish_1(RPC_VI_PIPE ViPipe,  CLIENT *clnt)
{
	static RPC_CVI_S32 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RPC_CVI_ISP_AEBracketingFinish,
		(xdrproc_t) xdr_RPC_VI_PIPE, (caddr_t) &ViPipe,
		(xdrproc_t) xdr_RPC_CVI_S32, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_CVI_S32 *
rpc_cvi_isp_aebracketingsetsimple_1(uint8_t enable,  CLIENT *clnt)
{
	static RPC_CVI_S32 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RPC_CVI_ISP_AEBracketingSetSimple,
		(xdrproc_t) xdr_uint8_t, (caddr_t) &enable,
		(xdrproc_t) xdr_RPC_CVI_S32, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_CVI_S32 *
rpc_cvi_isp_setaestatisticsconfig_1(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  CLIENT *clnt)
{
	rpc_cvi_isp_setaestatisticsconfig_1_argument arg;
	static RPC_CVI_S32 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.ViPipe = ViPipe;
	arg.stAttrData = stAttrData;
	if (clnt_call (clnt, RPC_CVI_ISP_SetAEStatisticsConfig, (xdrproc_t) xdr_rpc_cvi_isp_setaestatisticsconfig_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_RPC_CVI_S32, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getaestatisticsconfig_1(RPC_VI_PIPE ViPipe,  CLIENT *clnt)
{
	static RPC_ISP_GET_ATTR_DATA_S clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RPC_CVI_ISP_GetAEStatisticsConfig,
		(xdrproc_t) xdr_RPC_VI_PIPE, (caddr_t) &ViPipe,
		(xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_CVI_S32 *
rpc_cvi_isp_setantiflicker_1(RPC_VI_PIPE ViPipe, uint8_t enable, uint8_t frequency,  CLIENT *clnt)
{
	rpc_cvi_isp_setantiflicker_1_argument arg;
	static RPC_CVI_S32 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.ViPipe = ViPipe;
	arg.enable = enable;
	arg.frequency = frequency;
	if (clnt_call (clnt, RPC_CVI_ISP_SetAntiFlicker, (xdrproc_t) xdr_rpc_cvi_isp_setantiflicker_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_RPC_CVI_S32, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

uint32_t *
rpc_cvi_isp_getantiflicker_1(RPC_VI_PIPE ViPipe,  CLIENT *clnt)
{
	static uint32_t clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RPC_CVI_ISP_GetAntiFlicker,
		(xdrproc_t) xdr_RPC_VI_PIPE, (caddr_t) &ViPipe,
		(xdrproc_t) xdr_uint32_t, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_CVI_S32 *
rpc_cvi_isp_setwdrleonly_1(RPC_VI_PIPE ViPipe, uint8_t wdrLEOnly,  CLIENT *clnt)
{
	rpc_cvi_isp_setwdrleonly_1_argument arg;
	static RPC_CVI_S32 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.ViPipe = ViPipe;
	arg.wdrLEOnly = wdrLEOnly;
	if (clnt_call (clnt, RPC_CVI_ISP_SetWDRLEOnly, (xdrproc_t) xdr_rpc_cvi_isp_setwdrleonly_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_RPC_CVI_S32, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

uint32_t *
rpc_cvi_isp_getframeid_1(RPC_VI_PIPE ViPipe,  CLIENT *clnt)
{
	static uint32_t clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RPC_CVI_ISP_GetFrameID,
		(xdrproc_t) xdr_RPC_VI_PIPE, (caddr_t) &ViPipe,
		(xdrproc_t) xdr_uint32_t, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_CVI_S32 *
rpc_cvi_isp_setaelogpath_1(char *fileName,  CLIENT *clnt)
{
	static RPC_CVI_S32 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RPC_CVI_ISP_SetAELogPath,
		(xdrproc_t) xdr_wrapstring, (caddr_t) &fileName,
		(xdrproc_t) xdr_RPC_CVI_S32, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getaelogpath_1(int pathSize,  CLIENT *clnt)
{
	static RPC_ISP_GET_ATTR_DATA_S clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RPC_CVI_ISP_GetAELogPath,
		(xdrproc_t) xdr_int, (caddr_t) &pathSize,
		(xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_CVI_S32 *
rpc_cvi_isp_setaelogname_1(char *fileName,  CLIENT *clnt)
{
	static RPC_CVI_S32 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RPC_CVI_ISP_SetAELogName,
		(xdrproc_t) xdr_wrapstring, (caddr_t) &fileName,
		(xdrproc_t) xdr_RPC_CVI_S32, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getaelogname_1(int nameSize,  CLIENT *clnt)
{
	static RPC_ISP_GET_ATTR_DATA_S clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RPC_CVI_ISP_GetAELogName,
		(xdrproc_t) xdr_int, (caddr_t) &nameSize,
		(xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

float *
rpc_cvi_isp_queryfps_1(RPC_VI_PIPE ViPipe,  CLIENT *clnt)
{
	static float clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RPC_CVI_ISP_QueryFps,
		(xdrproc_t) xdr_RPC_VI_PIPE, (caddr_t) &ViPipe,
		(xdrproc_t) xdr_float, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getaelogbuf_1(RPC_VI_PIPE ViPipe,  CLIENT *clnt)
{
	static RPC_ISP_GET_ATTR_DATA_S clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RPC_CVI_ISP_GetAELogBuf,
		(xdrproc_t) xdr_RPC_VI_PIPE, (caddr_t) &ViPipe,
		(xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getaelogbufsize_1(RPC_VI_PIPE ViPipe,  CLIENT *clnt)
{
	static RPC_ISP_GET_ATTR_DATA_S clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RPC_CVI_ISP_GetAELogBufSize,
		(xdrproc_t) xdr_RPC_VI_PIPE, (caddr_t) &ViPipe,
		(xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getaebinbuf_1(RPC_VI_PIPE ViPipe,  CLIENT *clnt)
{
	static RPC_ISP_GET_ATTR_DATA_S clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RPC_CVI_ISP_GetAEBinBuf,
		(xdrproc_t) xdr_RPC_VI_PIPE, (caddr_t) &ViPipe,
		(xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getaebinbufsize_1(RPC_VI_PIPE ViPipe,  CLIENT *clnt)
{
	static RPC_ISP_GET_ATTR_DATA_S clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RPC_CVI_ISP_GetAEBinBufSize,
		(xdrproc_t) xdr_RPC_VI_PIPE, (caddr_t) &ViPipe,
		(xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getcurrentlvx100_1(RPC_VI_PIPE ViPipe,  CLIENT *clnt)
{
	static RPC_ISP_GET_ATTR_DATA_S clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RPC_CVI_ISP_GetCurrentLvX100,
		(xdrproc_t) xdr_RPC_VI_PIPE, (caddr_t) &ViPipe,
		(xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_CVI_S32 *
rpc_cvi_isp_setfastbootexposure_1(RPC_VI_PIPE ViPipe, uint32_t expLine, uint32_t again, uint32_t dgain, uint32_t ispdgain,  CLIENT *clnt)
{
	rpc_cvi_isp_setfastbootexposure_1_argument arg;
	static RPC_CVI_S32 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.ViPipe = ViPipe;
	arg.expLine = expLine;
	arg.again = again;
	arg.dgain = dgain;
	arg.ispdgain = ispdgain;
	if (clnt_call (clnt, RPC_CVI_ISP_SetFastBootExposure, (xdrproc_t) xdr_rpc_cvi_isp_setfastbootexposure_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_RPC_CVI_S32, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_CVI_S32 *
rpc_cvi_isp_setsmartexposureattr_1(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  CLIENT *clnt)
{
	rpc_cvi_isp_setsmartexposureattr_1_argument arg;
	static RPC_CVI_S32 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.ViPipe = ViPipe;
	arg.stAttrData = stAttrData;
	if (clnt_call (clnt, RPC_CVI_ISP_SetSmartExposureAttr, (xdrproc_t) xdr_rpc_cvi_isp_setsmartexposureattr_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_RPC_CVI_S32, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getsmartexposureattr_1(RPC_VI_PIPE ViPipe,  CLIENT *clnt)
{
	static RPC_ISP_GET_ATTR_DATA_S clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RPC_CVI_ISP_GetSmartExposureAttr,
		(xdrproc_t) xdr_RPC_VI_PIPE, (caddr_t) &ViPipe,
		(xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_CVI_S32 *
rpc_cvi_isp_setwbattr_1(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  CLIENT *clnt)
{
	rpc_cvi_isp_setwbattr_1_argument arg;
	static RPC_CVI_S32 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.ViPipe = ViPipe;
	arg.stAttrData = stAttrData;
	if (clnt_call (clnt, RPC_CVI_ISP_SetWBAttr, (xdrproc_t) xdr_rpc_cvi_isp_setwbattr_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_RPC_CVI_S32, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getwbattr_1(RPC_VI_PIPE ViPipe,  CLIENT *clnt)
{
	static RPC_ISP_GET_ATTR_DATA_S clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RPC_CVI_ISP_GetWBAttr,
		(xdrproc_t) xdr_RPC_VI_PIPE, (caddr_t) &ViPipe,
		(xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_CVI_S32 *
rpc_cvi_isp_setawbattrex_1(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  CLIENT *clnt)
{
	rpc_cvi_isp_setawbattrex_1_argument arg;
	static RPC_CVI_S32 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.ViPipe = ViPipe;
	arg.stAttrData = stAttrData;
	if (clnt_call (clnt, RPC_CVI_ISP_SetAWBAttrEx, (xdrproc_t) xdr_rpc_cvi_isp_setawbattrex_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_RPC_CVI_S32, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getawbattrex_1(RPC_VI_PIPE ViPipe,  CLIENT *clnt)
{
	static RPC_ISP_GET_ATTR_DATA_S clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RPC_CVI_ISP_GetAWBAttrEx,
		(xdrproc_t) xdr_RPC_VI_PIPE, (caddr_t) &ViPipe,
		(xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_querywbinfo_1(RPC_VI_PIPE ViPipe,  CLIENT *clnt)
{
	static RPC_ISP_GET_ATTR_DATA_S clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RPC_CVI_ISP_QueryWBInfo,
		(xdrproc_t) xdr_RPC_VI_PIPE, (caddr_t) &ViPipe,
		(xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_CVI_S32 *
rpc_cvi_isp_setwbcalibration_1(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  CLIENT *clnt)
{
	rpc_cvi_isp_setwbcalibration_1_argument arg;
	static RPC_CVI_S32 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.ViPipe = ViPipe;
	arg.stAttrData = stAttrData;
	if (clnt_call (clnt, RPC_CVI_ISP_SetWBCalibration, (xdrproc_t) xdr_rpc_cvi_isp_setwbcalibration_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_RPC_CVI_S32, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getwbcalibration_1(RPC_VI_PIPE ViPipe,  CLIENT *clnt)
{
	static RPC_ISP_GET_ATTR_DATA_S clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RPC_CVI_ISP_GetWBCalibration,
		(xdrproc_t) xdr_RPC_VI_PIPE, (caddr_t) &ViPipe,
		(xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_CVI_S32 *
rpc_cvi_isp_setwbcalibrationex_1(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  CLIENT *clnt)
{
	rpc_cvi_isp_setwbcalibrationex_1_argument arg;
	static RPC_CVI_S32 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.ViPipe = ViPipe;
	arg.stAttrData = stAttrData;
	if (clnt_call (clnt, RPC_CVI_ISP_SetWBCalibrationEx, (xdrproc_t) xdr_rpc_cvi_isp_setwbcalibrationex_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_RPC_CVI_S32, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getwbcalibrationex_1(RPC_VI_PIPE ViPipe,  CLIENT *clnt)
{
	static RPC_ISP_GET_ATTR_DATA_S clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RPC_CVI_ISP_GetWBCalibrationEx,
		(xdrproc_t) xdr_RPC_VI_PIPE, (caddr_t) &ViPipe,
		(xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_CVI_S32 *
rpc_cvi_isp_setawbwinstatictics_1(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData,  CLIENT *clnt)
{
	rpc_cvi_isp_setawbwinstatictics_1_argument arg;
	static RPC_CVI_S32 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.ViPipe = ViPipe;
	arg.stAttrData = stAttrData;
	if (clnt_call (clnt, RPC_CVI_ISP_SetAWBWinStatictics, (xdrproc_t) xdr_rpc_cvi_isp_setawbwinstatictics_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_RPC_CVI_S32, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getawbwinstatictics_1(RPC_VI_PIPE ViPipe,  CLIENT *clnt)
{
	static RPC_ISP_GET_ATTR_DATA_S clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RPC_CVI_ISP_GetAWBWinStatictics,
		(xdrproc_t) xdr_RPC_VI_PIPE, (caddr_t) &ViPipe,
		(xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getawbsnaplogbuf_1(RPC_VI_PIPE ViPipe,  CLIENT *clnt)
{
	static RPC_ISP_GET_ATTR_DATA_S clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RPC_CVI_ISP_GetAWBSnapLogBuf,
		(xdrproc_t) xdr_RPC_VI_PIPE, (caddr_t) &ViPipe,
		(xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getawbdbgbinbuf_1(RPC_VI_PIPE ViPipe,  CLIENT *clnt)
{
	static RPC_ISP_GET_ATTR_DATA_S clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RPC_CVI_ISP_GetAWBDbgBinBuf,
		(xdrproc_t) xdr_RPC_VI_PIPE, (caddr_t) &ViPipe,
		(xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_CVI_S32 *
rpc_cvi_isp_getawbdbgbinsize_1(CLIENT *clnt)
{
	static RPC_CVI_S32 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	 if (clnt_call (clnt, RPC_CVI_ISP_GetAWBDbgBinSize, (xdrproc_t) xdr_void, (caddr_t) NULL,
		(xdrproc_t) xdr_RPC_CVI_S32, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_ISP_GET_ATTR_DATA_S *
rpc_cvi_isp_getawbcurve_1(RPC_VI_PIPE ViPipe,  CLIENT *clnt)
{
	static RPC_ISP_GET_ATTR_DATA_S clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RPC_CVI_ISP_GetAWBCurve,
		(xdrproc_t) xdr_RPC_VI_PIPE, (caddr_t) &ViPipe,
		(xdrproc_t) xdr_RPC_ISP_GET_ATTR_DATA_S, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_CVI_S32 *
rpc_cvi_isp_setawblogpath_1(char *fileName,  CLIENT *clnt)
{
	static RPC_CVI_S32 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RPC_CVI_ISP_SetAWBLogPath,
		(xdrproc_t) xdr_wrapstring, (caddr_t) &fileName,
		(xdrproc_t) xdr_RPC_CVI_S32, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

RPC_CVI_S32 *
rpc_cvi_isp_setawblogname_1(char *fileName,  CLIENT *clnt)
{
	static RPC_CVI_S32 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RPC_CVI_ISP_SetAWBLogName,
		(xdrproc_t) xdr_wrapstring, (caddr_t) &fileName,
		(xdrproc_t) xdr_RPC_CVI_S32, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
