
typedef int           RPC_CVI_S32;
typedef uint32_t      RPC_VI_PIPE;

struct RPC_ISP_SET_ATTR_DATA_S {
	uint8_t data<>;
};

struct RPC_ISP_GET_ATTR_DATA_S {
	int ret;
	uint8_t data<>;
};

program ISP_RPC {
	version ISP_RPC_VERSION {

		/******************************** cvi_isp.h ********************************/
		RPC_CVI_S32 RPC_CVI_ISP_SetPubAttr(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData) = 1;
		RPC_ISP_GET_ATTR_DATA_S RPC_CVI_ISP_GetPubAttr(RPC_VI_PIPE ViPipe) = 2;

		RPC_CVI_S32 RPC_CVI_ISP_SetModParam(RPC_ISP_SET_ATTR_DATA_S stAttrData) = 10;
		RPC_ISP_GET_ATTR_DATA_S RPC_CVI_ISP_GetModParam() = 11;

		RPC_CVI_S32 RPC_CVI_ISP_SetCtrlParam(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData) = 20;
		RPC_ISP_GET_ATTR_DATA_S RPC_CVI_ISP_GetCtrlParam(RPC_VI_PIPE ViPipe) = 21;

		RPC_CVI_S32 RPC_CVI_ISP_SetFMWState(RPC_VI_PIPE ViPipe, uint32_t enState) = 30;
		uint32_t RPC_CVI_ISP_GetFMWState(RPC_VI_PIPE ViPipe) = 31;

		RPC_CVI_S32 RPC_CVI_ISP_SetModuleControl(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData) = 40;
		RPC_ISP_GET_ATTR_DATA_S RPC_CVI_ISP_GetModuleControl(RPC_VI_PIPE ViPipe) = 41;

		RPC_CVI_S32 RPC_CVI_ISP_SetRegister(RPC_VI_PIPE ViPipe, uint32_t u32Addr, uint32_t u32Value) = 50;
		uint32_t RPC_CVI_ISP_GetRegister(RPC_VI_PIPE ViPipe, uint32_t u32Addr) = 51;

		RPC_CVI_S32 RPC_CVI_ISP_SetColorToneAttr(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData) = 60;
		RPC_ISP_GET_ATTR_DATA_S RPC_CVI_ISP_GetColorToneAttr(RPC_VI_PIPE ViPipe) = 61;

		RPC_CVI_S32 RPC_CVI_ISP_SetDehazeAttr(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData) = 70;
		RPC_ISP_GET_ATTR_DATA_S RPC_CVI_ISP_GetDehazeAttr(RPC_VI_PIPE ViPipe) = 71;

		RPC_CVI_S32 RPC_CVI_ISP_SetGammaAttr(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData) = 80;
		RPC_ISP_GET_ATTR_DATA_S RPC_CVI_ISP_GetGammaAttr(RPC_VI_PIPE ViPipe) = 81;

		RPC_CVI_S32 RPC_CVI_ISP_SetGammaCurveType(RPC_VI_PIPE ViPipe, uint32_t curveType) = 90;

		RPC_CVI_S32 RPC_CVI_ISP_SetAutoGammaAttr(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData) = 100;
		RPC_ISP_GET_ATTR_DATA_S RPC_CVI_ISP_GetAutoGammaAttr(RPC_VI_PIPE ViPipe) = 101;

		RPC_CVI_S32 RPC_CVI_ISP_SetStatisticsConfig(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData) = 110;
		RPC_ISP_GET_ATTR_DATA_S RPC_CVI_ISP_GetStatisticsConfig(RPC_VI_PIPE ViPipe) = 111;

		RPC_CVI_S32 RPC_CVI_ISP_SetNRAttr(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData) = 120;
		RPC_ISP_GET_ATTR_DATA_S RPC_CVI_ISP_GetNRAttr(RPC_VI_PIPE ViPipe) = 121;

		RPC_CVI_S32 RPC_CVI_ISP_SetNRFilterAttr(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData) = 130;
		RPC_ISP_GET_ATTR_DATA_S RPC_CVI_ISP_GetNRFilterAttr(RPC_VI_PIPE ViPipe) = 131;

		RPC_CVI_S32 RPC_CVI_ISP_SetRLSCAttr(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData) = 140;
		RPC_ISP_GET_ATTR_DATA_S RPC_CVI_ISP_GetRLSCAttr(RPC_VI_PIPE ViPipe) = 141;

		RPC_CVI_S32 RPC_CVI_ISP_SetYNRAttr(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData) = 150;
		RPC_ISP_GET_ATTR_DATA_S RPC_CVI_ISP_GetYNRAttr(RPC_VI_PIPE ViPipe) = 151;

		RPC_CVI_S32 RPC_CVI_ISP_SetYNRMotionNRAttr(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData) = 160;
		RPC_ISP_GET_ATTR_DATA_S RPC_CVI_ISP_GetYNRMotionNRAttr(RPC_VI_PIPE ViPipe) = 161;

		RPC_CVI_S32 RPC_CVI_ISP_SetYNRFilterAttr(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData) = 170;
		RPC_ISP_GET_ATTR_DATA_S RPC_CVI_ISP_GetYNRFilterAttr(RPC_VI_PIPE ViPipe) = 171;

		RPC_CVI_S32 RPC_CVI_ISP_SetCNRAttr(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData) = 180;
		RPC_ISP_GET_ATTR_DATA_S RPC_CVI_ISP_GetCNRAttr(RPC_VI_PIPE ViPipe) = 181;

		RPC_CVI_S32 RPC_CVI_ISP_SetCACAttr(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData) = 190;
		RPC_ISP_GET_ATTR_DATA_S RPC_CVI_ISP_GetCACAttr(RPC_VI_PIPE ViPipe) = 191;

		RPC_CVI_S32 RPC_CVI_ISP_SetDCIAttr(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData) = 200;
		RPC_ISP_GET_ATTR_DATA_S RPC_CVI_ISP_GetDCIAttr(RPC_VI_PIPE ViPipe) = 201;

		RPC_CVI_S32 RPC_CVI_ISP_SetMeshShadingAttr(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData) = 210;
		RPC_ISP_GET_ATTR_DATA_S RPC_CVI_ISP_GetMeshShadingAttr(RPC_VI_PIPE ViPipe) = 211;

		RPC_CVI_S32 RPC_CVI_ISP_SetMeshShadingGainLutAttr(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData) = 220;
		RPC_ISP_GET_ATTR_DATA_S RPC_CVI_ISP_GetMeshShadingGainLutAttr(RPC_VI_PIPE ViPipe) = 221;

		RPC_CVI_S32 RPC_CVI_ISP_SetRadialShadingAttr(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData) = 230;
		RPC_ISP_GET_ATTR_DATA_S RPC_CVI_ISP_GetRadialShadingAttr(RPC_VI_PIPE ViPipe) = 231;

		RPC_CVI_S32 RPC_CVI_ISP_SetRadialShadingGainLutAttr(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData) = 240;
		RPC_ISP_GET_ATTR_DATA_S RPC_CVI_ISP_GetRadialShadingGainLutAttr(RPC_VI_PIPE ViPipe) = 241;

		RPC_CVI_S32 RPC_CVI_ISP_SetTNRAttr(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData) = 250;
		RPC_ISP_GET_ATTR_DATA_S RPC_CVI_ISP_GetTNRAttr(RPC_VI_PIPE ViPipe) = 251;

		RPC_CVI_S32 RPC_CVI_ISP_SetTNRNoiseModelAttr(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData) = 260;
		RPC_ISP_GET_ATTR_DATA_S RPC_CVI_ISP_GetTNRNoiseModelAttr(RPC_VI_PIPE ViPipe) = 261;

		RPC_CVI_S32 RPC_CVI_ISP_SetTNRLumaMotionAttr(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData) = 270;
		RPC_ISP_GET_ATTR_DATA_S RPC_CVI_ISP_GetTNRLumaMotionAttr(RPC_VI_PIPE ViPipe) = 271;

		RPC_CVI_S32 RPC_CVI_ISP_SetTNRGhostAttr(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData) = 280;
		RPC_ISP_GET_ATTR_DATA_S RPC_CVI_ISP_GetTNRGhostAttr(RPC_VI_PIPE ViPipe) = 281;

		RPC_CVI_S32 RPC_CVI_ISP_SetTNRMtPrtAttr(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData) = 290;
		RPC_ISP_GET_ATTR_DATA_S RPC_CVI_ISP_GetTNRMtPrtAttr(RPC_VI_PIPE ViPipe) = 291;

		RPC_CVI_S32 RPC_CVI_ISP_SetCLutAttr(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData) = 300;
		RPC_ISP_GET_ATTR_DATA_S RPC_CVI_ISP_GetCLutAttr(RPC_VI_PIPE ViPipe) = 301;

		RPC_CVI_S32 RPC_CVI_ISP_SetCLutCoeff(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData) = 310;
		RPC_ISP_GET_ATTR_DATA_S RPC_CVI_ISP_GetCLutCoeff(RPC_VI_PIPE ViPipe) = 311;

		RPC_CVI_S32 RPC_CVI_ISP_SetBlackLevelAttr(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData) = 320;
		RPC_ISP_GET_ATTR_DATA_S RPC_CVI_ISP_GetBlackLevelAttr(RPC_VI_PIPE ViPipe) = 321;

		RPC_CVI_S32 RPC_CVI_ISP_SetDemosaicAttr(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData) = 330;
		RPC_ISP_GET_ATTR_DATA_S RPC_CVI_ISP_GetDemosaicAttr(RPC_VI_PIPE ViPipe) = 331;

		RPC_CVI_S32 RPC_CVI_ISP_SetDemosaicDemoireAttr(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData) = 340;
		RPC_ISP_GET_ATTR_DATA_S RPC_CVI_ISP_GetDemosaicDemoireAttr(RPC_VI_PIPE ViPipe) = 341;

		RPC_CVI_S32 RPC_CVI_ISP_SetDemosaicFilterAttr(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData) = 350;
		RPC_ISP_GET_ATTR_DATA_S RPC_CVI_ISP_GetDemosaicFilterAttr(RPC_VI_PIPE ViPipe) = 351;

		RPC_CVI_S32 RPC_CVI_ISP_SetDemosaicEEAttr(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData) = 360;
		RPC_ISP_GET_ATTR_DATA_S RPC_CVI_ISP_GetDemosaicEEAttr(RPC_VI_PIPE ViPipe) = 361;

		RPC_CVI_S32 RPC_CVI_ISP_SetSaturationAttr(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData) = 370;
		RPC_ISP_GET_ATTR_DATA_S RPC_CVI_ISP_GetSaturationAttr(RPC_VI_PIPE ViPipe) = 371;

		RPC_CVI_S32 RPC_CVI_ISP_SetCCMAttr(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData) = 380;
		RPC_ISP_GET_ATTR_DATA_S RPC_CVI_ISP_GetCCMAttr(RPC_VI_PIPE ViPipe) = 381;

		RPC_CVI_S32 RPC_CVI_ISP_SetHSVAttr(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData) = 390;
		RPC_ISP_GET_ATTR_DATA_S RPC_CVI_ISP_GetHSVAttr(RPC_VI_PIPE ViPipe) = 391;

		RPC_CVI_S32 RPC_CVI_ISP_SetDPDynamicAttr(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData) = 400;
		RPC_ISP_GET_ATTR_DATA_S RPC_CVI_ISP_GetDPDynamicAttr(RPC_VI_PIPE ViPipe) = 401;

		RPC_CVI_S32 RPC_CVI_ISP_SetDPStaticAttr(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData) = 410;
		RPC_ISP_GET_ATTR_DATA_S RPC_CVI_ISP_GetDPStaticAttr(RPC_VI_PIPE ViPipe) = 411;

		RPC_CVI_S32 RPC_CVI_ISP_SetDPCalibrate(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData) = 420;
		RPC_ISP_GET_ATTR_DATA_S RPC_CVI_ISP_GetDPCalibrate(RPC_VI_PIPE ViPipe) = 421;

		RPC_CVI_S32 RPC_CVI_ISP_SetCrosstalkAttr(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData) = 430;
		RPC_ISP_GET_ATTR_DATA_S RPC_CVI_ISP_GetCrosstalkAttr(RPC_VI_PIPE ViPipe) = 431;

		RPC_ISP_GET_ATTR_DATA_S RPC_CVI_ISP_GetAEStatistics(RPC_VI_PIPE ViPipe) = 440;
		RPC_ISP_GET_ATTR_DATA_S RPC_CVI_ISP_GetWBStatistics(RPC_VI_PIPE ViPipe) = 441;
		RPC_ISP_GET_ATTR_DATA_S RPC_CVI_ISP_GetFocusStatistics(RPC_VI_PIPE ViPipe) = 443;
		RPC_ISP_GET_ATTR_DATA_S RPC_CVI_ISP_GetLightboxGain(RPC_VI_PIPE ViPipe) = 444;

		RPC_CVI_S32 RPC_CVI_ISP_SetFSWDRAttr(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData) = 450;
		RPC_ISP_GET_ATTR_DATA_S RPC_CVI_ISP_GetFSWDRAttr(RPC_VI_PIPE ViPipe) = 451;

		RPC_CVI_S32 RPC_CVI_ISP_SetDRCAttr(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData) = 460;
		RPC_ISP_GET_ATTR_DATA_S RPC_CVI_ISP_GetDRCAttr(RPC_VI_PIPE ViPipe) = 461;

		RPC_CVI_S32 RPC_CVI_ISP_SetSharpenAttr(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData) = 470;
		RPC_ISP_GET_ATTR_DATA_S RPC_CVI_ISP_GetSharpenAttr(RPC_VI_PIPE ViPipe) = 471;

		RPC_CVI_S32 RPC_CVI_ISP_SetNoiseProfileAttr(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData) = 480;
		RPC_ISP_GET_ATTR_DATA_S RPC_CVI_ISP_GetNoiseProfileAttr(RPC_VI_PIPE ViPipe) = 481;

		RPC_CVI_S32 RPC_CVI_ISP_SetYContrastAttr(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData) = 490;
		RPC_ISP_GET_ATTR_DATA_S RPC_CVI_ISP_GetYContrastAttr(RPC_VI_PIPE ViPipe) = 491;

		RPC_CVI_S32 RPC_CVI_ISP_SetDCFInfo(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData) = 500;
		RPC_ISP_GET_ATTR_DATA_S RPC_CVI_ISP_GetDCFInfo(RPC_VI_PIPE ViPipe) = 501;

		RPC_ISP_GET_ATTR_DATA_S RPC_CVI_ISP_QueryInnerStateInfo(RPC_VI_PIPE ViPipe) = 510;
		RPC_CVI_S32 RPC_CVI_ISP_GetVDTimeOut(RPC_VI_PIPE ViPipe, uint32_t enIspVDType, uint32_t u32MilliSec) = 511;

		RPC_CVI_S32 RPC_CVI_ISP_SetMonoAttr(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData) = 520;
		RPC_ISP_GET_ATTR_DATA_S RPC_CVI_ISP_GetMonoAttr(RPC_VI_PIPE ViPipe) = 521;

		RPC_CVI_S32 RPC_CVI_ISP_SetDisAttr(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData) = 530;
		RPC_ISP_GET_ATTR_DATA_S RPC_CVI_ISP_GetDisAttr(RPC_VI_PIPE ViPipe) = 531;

		RPC_CVI_S32 RPC_CVI_ISP_SetDisConfig(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData) = 540;
		RPC_ISP_GET_ATTR_DATA_S RPC_CVI_ISP_GetDisConfig(RPC_VI_PIPE ViPipe) = 541;

		RPC_CVI_S32 RPC_CVI_ISP_GetBinStatus(RPC_VI_PIPE ViPipe) = 550;

		RPC_CVI_S32 RPC_CVI_ISP_SetVCAttr(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData) = 560;
		RPC_ISP_GET_ATTR_DATA_S RPC_CVI_ISP_GetVCAttr(RPC_VI_PIPE ViPipe) = 561;

		RPC_CVI_S32 RPC_CVI_ISP_DumpHwRegisterToFile(RPC_VI_PIPE ViPipe, string fileName) = 570;
		RPC_CVI_S32 RPC_CVI_ISP_DumpFrameRawInfoToFile(RPC_VI_PIPE ViPipe, string fileName) = 571;

		RPC_ISP_GET_ATTR_DATA_S RPC_CVI_ISP_IrAutoRunOnce(uint32_t IspDev, RPC_ISP_SET_ATTR_DATA_S stAttrData) = 580;

		RPC_CVI_S32 RPC_CVI_ISP_SetSmartInfo(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData, uint8_t TimeOut) = 590;
		RPC_ISP_GET_ATTR_DATA_S RPC_CVI_ISP_GetSmartInfo(RPC_VI_PIPE ViPipe) = 591;

		/***************cv182x***************************/
		RPC_CVI_S32 RPC_CVI_ISP_SetTNRMotionAdaptAttr(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData) = 600;
		RPC_ISP_GET_ATTR_DATA_S RPC_CVI_ISP_GetTNRMotionAdaptAttr(RPC_VI_PIPE ViPipe) =601;

		RPC_CVI_S32 RPC_CVI_ISP_SetClutSaturationAttr(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData) = 610;
		RPC_ISP_GET_ATTR_DATA_S RPC_CVI_ISP_GetClutSaturationAttr(RPC_VI_PIPE ViPipe) = 611;

		RPC_ISP_GET_ATTR_DATA_S RPC_CVI_ISP_GetGammaCurveByType(RPC_VI_PIPE ViPipe,uint32_t curveType) = 620;

		RPC_CVI_S32 RPC_CVI_ISP_SetPreSharpenAttr(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData) = 630;
		RPC_ISP_GET_ATTR_DATA_S RPC_CVI_ISP_GetPreSharpenAttr(RPC_VI_PIPE ViPipe) = 631;

		RPC_CVI_S32 RPC_CVI_ISP_SetRGBCACAttr(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData) = 640;
		RPC_ISP_GET_ATTR_DATA_S RPC_CVI_ISP_GetRGBCACAttr(RPC_VI_PIPE ViPipe) = 641;

		RPC_CVI_S32 RPC_CVI_ISP_SetCNRMotionNRAttr(RPC_VI_PIPE ViPipe,RPC_ISP_SET_ATTR_DATA_S stAttrData) = 650;
		RPC_ISP_GET_ATTR_DATA_S RPC_CVI_ISP_GetCNRMotionNRAttr(RPC_VI_PIPE ViPipe) = 651;

		RPC_CVI_S32 RPC_CVI_ISP_SetCCMSaturationAttr(RPC_VI_PIPE ViPipe,RPC_ISP_SET_ATTR_DATA_S stAttrData) = 660;
		RPC_ISP_GET_ATTR_DATA_S RPC_CVI_ISP_GetCCMSaturationAttr(RPC_VI_PIPE ViPipe) = 661;

		RPC_CVI_S32 RPC_CVI_ISP_SetCAAttr(RPC_VI_PIPE ViPipe,RPC_ISP_SET_ATTR_DATA_S stAttrData) = 670;
		RPC_ISP_GET_ATTR_DATA_S RPC_CVI_ISP_GetCAAttr(RPC_VI_PIPE ViPipe) = 671;

		RPC_CVI_S32 RPC_CVI_ISP_SetCSCAttr(RPC_VI_PIPE ViPipe,RPC_ISP_SET_ATTR_DATA_S stAttrData) = 680;
		RPC_ISP_GET_ATTR_DATA_S RPC_CVI_ISP_GetCSCAttr(RPC_VI_PIPE ViPipe) = 691;

		/******************************** cvi_ae.h ********************************/
		RPC_CVI_S32 RPC_CVI_ISP_SetExposureAttr(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData) = 2000;
		RPC_ISP_GET_ATTR_DATA_S RPC_CVI_ISP_GetExposureAttr(RPC_VI_PIPE ViPipe) = 2001;

		RPC_ISP_GET_ATTR_DATA_S RPC_CVI_ISP_QueryExposureInfo(RPC_VI_PIPE ViPipe) = 2010;

		RPC_CVI_S32 RPC_CVI_ISP_SetWDRExposureAttr(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData) = 2020;
		RPC_ISP_GET_ATTR_DATA_S RPC_CVI_ISP_GetWDRExposureAttr(RPC_VI_PIPE ViPipe) = 2021;

		RPC_CVI_S32 RPC_CVI_ISP_SetAERouteAttr(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData) = 2030;
		RPC_ISP_GET_ATTR_DATA_S RPC_CVI_ISP_GetAERouteAttr(RPC_VI_PIPE ViPipe) = 2031;

		RPC_CVI_S32 RPC_CVI_ISP_SetAERouteAttrEx(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData) = 2040;
		RPC_ISP_GET_ATTR_DATA_S RPC_CVI_ISP_GetAERouteAttrEx(RPC_VI_PIPE ViPipe) = 2041;

		RPC_CVI_S32 RPC_CVI_ISP_AEBracketingStart(RPC_VI_PIPE ViPipe) = 2050;
		RPC_CVI_S32 RPC_CVI_ISP_AEBracketingSetExpsoure(RPC_VI_PIPE ViPipe, int leEvX10, int seEvX10) = 2051;
		RPC_CVI_S32 RPC_CVI_ISP_AEBracketingFinish(RPC_VI_PIPE ViPipe) = 2052;
		RPC_CVI_S32 RPC_CVI_ISP_AEBracketingSetSimple(uint8_t enable) = 2053;

		RPC_CVI_S32 RPC_CVI_ISP_SetAEStatisticsConfig(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData) = 2060;
		RPC_ISP_GET_ATTR_DATA_S RPC_CVI_ISP_GetAEStatisticsConfig(RPC_VI_PIPE ViPipe) = 2061;

		RPC_CVI_S32 RPC_CVI_ISP_SetAntiFlicker(RPC_VI_PIPE ViPipe, uint8_t enable, uint8_t frequency) = 2070;
		uint32_t RPC_CVI_ISP_GetAntiFlicker(RPC_VI_PIPE ViPipe) = 2071;

		RPC_CVI_S32 RPC_CVI_ISP_SetWDRLEOnly(RPC_VI_PIPE ViPipe, uint8_t wdrLEOnly) = 2080;

		uint32_t RPC_CVI_ISP_GetFrameID(RPC_VI_PIPE ViPipe) = 2090;

		RPC_CVI_S32 RPC_CVI_ISP_SetAELogPath(string fileName) = 2100;
		RPC_ISP_GET_ATTR_DATA_S RPC_CVI_ISP_GetAELogPath(int pathSize) = 2101;

		RPC_CVI_S32 RPC_CVI_ISP_SetAELogName(string fileName) = 2110;
		RPC_ISP_GET_ATTR_DATA_S RPC_CVI_ISP_GetAELogName(int nameSize) = 2111;

		float RPC_CVI_ISP_QueryFps(RPC_VI_PIPE ViPipe) = 2120;

		RPC_ISP_GET_ATTR_DATA_S RPC_CVI_ISP_GetAELogBuf(RPC_VI_PIPE ViPipe) = 2130;

		RPC_ISP_GET_ATTR_DATA_S RPC_CVI_ISP_GetAELogBufSize(RPC_VI_PIPE ViPipe) = 2140;

		RPC_ISP_GET_ATTR_DATA_S RPC_CVI_ISP_GetAEBinBuf(RPC_VI_PIPE ViPipe) = 2150;

		RPC_ISP_GET_ATTR_DATA_S RPC_CVI_ISP_GetAEBinBufSize(RPC_VI_PIPE ViPipe) = 2160;

		RPC_ISP_GET_ATTR_DATA_S RPC_CVI_ISP_GetCurrentLvX100(RPC_VI_PIPE ViPipe) = 2170;

		RPC_CVI_S32 RPC_CVI_ISP_SetFastBootExposure(RPC_VI_PIPE ViPipe, uint32_t expLine, uint32_t again, uint32_t dgain, uint32_t ispdgain) = 2180;

		RPC_CVI_S32 RPC_CVI_ISP_SetSmartExposureAttr(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData) = 2190;
		RPC_ISP_GET_ATTR_DATA_S RPC_CVI_ISP_GetSmartExposureAttr(RPC_VI_PIPE ViPipe) = 2201;

		/******************************** cvi_awb.h ********************************/
		RPC_CVI_S32 RPC_CVI_ISP_SetWBAttr(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData) = 3000;
		RPC_ISP_GET_ATTR_DATA_S RPC_CVI_ISP_GetWBAttr(RPC_VI_PIPE ViPipe) = 3001;

		RPC_CVI_S32 RPC_CVI_ISP_SetAWBAttrEx(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData) = 3010;
		RPC_ISP_GET_ATTR_DATA_S RPC_CVI_ISP_GetAWBAttrEx(RPC_VI_PIPE ViPipe) = 3011;

		RPC_ISP_GET_ATTR_DATA_S RPC_CVI_ISP_QueryWBInfo(RPC_VI_PIPE ViPipe) = 3020;

		RPC_CVI_S32 RPC_CVI_ISP_SetWBCalibration(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData) = 3030;
		RPC_ISP_GET_ATTR_DATA_S RPC_CVI_ISP_GetWBCalibration(RPC_VI_PIPE ViPipe) = 3031;

		RPC_CVI_S32 RPC_CVI_ISP_SetWBCalibrationEx(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData) = 3040;
		RPC_ISP_GET_ATTR_DATA_S RPC_CVI_ISP_GetWBCalibrationEx(RPC_VI_PIPE ViPipe) = 3041;

		RPC_CVI_S32 RPC_CVI_ISP_SetAWBWinStatictics(RPC_VI_PIPE ViPipe, RPC_ISP_SET_ATTR_DATA_S stAttrData) = 3050;
		RPC_ISP_GET_ATTR_DATA_S RPC_CVI_ISP_GetAWBWinStatictics(RPC_VI_PIPE ViPipe) = 3051;

		RPC_ISP_GET_ATTR_DATA_S RPC_CVI_ISP_GetAWBSnapLogBuf(RPC_VI_PIPE ViPipe) = 3060;

		RPC_ISP_GET_ATTR_DATA_S RPC_CVI_ISP_GetAWBDbgBinBuf(RPC_VI_PIPE ViPipe) = 3070;

		RPC_CVI_S32 RPC_CVI_ISP_GetAWBDbgBinSize() = 3080;

		RPC_ISP_GET_ATTR_DATA_S RPC_CVI_ISP_GetAWBCurve(RPC_VI_PIPE ViPipe) = 3090;

		RPC_CVI_S32 RPC_CVI_ISP_SetAWBLogPath(string fileName) = 3100;

		RPC_CVI_S32 RPC_CVI_ISP_SetAWBLogName(string fileName) = 3110;

	} = 1;
} = 0x20000001;
